.PHONY: build test verify

build:
	go build -mod=readonly ./...

test:
	go test -mod=readonly ./...

verify:
	test -z "$$(gofmt -l .)"
	go vet -mod=readonly ./...
	go test -mod=readonly -race -cover ./...
