-- Lock risk: creates new relations and deferred integrity triggers only.
-- Rewrite risk: none on a fresh database. Topic/post counters are checked at commit.

CREATE TABLE public.topics (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_id bigint NOT NULL REFERENCES public.areas (id) ON DELETE RESTRICT,
    author_id bigint NOT NULL REFERENCES public.users (id) ON DELETE RESTRICT,
    title text NOT NULL,
    slug text,
    state text NOT NULL DEFAULT 'open',
    pinned_at timestamp with time zone,
    first_post_id bigint NOT NULL,
    latest_post_id bigint NOT NULL,
    reply_count integer NOT NULL DEFAULT 0,
    next_post_number integer NOT NULL DEFAULT 2,
    created_at timestamp with time zone NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamp with time zone NOT NULL DEFAULT clock_timestamp(),
    last_activity_at timestamp with time zone NOT NULL DEFAULT clock_timestamp(),
    deleted_at timestamp with time zone,
    CONSTRAINT topics_title_length CHECK (char_length(title) BETWEEN 1 AND 200),
    CONSTRAINT topics_slug_format CHECK (
        slug IS NULL
        OR (char_length(slug) BETWEEN 1 AND 120 AND slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$')
    ),
    CONSTRAINT topics_area_slug_unique UNIQUE (area_id, slug),
    CONSTRAINT topics_state_closed CHECK (state IN ('open', 'locked', 'hidden', 'archived')),
    CONSTRAINT topics_reply_count_nonnegative CHECK (reply_count >= 0),
    CONSTRAINT topics_next_post_number_valid CHECK (next_post_number >= 2),
    CONSTRAINT topics_timestamps_ordered CHECK (
        updated_at >= created_at
        AND last_activity_at >= created_at
        AND (pinned_at IS NULL OR pinned_at >= created_at)
        AND (deleted_at IS NULL OR deleted_at >= created_at)
    )
);

CREATE TABLE public.posts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id bigint NOT NULL,
    author_id bigint NOT NULL REFERENCES public.users (id) ON DELETE RESTRICT,
    post_number integer NOT NULL,
    markdown_source text NOT NULL,
    rendered_html text NOT NULL,
    renderer_version text NOT NULL,
    revision integer NOT NULL DEFAULT 1,
    created_at timestamp with time zone NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamp with time zone NOT NULL DEFAULT clock_timestamp(),
    edited_at timestamp with time zone,
    deleted_at timestamp with time zone,
    deleted_by bigint REFERENCES public.users (id) ON DELETE RESTRICT,
    deletion_reason text,
    CONSTRAINT posts_topic_fk FOREIGN KEY (topic_id)
        REFERENCES public.topics (id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT posts_topic_number_unique UNIQUE (topic_id, post_number),
    CONSTRAINT posts_post_number_positive CHECK (post_number > 0),
    CONSTRAINT posts_markdown_size CHECK (octet_length(markdown_source) BETWEEN 1 AND 65536),
    CONSTRAINT posts_rendered_size CHECK (octet_length(rendered_html) <= 262144),
    CONSTRAINT posts_renderer_version_length CHECK (char_length(renderer_version) BETWEEN 1 AND 64),
    CONSTRAINT posts_revision_positive CHECK (revision > 0),
    CONSTRAINT posts_edit_state_consistent CHECK (
        (revision = 1 AND edited_at IS NULL)
        OR (revision > 1 AND edited_at IS NOT NULL AND edited_at >= created_at)
    ),
    CONSTRAINT posts_deletion_state_consistent CHECK (
        (deleted_at IS NULL AND deleted_by IS NULL AND deletion_reason IS NULL)
        OR
        (deleted_at IS NOT NULL
         AND deleted_by IS NOT NULL
         AND deletion_reason IS NOT NULL
         AND deleted_at >= created_at
         AND char_length(deletion_reason) BETWEEN 1 AND 500)
    ),
    CONSTRAINT posts_timestamps_ordered CHECK (updated_at >= created_at)
);

ALTER TABLE public.topics
    ADD CONSTRAINT topics_first_post_fk FOREIGN KEY (first_post_id)
        REFERENCES public.posts (id) DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT topics_latest_post_fk FOREIGN KEY (latest_post_id)
        REFERENCES public.posts (id) DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX topics_area_listing_idx
    ON public.topics (area_id, pinned_at DESC NULLS LAST, last_activity_at DESC, id DESC)
    WHERE deleted_at IS NULL;

CREATE INDEX topics_recent_activity_idx
    ON public.topics (last_activity_at DESC, id DESC)
    WHERE deleted_at IS NULL;

CREATE INDEX posts_topic_order_idx
    ON public.posts (topic_id, post_number);

CREATE FUNCTION public.gotth_reject_post_identity_change()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
    IF NEW.topic_id IS DISTINCT FROM OLD.topic_id
       OR NEW.post_number IS DISTINCT FROM OLD.post_number THEN
        RAISE EXCEPTION 'post topic and number are immutable' USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER posts_identity_immutable
BEFORE UPDATE OF topic_id, post_number ON public.posts
FOR EACH ROW
EXECUTE FUNCTION public.gotth_reject_post_identity_change();

CREATE FUNCTION public.gotth_validate_topic_post_state()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
DECLARE
    target_topic_id bigint;
    topic_first_post_id bigint;
    topic_latest_post_id bigint;
    topic_reply_count integer;
    topic_next_post_number integer;
    first_post_topic_id bigint;
    first_post_number integer;
    latest_post_topic_id bigint;
    latest_post_number integer;
    actual_post_count bigint;
    actual_max_post_number integer;
BEGIN
    IF TG_TABLE_NAME = 'topics' THEN
        target_topic_id := COALESCE(NEW.id, OLD.id);
    ELSE
        target_topic_id := COALESCE(NEW.topic_id, OLD.topic_id);
    END IF;

    SELECT first_post_id, latest_post_id, reply_count, next_post_number
    INTO topic_first_post_id, topic_latest_post_id, topic_reply_count, topic_next_post_number
    FROM public.topics
    WHERE id = target_topic_id;

    IF NOT FOUND THEN
        RETURN NULL;
    END IF;

    SELECT count(*), max(post_number)
    INTO actual_post_count, actual_max_post_number
    FROM public.posts
    WHERE topic_id = target_topic_id;

    SELECT topic_id, post_number
    INTO first_post_topic_id, first_post_number
    FROM public.posts
    WHERE id = topic_first_post_id;

    IF NOT FOUND OR first_post_topic_id <> target_topic_id OR first_post_number <> 1 THEN
        RAISE EXCEPTION 'topic first post is inconsistent' USING ERRCODE = 'check_violation';
    END IF;

    SELECT topic_id, post_number
    INTO latest_post_topic_id, latest_post_number
    FROM public.posts
    WHERE id = topic_latest_post_id;

    IF NOT FOUND
       OR latest_post_topic_id <> target_topic_id
       OR latest_post_number <> actual_max_post_number THEN
        RAISE EXCEPTION 'topic latest post is inconsistent' USING ERRCODE = 'check_violation';
    END IF;

    IF actual_post_count < 1
       OR topic_reply_count <> actual_post_count - 1
       OR topic_next_post_number <> actual_max_post_number + 1 THEN
        RAISE EXCEPTION 'topic post counters are inconsistent' USING ERRCODE = 'check_violation';
    END IF;

    RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER topics_validate_post_state
AFTER INSERT OR UPDATE OR DELETE ON public.topics
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION public.gotth_validate_topic_post_state();

CREATE CONSTRAINT TRIGGER posts_validate_topic_state
AFTER INSERT OR UPDATE OR DELETE ON public.posts
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION public.gotth_validate_topic_post_state();

CREATE TABLE public.topic_reads (
    user_id bigint NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    topic_id bigint NOT NULL REFERENCES public.topics (id) ON DELETE CASCADE,
    last_read_post_number integer NOT NULL,
    read_at timestamp with time zone NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (user_id, topic_id),
    CONSTRAINT topic_reads_post_number_positive CHECK (last_read_post_number > 0)
);

CREATE INDEX topic_reads_topic_user_idx
    ON public.topic_reads (topic_id, user_id);
