-- Lock risk: creates new relations only; no existing application rows are scanned.
-- Rewrite risk: none on a fresh database. Future changes must use expand/migrate/contract.

CREATE TABLE public.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name text NOT NULL,
    email text,
    avatar_url text,
    bio text NOT NULL DEFAULT '',
    role text NOT NULL DEFAULT 'member',
    suspended_at timestamp with time zone,
    suspended_until timestamp with time zone,
    suspension_reason text,
    muted_until timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamp with time zone NOT NULL DEFAULT clock_timestamp(),
    last_login_at timestamp with time zone NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT users_display_name_length CHECK (char_length(display_name) BETWEEN 1 AND 80),
    CONSTRAINT users_email_length CHECK (email IS NULL OR char_length(email) BETWEEN 3 AND 320),
    CONSTRAINT users_avatar_url_length CHECK (avatar_url IS NULL OR char_length(avatar_url) BETWEEN 1 AND 2048),
    CONSTRAINT users_bio_length CHECK (char_length(bio) <= 2000),
    CONSTRAINT users_role_closed CHECK (role IN ('member', 'moderator', 'administrator')),
    CONSTRAINT users_suspension_consistent CHECK (
        (suspended_at IS NULL AND suspended_until IS NULL AND suspension_reason IS NULL)
        OR
        (suspended_at IS NOT NULL
         AND suspended_at >= created_at
         AND suspension_reason IS NOT NULL
         AND char_length(suspension_reason) BETWEEN 1 AND 500
         AND (suspended_until IS NULL OR suspended_until > suspended_at))
    ),
    CONSTRAINT users_muted_after_creation CHECK (muted_until IS NULL OR muted_until > created_at),
    CONSTRAINT users_timestamps_ordered CHECK (updated_at >= created_at AND last_login_at >= created_at)
);

CREATE INDEX users_role_unsuspended_idx
    ON public.users (role, id)
    WHERE suspended_at IS NULL;

CREATE TABLE public.governance_state (
    singleton boolean PRIMARY KEY DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT governance_state_singleton_true CHECK (singleton)
);

INSERT INTO public.governance_state (singleton) VALUES (true);

CREATE TABLE public.external_identities (
    user_id bigint PRIMARY KEY REFERENCES public.users (id) ON DELETE RESTRICT,
    issuer text NOT NULL,
    subject text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT clock_timestamp(),
    last_verified_at timestamp with time zone NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT external_identities_issuer_length CHECK (char_length(issuer) BETWEEN 1 AND 2048),
    CONSTRAINT external_identities_subject_length CHECK (char_length(subject) BETWEEN 1 AND 512),
    CONSTRAINT external_identities_verification_ordered CHECK (last_verified_at >= created_at),
    CONSTRAINT external_identities_issuer_subject_unique UNIQUE (issuer, subject)
);

CREATE TABLE public.sessions (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    token_hash bytea NOT NULL,
    user_id bigint NOT NULL REFERENCES public.users (id) ON DELETE RESTRICT,
    issued_at timestamp with time zone NOT NULL DEFAULT clock_timestamp(),
    last_seen_at timestamp with time zone NOT NULL DEFAULT clock_timestamp(),
    validated_at timestamp with time zone NOT NULL DEFAULT clock_timestamp(),
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    user_agent_hash bytea,
    ip_prefix inet,
    CONSTRAINT sessions_token_hash_length CHECK (octet_length(token_hash) = 32),
    CONSTRAINT sessions_token_hash_unique UNIQUE (token_hash),
    CONSTRAINT sessions_user_agent_hash_length CHECK (user_agent_hash IS NULL OR octet_length(user_agent_hash) = 32),
    CONSTRAINT sessions_times_ordered CHECK (
        last_seen_at >= issued_at
        AND validated_at >= issued_at
        AND expires_at > issued_at
        AND last_seen_at <= expires_at
        AND validated_at <= expires_at
        AND (revoked_at IS NULL OR revoked_at >= issued_at)
    )
);

CREATE INDEX sessions_user_active_idx
    ON public.sessions (user_id, expires_at DESC)
    WHERE revoked_at IS NULL;

CREATE TABLE public.oidc_login_attempts (
    state_hash bytea PRIMARY KEY,
    nonce_ciphertext bytea NOT NULL,
    pkce_verifier_ciphertext bytea NOT NULL,
    purpose text NOT NULL,
    session_id bigint REFERENCES public.sessions (id) ON DELETE CASCADE,
    return_path text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT clock_timestamp(),
    expires_at timestamp with time zone NOT NULL,
    consumed_at timestamp with time zone,
    CONSTRAINT oidc_login_attempts_state_hash_length CHECK (octet_length(state_hash) = 32),
    CONSTRAINT oidc_login_attempts_nonce_length CHECK (octet_length(nonce_ciphertext) BETWEEN 1 AND 4096),
    CONSTRAINT oidc_login_attempts_pkce_length CHECK (octet_length(pkce_verifier_ciphertext) BETWEEN 1 AND 4096),
    CONSTRAINT oidc_login_attempts_purpose_closed CHECK (purpose IN ('login', 'revalidate')),
    CONSTRAINT oidc_login_attempts_session_matches_purpose CHECK (
        (purpose = 'login' AND session_id IS NULL)
        OR (purpose = 'revalidate' AND session_id IS NOT NULL)
    ),
    CONSTRAINT oidc_login_attempts_return_path_internal CHECK (
        char_length(return_path) BETWEEN 3 AND 2048
        AND (return_path = '/bb' OR return_path LIKE '/bb/%' OR return_path LIKE '/bb?%')
        AND return_path NOT LIKE '%://%'
        AND return_path NOT LIKE E'%\\%'
    ),
    CONSTRAINT oidc_login_attempts_times_ordered CHECK (
        expires_at > created_at
        AND (consumed_at IS NULL OR consumed_at BETWEEN created_at AND expires_at)
    )
);

CREATE INDEX oidc_login_attempts_expiry_idx
    ON public.oidc_login_attempts (expires_at)
    WHERE consumed_at IS NULL;
