// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_administration.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const administrationMembershipExists = `-- name: AdministrationMembershipExists :one
SELECT EXISTS (
    SELECT 1
    FROM public.forum_group_members AS membership
    WHERE membership.user_id = $1
      AND membership.group_id = $2
)::boolean
`

type AdministrationMembershipExistsParams struct {
	UserID  int64
	GroupID int64
}

func (q *Queries) AdministrationMembershipExists(ctx context.Context, arg AdministrationMembershipExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, administrationMembershipExists, arg.UserID, arg.GroupID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const changeAdministrationRoleAndAudit = `-- name: ChangeAdministrationRoleAndAudit :one
WITH changed AS (
    UPDATE public.users AS forum_user
    SET role = $1,
        updated_at = GREATEST(forum_user.updated_at, $2::timestamptz),
        administration_revision = forum_user.administration_revision + 1
    WHERE forum_user.id = $3
      AND forum_user.role = $4
      AND forum_user.administration_revision = $5
      AND forum_user.administration_revision < 9223372036854775807
    RETURNING forum_user.id, forum_user.role, forum_user.updated_at,
              forum_user.administration_revision
), audit AS (
    INSERT INTO public.moderation_actions (
        actor_kind, actor_user_id, target_type, target_user_id,
        action_type, reason, previous_state, resulting_state,
        request_id, created_at
    )
    SELECT 'forum_user', $6, 'user', changed.id,
           'change_role', $7,
           jsonb_build_object('role', $4::text,
                              'administration_revision', $5::bigint),
           jsonb_build_object('role', changed.role,
                              'administration_revision', changed.administration_revision),
           $8, changed.updated_at
    FROM changed
    RETURNING id, target_user_id
), revoked AS (
    UPDATE public.sessions AS session
    SET revoked_at = GREATEST(session.issued_at, $2::timestamptz)
    FROM changed
    WHERE session.user_id = changed.id
      AND session.revoked_at IS NULL
    RETURNING session.id
)
SELECT changed.id AS user_id, changed.role,
       changed.administration_revision, audit.id AS audit_id,
       (SELECT count(*)::bigint FROM revoked) AS revoked_sessions
FROM changed
JOIN audit ON audit.target_user_id = changed.id
`

type ChangeAdministrationRoleAndAuditParams struct {
	Role             string
	ObservedAt       pgtype.Timestamptz
	TargetUserID     int64
	ExpectedRole     string
	ExpectedRevision int64
	ActorUserID      pgtype.Int8
	Reason           pgtype.Text
	RequestID        pgtype.UUID
}

type ChangeAdministrationRoleAndAuditRow struct {
	UserID                 int64
	Role                   string
	AdministrationRevision int64
	AuditID                int64
	RevokedSessions        int64
}

func (q *Queries) ChangeAdministrationRoleAndAudit(ctx context.Context, arg ChangeAdministrationRoleAndAuditParams) (ChangeAdministrationRoleAndAuditRow, error) {
	row := q.db.QueryRow(ctx, changeAdministrationRoleAndAudit,
		arg.Role,
		arg.ObservedAt,
		arg.TargetUserID,
		arg.ExpectedRole,
		arg.ExpectedRevision,
		arg.ActorUserID,
		arg.Reason,
		arg.RequestID,
	)
	var i ChangeAdministrationRoleAndAuditRow
	err := row.Scan(
		&i.UserID,
		&i.Role,
		&i.AdministrationRevision,
		&i.AuditID,
		&i.RevokedSessions,
	)
	return i, err
}

const createAdministrationGroupAndAudit = `-- name: CreateAdministrationGroupAndAudit :one
WITH created AS (
    INSERT INTO public.forum_groups (name, created_by, created_at, updated_at)
    VALUES ($1, $2, $3::timestamptz, $3::timestamptz)
    RETURNING id, name, administration_revision
), audit AS (
    INSERT INTO public.moderation_actions (
        actor_kind, actor_user_id, target_type, target_group_id,
        action_type, reason, previous_state, resulting_state,
        request_id, created_at
    )
    SELECT 'forum_user', $2, 'group', created.id,
           'create_group', $4, '{}'::jsonb,
           jsonb_build_object('name', created.name, 'administration_revision', created.administration_revision),
           $5, $3::timestamptz
    FROM created
    RETURNING id, target_group_id
)
SELECT created.id AS group_id, created.name,
       created.administration_revision, audit.id AS audit_id
FROM created
JOIN audit ON audit.target_group_id = created.id
`

type CreateAdministrationGroupAndAuditParams struct {
	Name        string
	ActorUserID int64
	ObservedAt  pgtype.Timestamptz
	Reason      pgtype.Text
	RequestID   pgtype.UUID
}

type CreateAdministrationGroupAndAuditRow struct {
	GroupID                int64
	Name                   string
	AdministrationRevision int64
	AuditID                int64
}

func (q *Queries) CreateAdministrationGroupAndAudit(ctx context.Context, arg CreateAdministrationGroupAndAuditParams) (CreateAdministrationGroupAndAuditRow, error) {
	row := q.db.QueryRow(ctx, createAdministrationGroupAndAudit,
		arg.Name,
		arg.ActorUserID,
		arg.ObservedAt,
		arg.Reason,
		arg.RequestID,
	)
	var i CreateAdministrationGroupAndAuditRow
	err := row.Scan(
		&i.GroupID,
		&i.Name,
		&i.AdministrationRevision,
		&i.AuditID,
	)
	return i, err
}

const grantAdministrationMembershipAndAudit = `-- name: GrantAdministrationMembershipAndAudit :one
WITH mapping AS (
    INSERT INTO public.forum_group_members (group_id, user_id, granted_by, created_at)
    VALUES ($1, $2, $3, $4::timestamptz)
    ON CONFLICT (group_id, user_id) DO NOTHING
    RETURNING group_id, user_id
), changed AS (
    UPDATE public.users AS forum_user
    SET administration_revision = forum_user.administration_revision + 1,
        updated_at = GREATEST(forum_user.updated_at, $4::timestamptz)
    FROM mapping
    WHERE forum_user.id = mapping.user_id
      AND forum_user.administration_revision = $5
      AND forum_user.administration_revision < 9223372036854775807
    RETURNING forum_user.id, forum_user.updated_at,
              forum_user.administration_revision
), audit AS (
    INSERT INTO public.moderation_actions (
        actor_kind, actor_user_id, target_type, target_user_id,
        action_type, reason, previous_state, resulting_state,
        request_id, created_at
    )
    SELECT 'forum_user', $3, 'user', changed.id,
           'grant_group_membership', $6,
           jsonb_build_object('group_id', mapping.group_id, 'member', false,
                              'administration_revision', $5::bigint),
           jsonb_build_object('group_id', mapping.group_id, 'member', true,
                              'administration_revision', changed.administration_revision),
           $7, changed.updated_at
    FROM changed
    JOIN mapping ON mapping.user_id = changed.id
    RETURNING id, target_user_id
)
SELECT changed.id AS user_id, changed.administration_revision,
       audit.id AS audit_id
FROM changed
JOIN audit ON audit.target_user_id = changed.id
`

type GrantAdministrationMembershipAndAuditParams struct {
	GroupID          int64
	TargetUserID     int64
	ActorUserID      int64
	ObservedAt       pgtype.Timestamptz
	ExpectedRevision int64
	Reason           pgtype.Text
	RequestID        pgtype.UUID
}

type GrantAdministrationMembershipAndAuditRow struct {
	UserID                 int64
	AdministrationRevision int64
	AuditID                int64
}

func (q *Queries) GrantAdministrationMembershipAndAudit(ctx context.Context, arg GrantAdministrationMembershipAndAuditParams) (GrantAdministrationMembershipAndAuditRow, error) {
	row := q.db.QueryRow(ctx, grantAdministrationMembershipAndAudit,
		arg.GroupID,
		arg.TargetUserID,
		arg.ActorUserID,
		arg.ObservedAt,
		arg.ExpectedRevision,
		arg.Reason,
		arg.RequestID,
	)
	var i GrantAdministrationMembershipAndAuditRow
	err := row.Scan(&i.UserID, &i.AdministrationRevision, &i.AuditID)
	return i, err
}

const listAccountGroupsForAdministration = `-- name: ListAccountGroupsForAdministration :many
WITH actor AS MATERIALIZED (
    SELECT forum_user.id
    FROM public.users AS forum_user
    WHERE forum_user.id = $1
      AND forum_user.role = 'administrator'
      AND (
          forum_user.suspended_at IS NULL
          OR forum_user.suspended_at > $2::timestamptz
          OR forum_user.suspended_until <= $2::timestamptz
      )
      AND (forum_user.muted_until IS NULL OR forum_user.muted_until <= $2::timestamptz)
), target AS MATERIALIZED (
    SELECT forum_user.id
    FROM actor
    JOIN public.users AS forum_user ON forum_user.id = $3
), candidate AS MATERIALIZED (
    SELECT forum_group.id, forum_group.name,
           EXISTS (
               SELECT 1
               FROM public.forum_group_members AS membership
               WHERE membership.user_id = target.id
                 AND membership.group_id = forum_group.id
           )::boolean AS member
    FROM target
    JOIN LATERAL (
        SELECT group_row.id, group_row.name
        FROM public.forum_groups AS group_row
        WHERE group_row.id > $4
        ORDER BY group_row.id
        LIMIT $5
    ) AS forum_group ON true
)
SELECT (target.id IS NOT NULL)::boolean AS account_present,
       (candidate.id IS NOT NULL)::boolean AS group_present,
       COALESCE(candidate.id, 0)::bigint AS group_id,
       COALESCE(candidate.name, '')::text AS group_name,
       COALESCE(candidate.member, false)::boolean AS member
FROM actor
LEFT JOIN target ON true
LEFT JOIN candidate ON true
ORDER BY candidate.id NULLS LAST
`

type ListAccountGroupsForAdministrationParams struct {
	ActorUserID  int64
	ObservedAt   pgtype.Timestamptz
	TargetUserID int64
	AfterGroupID int64
	PageLimit    int32
}

type ListAccountGroupsForAdministrationRow struct {
	AccountPresent bool
	GroupPresent   bool
	GroupID        int64
	GroupName      string
	Member         bool
}

func (q *Queries) ListAccountGroupsForAdministration(ctx context.Context, arg ListAccountGroupsForAdministrationParams) ([]ListAccountGroupsForAdministrationRow, error) {
	rows, err := q.db.Query(ctx, listAccountGroupsForAdministration,
		arg.ActorUserID,
		arg.ObservedAt,
		arg.TargetUserID,
		arg.AfterGroupID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountGroupsForAdministrationRow{}
	for rows.Next() {
		var i ListAccountGroupsForAdministrationRow
		if err := rows.Scan(
			&i.AccountPresent,
			&i.GroupPresent,
			&i.GroupID,
			&i.GroupName,
			&i.Member,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountsForAdministration = `-- name: ListAccountsForAdministration :many
WITH actor AS MATERIALIZED (
    SELECT forum_user.id
    FROM public.users AS forum_user
    WHERE forum_user.id = $2
      AND forum_user.role = 'administrator'
      AND (
          forum_user.suspended_at IS NULL
          OR forum_user.suspended_at > $1::timestamptz
          OR forum_user.suspended_until <= $1::timestamptz
      )
      AND (forum_user.muted_until IS NULL OR forum_user.muted_until <= $1::timestamptz)
), account AS MATERIALIZED (
    SELECT target.id, target.display_name, target.role,
           target.suspended_at, target.suspended_until,
           target.created_at, target.updated_at,
           target.administration_revision
    FROM actor
    JOIN LATERAL (
        SELECT forum_user.id, forum_user.display_name, forum_user.role,
               forum_user.suspended_at, forum_user.suspended_until,
               forum_user.created_at, forum_user.updated_at,
               forum_user.administration_revision
        FROM public.users AS forum_user
        WHERE forum_user.id > $3
        ORDER BY forum_user.id
        LIMIT $4
    ) AS target ON true
)
SELECT (account.id IS NOT NULL)::boolean AS account_present,
       COALESCE(account.id, 0)::bigint AS id,
       COALESCE(account.display_name, '')::text AS display_name,
       COALESCE(account.role, '')::text AS role,
       COALESCE(account.suspended_at <= $1::timestamptz
                AND (account.suspended_until IS NULL OR account.suspended_until > $1::timestamptz), false)::boolean AS suspended,
       account.created_at, account.updated_at,
       COALESCE(account.administration_revision, 0)::bigint AS administration_revision
FROM actor
LEFT JOIN account ON true
ORDER BY account.id NULLS LAST
`

type ListAccountsForAdministrationParams struct {
	ObservedAt  pgtype.Timestamptz
	ActorUserID int64
	AfterUserID int64
	PageLimit   int32
}

type ListAccountsForAdministrationRow struct {
	AccountPresent         bool
	ID                     int64
	DisplayName            string
	Role                   string
	Suspended              bool
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	AdministrationRevision int64
}

func (q *Queries) ListAccountsForAdministration(ctx context.Context, arg ListAccountsForAdministrationParams) ([]ListAccountsForAdministrationRow, error) {
	rows, err := q.db.Query(ctx, listAccountsForAdministration,
		arg.ObservedAt,
		arg.ActorUserID,
		arg.AfterUserID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsForAdministrationRow{}
	for rows.Next() {
		var i ListAccountsForAdministrationRow
		if err := rows.Scan(
			&i.AccountPresent,
			&i.ID,
			&i.DisplayName,
			&i.Role,
			&i.Suspended,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AdministrationRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsForAdministration = `-- name: ListGroupsForAdministration :many
WITH actor AS MATERIALIZED (
    SELECT forum_user.id
    FROM public.users AS forum_user
    WHERE forum_user.id = $1
      AND forum_user.role = 'administrator'
      AND (
          forum_user.suspended_at IS NULL
          OR forum_user.suspended_at > $2::timestamptz
          OR forum_user.suspended_until <= $2::timestamptz
      )
      AND (forum_user.muted_until IS NULL OR forum_user.muted_until <= $2::timestamptz)
), candidate AS MATERIALIZED (
    SELECT forum_group.id, forum_group.name, forum_group.created_at,
           forum_group.updated_at, forum_group.administration_revision
    FROM actor
    JOIN LATERAL (
        SELECT group_row.id, group_row.name, group_row.created_at,
               group_row.updated_at, group_row.administration_revision
        FROM public.forum_groups AS group_row
        WHERE group_row.id > $3
        ORDER BY group_row.id
        LIMIT $4
    ) AS forum_group ON true
)
SELECT (candidate.id IS NOT NULL)::boolean AS group_present,
       COALESCE(candidate.id, 0)::bigint AS id,
       COALESCE(candidate.name, '')::text AS name,
       candidate.created_at, candidate.updated_at,
       COALESCE(candidate.administration_revision, 0)::bigint AS administration_revision
FROM actor
LEFT JOIN candidate ON true
ORDER BY candidate.id NULLS LAST
`

type ListGroupsForAdministrationParams struct {
	ActorUserID  int64
	ObservedAt   pgtype.Timestamptz
	AfterGroupID int64
	PageLimit    int32
}

type ListGroupsForAdministrationRow struct {
	GroupPresent           bool
	ID                     int64
	Name                   string
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	AdministrationRevision int64
}

func (q *Queries) ListGroupsForAdministration(ctx context.Context, arg ListGroupsForAdministrationParams) ([]ListGroupsForAdministrationRow, error) {
	rows, err := q.db.Query(ctx, listGroupsForAdministration,
		arg.ActorUserID,
		arg.ObservedAt,
		arg.AfterGroupID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupsForAdministrationRow{}
	for rows.Next() {
		var i ListGroupsForAdministrationRow
		if err := rows.Scan(
			&i.GroupPresent,
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AdministrationRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadAccountForAdministration = `-- name: LoadAccountForAdministration :one
WITH actor AS MATERIALIZED (
    SELECT forum_user.id
    FROM public.users AS forum_user
    WHERE forum_user.id = $2
      AND forum_user.role = 'administrator'
      AND (
          forum_user.suspended_at IS NULL
          OR forum_user.suspended_at > $1::timestamptz
          OR forum_user.suspended_until <= $1::timestamptz
      )
      AND (forum_user.muted_until IS NULL OR forum_user.muted_until <= $1::timestamptz)
), target AS MATERIALIZED (
    SELECT forum_user.id, forum_user.display_name, forum_user.role,
           forum_user.suspended_at, forum_user.suspended_until,
           forum_user.created_at, forum_user.updated_at,
           forum_user.administration_revision
    FROM actor
    JOIN public.users AS forum_user ON forum_user.id = $3
)
SELECT (target.id IS NOT NULL)::boolean AS account_present,
       COALESCE(target.id, 0)::bigint AS id,
       COALESCE(target.display_name, '')::text AS display_name,
       COALESCE(target.role, '')::text AS role,
       COALESCE(target.suspended_at <= $1::timestamptz
                AND (target.suspended_until IS NULL OR target.suspended_until > $1::timestamptz), false)::boolean AS suspended,
       target.created_at, target.updated_at,
       COALESCE(target.administration_revision, 0)::bigint AS administration_revision
FROM actor
LEFT JOIN target ON true
`

type LoadAccountForAdministrationParams struct {
	ObservedAt   pgtype.Timestamptz
	ActorUserID  int64
	TargetUserID int64
}

type LoadAccountForAdministrationRow struct {
	AccountPresent         bool
	ID                     int64
	DisplayName            string
	Role                   string
	Suspended              bool
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	AdministrationRevision int64
}

func (q *Queries) LoadAccountForAdministration(ctx context.Context, arg LoadAccountForAdministrationParams) (LoadAccountForAdministrationRow, error) {
	row := q.db.QueryRow(ctx, loadAccountForAdministration, arg.ObservedAt, arg.ActorUserID, arg.TargetUserID)
	var i LoadAccountForAdministrationRow
	err := row.Scan(
		&i.AccountPresent,
		&i.ID,
		&i.DisplayName,
		&i.Role,
		&i.Suspended,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AdministrationRevision,
	)
	return i, err
}

const lockAdministrationGroup = `-- name: LockAdministrationGroup :one
SELECT forum_group.id, forum_group.name, forum_group.created_by,
       forum_group.created_at, forum_group.updated_at,
       forum_group.administration_revision
FROM public.forum_groups AS forum_group
WHERE forum_group.id = $1
FOR UPDATE OF forum_group
`

func (q *Queries) LockAdministrationGroup(ctx context.Context, groupID int64) (ForumGroup, error) {
	row := q.db.QueryRow(ctx, lockAdministrationGroup, groupID)
	var i ForumGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AdministrationRevision,
	)
	return i, err
}

const lockAdministrationUser = `-- name: LockAdministrationUser :one
SELECT forum_user.id, forum_user.display_name, forum_user.role,
       forum_user.suspended_at, forum_user.suspended_until,
       forum_user.muted_until, forum_user.created_at, forum_user.updated_at,
       forum_user.administration_revision
FROM public.users AS forum_user
WHERE forum_user.id = $1
FOR UPDATE OF forum_user
`

type LockAdministrationUserRow struct {
	ID                     int64
	DisplayName            string
	Role                   string
	SuspendedAt            pgtype.Timestamptz
	SuspendedUntil         pgtype.Timestamptz
	MutedUntil             pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	AdministrationRevision int64
}

func (q *Queries) LockAdministrationUser(ctx context.Context, userID int64) (LockAdministrationUserRow, error) {
	row := q.db.QueryRow(ctx, lockAdministrationUser, userID)
	var i LockAdministrationUserRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Role,
		&i.SuspendedAt,
		&i.SuspendedUntil,
		&i.MutedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AdministrationRevision,
	)
	return i, err
}

const renameAdministrationGroupAndAudit = `-- name: RenameAdministrationGroupAndAudit :one
WITH changed AS (
    UPDATE public.forum_groups AS forum_group
    SET name = $1,
        updated_at = GREATEST(forum_group.updated_at, $2::timestamptz),
        administration_revision = forum_group.administration_revision + 1
    WHERE forum_group.id = $3
      AND forum_group.administration_revision = $4
      AND forum_group.administration_revision < 9223372036854775807
    RETURNING forum_group.id, forum_group.name, forum_group.updated_at,
              forum_group.administration_revision
), audit AS (
    INSERT INTO public.moderation_actions (
        actor_kind, actor_user_id, target_type, target_group_id,
        action_type, reason, previous_state, resulting_state,
        request_id, created_at
    )
    SELECT 'forum_user', $5, 'group', changed.id,
           'rename_group', $6,
           jsonb_build_object('name', $7::text,
                              'administration_revision', $4::bigint),
           jsonb_build_object('name', changed.name,
                              'administration_revision', changed.administration_revision),
           $8, changed.updated_at
    FROM changed
    RETURNING id, target_group_id
)
SELECT changed.id AS group_id, changed.name,
       changed.administration_revision, audit.id AS audit_id
FROM changed
JOIN audit ON audit.target_group_id = changed.id
`

type RenameAdministrationGroupAndAuditParams struct {
	Name             string
	ObservedAt       pgtype.Timestamptz
	GroupID          int64
	ExpectedRevision int64
	ActorUserID      pgtype.Int8
	Reason           pgtype.Text
	PreviousName     string
	RequestID        pgtype.UUID
}

type RenameAdministrationGroupAndAuditRow struct {
	GroupID                int64
	Name                   string
	AdministrationRevision int64
	AuditID                int64
}

func (q *Queries) RenameAdministrationGroupAndAudit(ctx context.Context, arg RenameAdministrationGroupAndAuditParams) (RenameAdministrationGroupAndAuditRow, error) {
	row := q.db.QueryRow(ctx, renameAdministrationGroupAndAudit,
		arg.Name,
		arg.ObservedAt,
		arg.GroupID,
		arg.ExpectedRevision,
		arg.ActorUserID,
		arg.Reason,
		arg.PreviousName,
		arg.RequestID,
	)
	var i RenameAdministrationGroupAndAuditRow
	err := row.Scan(
		&i.GroupID,
		&i.Name,
		&i.AdministrationRevision,
		&i.AuditID,
	)
	return i, err
}

const revokeAdministrationMembershipAndAudit = `-- name: RevokeAdministrationMembershipAndAudit :one
WITH mapping AS (
    DELETE FROM public.forum_group_members AS membership
    WHERE membership.group_id = $1
      AND membership.user_id = $2
    RETURNING membership.group_id, membership.user_id
), changed AS (
    UPDATE public.users AS forum_user
    SET administration_revision = forum_user.administration_revision + 1,
        updated_at = GREATEST(forum_user.updated_at, $3::timestamptz)
    FROM mapping
    WHERE forum_user.id = mapping.user_id
      AND forum_user.administration_revision = $4
      AND forum_user.administration_revision < 9223372036854775807
    RETURNING forum_user.id, forum_user.updated_at,
              forum_user.administration_revision
), audit AS (
    INSERT INTO public.moderation_actions (
        actor_kind, actor_user_id, target_type, target_user_id,
        action_type, reason, previous_state, resulting_state,
        request_id, created_at
    )
    SELECT 'forum_user', $5, 'user', changed.id,
           'revoke_group_membership', $6,
           jsonb_build_object('group_id', mapping.group_id, 'member', true,
                              'administration_revision', $4::bigint),
           jsonb_build_object('group_id', mapping.group_id, 'member', false,
                              'administration_revision', changed.administration_revision),
           $7, changed.updated_at
    FROM changed
    JOIN mapping ON mapping.user_id = changed.id
    RETURNING id, target_user_id
)
SELECT changed.id AS user_id, changed.administration_revision,
       audit.id AS audit_id
FROM changed
JOIN audit ON audit.target_user_id = changed.id
`

type RevokeAdministrationMembershipAndAuditParams struct {
	GroupID          int64
	TargetUserID     int64
	ObservedAt       pgtype.Timestamptz
	ExpectedRevision int64
	ActorUserID      pgtype.Int8
	Reason           pgtype.Text
	RequestID        pgtype.UUID
}

type RevokeAdministrationMembershipAndAuditRow struct {
	UserID                 int64
	AdministrationRevision int64
	AuditID                int64
}

func (q *Queries) RevokeAdministrationMembershipAndAudit(ctx context.Context, arg RevokeAdministrationMembershipAndAuditParams) (RevokeAdministrationMembershipAndAuditRow, error) {
	row := q.db.QueryRow(ctx, revokeAdministrationMembershipAndAudit,
		arg.GroupID,
		arg.TargetUserID,
		arg.ObservedAt,
		arg.ExpectedRevision,
		arg.ActorUserID,
		arg.Reason,
		arg.RequestID,
	)
	var i RevokeAdministrationMembershipAndAuditRow
	err := row.Scan(&i.UserID, &i.AdministrationRevision, &i.AuditID)
	return i, err
}
