// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: administration_sessions_email.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeEmailTestAndAudit = `-- name: CompleteEmailTestAndAudit :one
WITH completed AS (
    UPDATE public.email_test_state AS state
    SET status = $1,
        completed_at = $2::timestamptz
    WHERE state.administrator_id = $3
      AND state.idempotency_key = $4
      AND state.status = 'requested'
      AND $1::text IN ('accepted', 'failed', 'unknown')
    RETURNING state.administrator_id, state.status, state.completed_at
), audit AS (
    INSERT INTO public.moderation_actions (
        actor_kind, actor_user_id, target_type, target_user_id,
        action_type, reason, previous_state, resulting_state,
        request_id, created_at
    )
    SELECT 'forum_user', completed.administrator_id, 'user',
           completed.administrator_id, 'test_email', $5,
           jsonb_build_object(
               'status', 'requested',
               'idempotency_sha256', $6::text
           ),
           jsonb_build_object(
               'status', completed.status,
               'idempotency_sha256', $6::text
           ),
           $7, completed.completed_at
    FROM completed
    RETURNING id
)
SELECT completed.status, completed.completed_at, audit.id AS audit_id
FROM completed
JOIN audit ON true
`

type CompleteEmailTestAndAuditParams struct {
	Status            string
	ObservedAt        pgtype.Timestamptz
	ActorUserID       int64
	IdempotencyKey    pgtype.UUID
	Reason            pgtype.Text
	IdempotencySha256 string
	RequestID         pgtype.UUID
}

type CompleteEmailTestAndAuditRow struct {
	Status      string
	CompletedAt pgtype.Timestamptz
	AuditID     int64
}

func (q *Queries) CompleteEmailTestAndAudit(ctx context.Context, arg CompleteEmailTestAndAuditParams) (CompleteEmailTestAndAuditRow, error) {
	row := q.db.QueryRow(ctx, completeEmailTestAndAudit,
		arg.Status,
		arg.ObservedAt,
		arg.ActorUserID,
		arg.IdempotencyKey,
		arg.Reason,
		arg.IdempotencySha256,
		arg.RequestID,
	)
	var i CompleteEmailTestAndAuditRow
	err := row.Scan(&i.Status, &i.CompletedAt, &i.AuditID)
	return i, err
}

const listSessionsForAdministration = `-- name: ListSessionsForAdministration :many
WITH actor AS MATERIALIZED (
    SELECT forum_user.id
    FROM public.users AS forum_user
    WHERE forum_user.id = $1
      AND forum_user.role = 'administrator'
      AND forum_user.authentik_sync_state = 'accepted'
      AND (
          forum_user.suspended_at IS NULL
          OR forum_user.suspended_at > $2::timestamptz
          OR forum_user.suspended_until <= $2::timestamptz
      )
      AND (forum_user.muted_until IS NULL OR forum_user.muted_until <= $2::timestamptz)
), target AS MATERIALIZED (
    SELECT forum_user.id, forum_user.display_name,
           forum_user.administration_revision
    FROM actor
    JOIN public.users AS forum_user
      ON forum_user.id = $3
), settings AS MATERIALIZED (
    SELECT session_idle_seconds
    FROM public.site_settings
    WHERE singleton
      AND (SELECT count(*) FROM public.site_settings) = 1
), candidate AS MATERIALIZED (
    SELECT local_session.id, local_session.issued_at,
           local_session.last_seen_at, local_session.validated_at,
           local_session.expires_at
    FROM target
    JOIN settings ON true
    JOIN LATERAL (
        SELECT session_row.id, session_row.issued_at,
               session_row.last_seen_at, session_row.validated_at,
               session_row.expires_at
        FROM public.sessions AS session_row
        WHERE session_row.user_id = target.id
          AND session_row.revoked_at IS NULL
          AND session_row.issued_at <= $2::timestamptz
          AND session_row.last_seen_at <= $2::timestamptz
          AND session_row.validated_at <= $2::timestamptz
          AND session_row.expires_at > $2::timestamptz
          AND session_row.last_seen_at >
              $2::timestamptz
              - pg_catalog.make_interval(secs => settings.session_idle_seconds)
        ORDER BY session_row.id DESC
        LIMIT $4
    ) AS local_session ON true
)
SELECT (actor.id IS NOT NULL)::boolean AS actor_present,
       (target.id IS NOT NULL)::boolean AS target_present,
       (settings.session_idle_seconds IS NOT NULL)::boolean AS settings_present,
       COALESCE(target.id, 0)::bigint AS target_user_id,
       COALESCE(target.display_name, '')::text AS display_name,
       COALESCE(target.administration_revision, 0)::bigint AS target_revision,
       (candidate.id IS NOT NULL)::boolean AS session_present,
       COALESCE(candidate.id, 0)::bigint AS session_id,
       candidate.issued_at,
       candidate.last_seen_at,
       candidate.validated_at,
       candidate.expires_at
FROM (VALUES (true)) AS anchor(singleton)
LEFT JOIN actor ON true
LEFT JOIN target ON true
LEFT JOIN settings ON true
LEFT JOIN candidate ON true
ORDER BY candidate.id DESC NULLS LAST
`

type ListSessionsForAdministrationParams struct {
	ActorUserID  int64
	ObservedAt   pgtype.Timestamptz
	TargetUserID int64
	PageLimit    int32
}

type ListSessionsForAdministrationRow struct {
	ActorPresent    bool
	TargetPresent   bool
	SettingsPresent bool
	TargetUserID    int64
	DisplayName     string
	TargetRevision  int64
	SessionPresent  bool
	SessionID       int64
	IssuedAt        pgtype.Timestamptz
	LastSeenAt      pgtype.Timestamptz
	ValidatedAt     pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
}

func (q *Queries) ListSessionsForAdministration(ctx context.Context, arg ListSessionsForAdministrationParams) ([]ListSessionsForAdministrationRow, error) {
	rows, err := q.db.Query(ctx, listSessionsForAdministration,
		arg.ActorUserID,
		arg.ObservedAt,
		arg.TargetUserID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsForAdministrationRow{}
	for rows.Next() {
		var i ListSessionsForAdministrationRow
		if err := rows.Scan(
			&i.ActorPresent,
			&i.TargetPresent,
			&i.SettingsPresent,
			&i.TargetUserID,
			&i.DisplayName,
			&i.TargetRevision,
			&i.SessionPresent,
			&i.SessionID,
			&i.IssuedAt,
			&i.LastSeenAt,
			&i.ValidatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadEmailTestStateForAdministration = `-- name: LoadEmailTestStateForAdministration :one
WITH actor AS MATERIALIZED (
    SELECT forum_user.id
    FROM public.users AS forum_user
    WHERE forum_user.id = $1
      AND forum_user.role = 'administrator'
      AND forum_user.authentik_sync_state = 'accepted'
      AND (
          forum_user.suspended_at IS NULL
          OR forum_user.suspended_at > $2::timestamptz
          OR forum_user.suspended_until <= $2::timestamptz
      )
      AND (forum_user.muted_until IS NULL OR forum_user.muted_until <= $2::timestamptz)
)
SELECT (actor.id IS NOT NULL)::boolean AS actor_present,
       (state.administrator_id IS NOT NULL)::boolean AS state_present,
       COALESCE(state.status, '')::text AS status,
       state.requested_at, state.completed_at, state.next_allowed_at
FROM (VALUES (true)) AS anchor(singleton)
LEFT JOIN actor ON true
LEFT JOIN public.email_test_state AS state
  ON state.administrator_id = actor.id
`

type LoadEmailTestStateForAdministrationParams struct {
	ActorUserID int64
	ObservedAt  pgtype.Timestamptz
}

type LoadEmailTestStateForAdministrationRow struct {
	ActorPresent  bool
	StatePresent  bool
	Status        string
	RequestedAt   pgtype.Timestamptz
	CompletedAt   pgtype.Timestamptz
	NextAllowedAt pgtype.Timestamptz
}

func (q *Queries) LoadEmailTestStateForAdministration(ctx context.Context, arg LoadEmailTestStateForAdministrationParams) (LoadEmailTestStateForAdministrationRow, error) {
	row := q.db.QueryRow(ctx, loadEmailTestStateForAdministration, arg.ActorUserID, arg.ObservedAt)
	var i LoadEmailTestStateForAdministrationRow
	err := row.Scan(
		&i.ActorPresent,
		&i.StatePresent,
		&i.Status,
		&i.RequestedAt,
		&i.CompletedAt,
		&i.NextAllowedAt,
	)
	return i, err
}

const lockEmailTestAdministrator = `-- name: LockEmailTestAdministrator :one
SELECT forum_user.id, forum_user.email
FROM public.users AS forum_user
WHERE forum_user.id = $1
  AND forum_user.role = 'administrator'
  AND forum_user.authentik_sync_state = 'accepted'
  AND (
      forum_user.suspended_at IS NULL
      OR forum_user.suspended_at > $2::timestamptz
      OR forum_user.suspended_until <= $2::timestamptz
  )
  AND (forum_user.muted_until IS NULL OR forum_user.muted_until <= $2::timestamptz)
FOR UPDATE OF forum_user
`

type LockEmailTestAdministratorParams struct {
	ActorUserID int64
	ObservedAt  pgtype.Timestamptz
}

type LockEmailTestAdministratorRow struct {
	ID    int64
	Email pgtype.Text
}

func (q *Queries) LockEmailTestAdministrator(ctx context.Context, arg LockEmailTestAdministratorParams) (LockEmailTestAdministratorRow, error) {
	row := q.db.QueryRow(ctx, lockEmailTestAdministrator, arg.ActorUserID, arg.ObservedAt)
	var i LockEmailTestAdministratorRow
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}

const reserveEmailTestAndAudit = `-- name: ReserveEmailTestAndAudit :one
WITH reserved AS (
    INSERT INTO public.email_test_state (
        administrator_id, idempotency_key, status,
        requested_at, completed_at, next_allowed_at
    )
    VALUES (
        $1, $2, 'requested',
        $3::timestamptz, NULL,
        $3::timestamptz + interval '5 minutes'
    )
    ON CONFLICT (administrator_id) DO UPDATE
    SET idempotency_key = EXCLUDED.idempotency_key,
        status = EXCLUDED.status,
        requested_at = EXCLUDED.requested_at,
        completed_at = EXCLUDED.completed_at,
        next_allowed_at = EXCLUDED.next_allowed_at
    WHERE email_test_state.next_allowed_at <= EXCLUDED.requested_at
    RETURNING administrator_id, requested_at, next_allowed_at
), audit AS (
    INSERT INTO public.moderation_actions (
        actor_kind, actor_user_id, target_type, target_user_id,
        action_type, reason, previous_state, resulting_state,
        request_id, created_at
    )
    SELECT 'forum_user', reserved.administrator_id, 'user',
           reserved.administrator_id, 'request_test_email', $4,
           '{}'::jsonb,
           jsonb_build_object(
               'status', 'requested',
               'idempotency_sha256', $5::text
           ),
           $6, reserved.requested_at
    FROM reserved
    RETURNING id
)
SELECT reserved.requested_at, reserved.next_allowed_at, audit.id AS audit_id
FROM reserved
JOIN audit ON true
`

type ReserveEmailTestAndAuditParams struct {
	ActorUserID       int64
	IdempotencyKey    pgtype.UUID
	ObservedAt        pgtype.Timestamptz
	Reason            pgtype.Text
	IdempotencySha256 string
	RequestID         pgtype.UUID
}

type ReserveEmailTestAndAuditRow struct {
	RequestedAt   pgtype.Timestamptz
	NextAllowedAt pgtype.Timestamptz
	AuditID       int64
}

func (q *Queries) ReserveEmailTestAndAudit(ctx context.Context, arg ReserveEmailTestAndAuditParams) (ReserveEmailTestAndAuditRow, error) {
	row := q.db.QueryRow(ctx, reserveEmailTestAndAudit,
		arg.ActorUserID,
		arg.IdempotencyKey,
		arg.ObservedAt,
		arg.Reason,
		arg.IdempotencySha256,
		arg.RequestID,
	)
	var i ReserveEmailTestAndAuditRow
	err := row.Scan(&i.RequestedAt, &i.NextAllowedAt, &i.AuditID)
	return i, err
}

const revokeAllSessionsForAdministrationAndAudit = `-- name: RevokeAllSessionsForAdministrationAndAudit :one
WITH revoked AS (
    UPDATE public.sessions AS local_session
    SET revoked_at = GREATEST(local_session.issued_at, $1::timestamptz)
    WHERE local_session.user_id = $2
      AND local_session.revoked_at IS NULL
      AND local_session.issued_at <= $1::timestamptz
      AND local_session.expires_at > $1::timestamptz
    RETURNING local_session.id
), changed AS (
    SELECT count(*)::bigint AS revoked_count
    FROM revoked
), audit AS (
    INSERT INTO public.moderation_actions (
        actor_kind, actor_user_id, target_type, target_user_id,
        action_type, reason, previous_state, resulting_state,
        request_id, created_at
    )
    SELECT 'forum_user', $3, 'user',
           $2, 'revoke_user_sessions', $4,
           jsonb_build_object('active_sessions_revoked', 0),
           jsonb_build_object('active_sessions_revoked', changed.revoked_count),
           $5, $1::timestamptz
    FROM changed
    WHERE changed.revoked_count > 0
    RETURNING id
)
SELECT changed.revoked_count, audit.id AS audit_id
FROM changed
JOIN audit ON true
`

type RevokeAllSessionsForAdministrationAndAuditParams struct {
	ObservedAt   pgtype.Timestamptz
	TargetUserID int64
	ActorUserID  pgtype.Int8
	Reason       pgtype.Text
	RequestID    pgtype.UUID
}

type RevokeAllSessionsForAdministrationAndAuditRow struct {
	RevokedCount int64
	AuditID      int64
}

func (q *Queries) RevokeAllSessionsForAdministrationAndAudit(ctx context.Context, arg RevokeAllSessionsForAdministrationAndAuditParams) (RevokeAllSessionsForAdministrationAndAuditRow, error) {
	row := q.db.QueryRow(ctx, revokeAllSessionsForAdministrationAndAudit,
		arg.ObservedAt,
		arg.TargetUserID,
		arg.ActorUserID,
		arg.Reason,
		arg.RequestID,
	)
	var i RevokeAllSessionsForAdministrationAndAuditRow
	err := row.Scan(&i.RevokedCount, &i.AuditID)
	return i, err
}

const revokeOneSessionForAdministrationAndAudit = `-- name: RevokeOneSessionForAdministrationAndAudit :one
WITH revoked AS (
    UPDATE public.sessions AS local_session
    SET revoked_at = GREATEST(local_session.issued_at, $1::timestamptz)
    WHERE local_session.id = $2
      AND local_session.user_id = $3
      AND local_session.revoked_at IS NULL
      AND local_session.issued_at <= $1::timestamptz
      AND local_session.expires_at > $1::timestamptz
    RETURNING local_session.id
), changed AS (
    SELECT count(*)::bigint AS revoked_count
    FROM revoked
), audit AS (
    INSERT INTO public.moderation_actions (
        actor_kind, actor_user_id, target_type, target_user_id,
        action_type, reason, previous_state, resulting_state,
        request_id, created_at
    )
    SELECT 'forum_user', $4, 'user',
           $3, 'revoke_session', $5,
           jsonb_build_object('active_sessions_revoked', 0),
           jsonb_build_object('active_sessions_revoked', changed.revoked_count),
           $6, $1::timestamptz
    FROM changed
    WHERE changed.revoked_count = 1
    RETURNING id
)
SELECT changed.revoked_count, audit.id AS audit_id
FROM changed
JOIN audit ON true
`

type RevokeOneSessionForAdministrationAndAuditParams struct {
	ObservedAt   pgtype.Timestamptz
	SessionID    int64
	TargetUserID int64
	ActorUserID  pgtype.Int8
	Reason       pgtype.Text
	RequestID    pgtype.UUID
}

type RevokeOneSessionForAdministrationAndAuditRow struct {
	RevokedCount int64
	AuditID      int64
}

func (q *Queries) RevokeOneSessionForAdministrationAndAudit(ctx context.Context, arg RevokeOneSessionForAdministrationAndAuditParams) (RevokeOneSessionForAdministrationAndAuditRow, error) {
	row := q.db.QueryRow(ctx, revokeOneSessionForAdministrationAndAudit,
		arg.ObservedAt,
		arg.SessionID,
		arg.TargetUserID,
		arg.ActorUserID,
		arg.Reason,
		arg.RequestID,
	)
	var i RevokeOneSessionForAdministrationAndAuditRow
	err := row.Scan(&i.RevokedCount, &i.AuditID)
	return i, err
}
