// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: areas.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAreaGroupForAdministration = `-- name: AddAreaGroupForAdministration :exec
INSERT INTO public.area_groups (area_id, group_id, added_by, created_at)
VALUES ($1, $2, $3, $4)
`

type AddAreaGroupForAdministrationParams struct {
	AreaID      int64
	GroupID     int64
	ActorUserID int64
	AtTime      pgtype.Timestamptz
}

func (q *Queries) AddAreaGroupForAdministration(ctx context.Context, arg AddAreaGroupForAdministrationParams) error {
	_, err := q.db.Exec(ctx, addAreaGroupForAdministration,
		arg.AreaID,
		arg.GroupID,
		arg.ActorUserID,
		arg.AtTime,
	)
	return err
}

const countExistingForumGroups = `-- name: CountExistingForumGroups :one
SELECT count(*)
FROM public.forum_groups
WHERE id = ANY($1::bigint[])
`

func (q *Queries) CountExistingForumGroups(ctx context.Context, groupIds []int64) (int64, error) {
	row := q.db.QueryRow(ctx, countExistingForumGroups, groupIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAreaAdministrationAudit = `-- name: CreateAreaAdministrationAudit :one
INSERT INTO public.moderation_actions (
    actor_kind,
    actor_user_id,
    target_type,
    target_area_id,
    action_type,
    reason,
    previous_state,
    resulting_state,
    request_id,
    created_at
)
VALUES (
    'forum_user',
    $1,
    'area',
    $2,
    $3,
    $4,
    $5::jsonb,
    $6::jsonb,
    $7,
    $8
)
RETURNING id
`

type CreateAreaAdministrationAuditParams struct {
	ActorUserID    pgtype.Int8
	AreaID         pgtype.Int8
	ActionType     string
	Reason         pgtype.Text
	PreviousState  []byte
	ResultingState []byte
	RequestID      pgtype.UUID
	AtTime         pgtype.Timestamptz
}

func (q *Queries) CreateAreaAdministrationAudit(ctx context.Context, arg CreateAreaAdministrationAuditParams) (int64, error) {
	row := q.db.QueryRow(ctx, createAreaAdministrationAudit,
		arg.ActorUserID,
		arg.AreaID,
		arg.ActionType,
		arg.Reason,
		arg.PreviousState,
		arg.ResultingState,
		arg.RequestID,
		arg.AtTime,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createAreaForAdministration = `-- name: CreateAreaForAdministration :one
INSERT INTO public.areas (
    slug, name, description, display_order, visibility, posting_mode,
    created_by, updated_by, created_at, updated_at
)
VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $7,
    $8, $8
)
RETURNING id, slug, name, description, display_order, visibility, posting_mode, created_by, updated_by, created_at, updated_at
`

type CreateAreaForAdministrationParams struct {
	Slug         string
	Name         string
	Description  string
	DisplayOrder int32
	Visibility   string
	PostingMode  string
	ActorUserID  int64
	AtTime       pgtype.Timestamptz
}

func (q *Queries) CreateAreaForAdministration(ctx context.Context, arg CreateAreaForAdministrationParams) (Area, error) {
	row := q.db.QueryRow(ctx, createAreaForAdministration,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.DisplayOrder,
		arg.Visibility,
		arg.PostingMode,
		arg.ActorUserID,
		arg.AtTime,
	)
	var i Area
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.DisplayOrder,
		&i.Visibility,
		&i.PostingMode,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAreaGroupsForAdministration = `-- name: DeleteAreaGroupsForAdministration :exec
DELETE FROM public.area_groups
WHERE area_id = $1
`

func (q *Queries) DeleteAreaGroupsForAdministration(ctx context.Context, areaID int64) error {
	_, err := q.db.Exec(ctx, deleteAreaGroupsForAdministration, areaID)
	return err
}

const getVisibleAreaBySlug = `-- name: GetVisibleAreaBySlug :one
SELECT
    a.id,
    a.slug,
    a.name,
    a.description,
    a.display_order,
    a.visibility,
    a.posting_mode,
    a.created_by,
    a.updated_by,
    a.created_at,
    a.updated_at
FROM public.areas AS a
WHERE a.slug = $1
  AND (
    $2::boolean
    OR a.visibility = 'public'
    OR (
        $3::boolean
        AND a.visibility = 'authenticated'
    )
    OR (
        $3::boolean
        AND a.visibility = 'groups'
        AND COALESCE(cardinality($4::bigint[]), 0) > 0
        AND EXISTS (
            SELECT 1
            FROM public.area_groups AS ag
            WHERE ag.area_id = a.id
              AND ag.group_id = ANY($4::bigint[])
        )
    )
  )
`

type GetVisibleAreaBySlugParams struct {
	Slug     string
	IsStaff  bool
	IsMember bool
	GroupIds []int64
}

func (q *Queries) GetVisibleAreaBySlug(ctx context.Context, arg GetVisibleAreaBySlugParams) (Area, error) {
	row := q.db.QueryRow(ctx, getVisibleAreaBySlug,
		arg.Slug,
		arg.IsStaff,
		arg.IsMember,
		arg.GroupIds,
	)
	var i Area
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.DisplayOrder,
		&i.Visibility,
		&i.PostingMode,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAreasForAdministration = `-- name: ListAreasForAdministration :many
SELECT
    a.id,
    a.slug,
    a.name,
    a.description,
    a.display_order,
    a.visibility,
    a.posting_mode,
    a.created_by,
    a.updated_by,
    a.created_at,
    a.updated_at,
    COALESCE(
        ARRAY(
            SELECT ag.group_id
            FROM public.area_groups AS ag
            WHERE ag.area_id = a.id
            ORDER BY ag.group_id
        ),
        ARRAY[]::bigint[]
    )::bigint[] AS group_ids
FROM public.areas AS a
ORDER BY a.display_order, a.id
`

type ListAreasForAdministrationRow struct {
	ID           int64
	Slug         string
	Name         string
	Description  string
	DisplayOrder int32
	Visibility   string
	PostingMode  string
	CreatedBy    int64
	UpdatedBy    int64
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	GroupIds     []int64
}

func (q *Queries) ListAreasForAdministration(ctx context.Context) ([]ListAreasForAdministrationRow, error) {
	rows, err := q.db.Query(ctx, listAreasForAdministration)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAreasForAdministrationRow{}
	for rows.Next() {
		var i ListAreasForAdministrationRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.DisplayOrder,
			&i.Visibility,
			&i.PostingMode,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForumGroupsForAreaAdministration = `-- name: ListForumGroupsForAreaAdministration :many
SELECT id, name
FROM public.forum_groups
ORDER BY lower(name), id
`

type ListForumGroupsForAreaAdministrationRow struct {
	ID   int64
	Name string
}

func (q *Queries) ListForumGroupsForAreaAdministration(ctx context.Context) ([]ListForumGroupsForAreaAdministrationRow, error) {
	rows, err := q.db.Query(ctx, listForumGroupsForAreaAdministration)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListForumGroupsForAreaAdministrationRow{}
	for rows.Next() {
		var i ListForumGroupsForAreaAdministrationRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleAreaSummaries = `-- name: ListVisibleAreaSummaries :many
WITH visible_areas AS (
    SELECT
        a.id,
        a.slug,
        a.name,
        a.description,
        a.display_order,
        a.visibility,
        a.posting_mode,
        a.created_by,
        a.updated_by,
        a.created_at,
        a.updated_at
    FROM public.areas AS a
    WHERE
        $1::boolean
        OR a.visibility = 'public'
        OR (
            $2::boolean
            AND a.visibility = 'authenticated'
        )
        OR (
            $2::boolean
            AND a.visibility = 'groups'
            AND COALESCE(cardinality($3::bigint[]), 0) > 0
            AND EXISTS (
                SELECT 1
                FROM public.area_groups AS ag
                WHERE ag.area_id = a.id
                  AND ag.group_id = ANY($3::bigint[])
            )
        )
),
visible_topics AS (
    SELECT topic.id, topic.area_id, topic.title
    FROM public.topics AS topic
    JOIN visible_areas AS area ON area.id = topic.area_id
    WHERE topic.deleted_at IS NULL
      AND ($1::boolean OR topic.state <> 'hidden')
),
topic_counts AS (
    SELECT topic.area_id, count(*)::bigint AS topic_count
    FROM visible_topics AS topic
    GROUP BY topic.area_id
),
visible_posts AS (
    SELECT post.id, post.topic_id, post.post_number, post.author_id, post.created_at
    FROM public.posts AS post
    JOIN visible_topics AS topic ON topic.id = post.topic_id
    WHERE post.deleted_at IS NULL
),
post_counts AS (
    SELECT topic.area_id, count(*)::bigint AS post_count
    FROM visible_posts AS post
    JOIN visible_topics AS topic ON topic.id = post.topic_id
    GROUP BY topic.area_id
),
latest_posts AS (
    SELECT DISTINCT ON (topic.area_id)
        topic.area_id,
        topic.id AS latest_topic_id,
        topic.title AS latest_topic_title,
        post.id AS latest_post_id,
        post.post_number AS latest_post_number,
        author.display_name AS latest_post_author,
        post.created_at AS latest_post_created_at
    FROM visible_posts AS post
    JOIN visible_topics AS topic ON topic.id = post.topic_id
    JOIN public.users AS author ON author.id = post.author_id
    ORDER BY topic.area_id, post.created_at DESC, post.id DESC
)
SELECT
    area.id,
    area.slug,
    area.name,
    area.description,
    area.display_order,
    area.visibility,
    area.posting_mode,
    area.created_by,
    area.updated_by,
    area.created_at,
    area.updated_at,
    COALESCE(topic_counts.topic_count, 0)::bigint AS topic_count,
    COALESCE(post_counts.post_count, 0)::bigint AS post_count,
    latest_posts.latest_topic_id,
    latest_posts.latest_topic_title,
    latest_posts.latest_post_id,
    latest_posts.latest_post_number,
    latest_posts.latest_post_author,
    latest_posts.latest_post_created_at
FROM visible_areas AS area
LEFT JOIN topic_counts ON topic_counts.area_id = area.id
LEFT JOIN post_counts ON post_counts.area_id = area.id
LEFT JOIN latest_posts ON latest_posts.area_id = area.id
ORDER BY area.display_order, area.id
`

type ListVisibleAreaSummariesParams struct {
	IsStaff  bool
	IsMember bool
	GroupIds []int64
}

type ListVisibleAreaSummariesRow struct {
	ID                  int64
	Slug                string
	Name                string
	Description         string
	DisplayOrder        int32
	Visibility          string
	PostingMode         string
	CreatedBy           int64
	UpdatedBy           int64
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	TopicCount          int64
	PostCount           int64
	LatestTopicID       pgtype.Int8
	LatestTopicTitle    pgtype.Text
	LatestPostID        pgtype.Int8
	LatestPostNumber    pgtype.Int4
	LatestPostAuthor    pgtype.Text
	LatestPostCreatedAt pgtype.Timestamptz
}

func (q *Queries) ListVisibleAreaSummaries(ctx context.Context, arg ListVisibleAreaSummariesParams) ([]ListVisibleAreaSummariesRow, error) {
	rows, err := q.db.Query(ctx, listVisibleAreaSummaries, arg.IsStaff, arg.IsMember, arg.GroupIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVisibleAreaSummariesRow{}
	for rows.Next() {
		var i ListVisibleAreaSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.DisplayOrder,
			&i.Visibility,
			&i.PostingMode,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TopicCount,
			&i.PostCount,
			&i.LatestTopicID,
			&i.LatestTopicTitle,
			&i.LatestPostID,
			&i.LatestPostNumber,
			&i.LatestPostAuthor,
			&i.LatestPostCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleAreas = `-- name: ListVisibleAreas :many
SELECT
    a.id,
    a.slug,
    a.name,
    a.description,
    a.display_order,
    a.visibility,
    a.posting_mode,
    a.created_by,
    a.updated_by,
    a.created_at,
    a.updated_at
FROM public.areas AS a
WHERE
    $1::boolean
    OR a.visibility = 'public'
    OR (
        $2::boolean
        AND a.visibility = 'authenticated'
    )
    OR (
        $2::boolean
        AND a.visibility = 'groups'
        AND COALESCE(cardinality($3::bigint[]), 0) > 0
        AND EXISTS (
            SELECT 1
            FROM public.area_groups AS ag
            WHERE ag.area_id = a.id
              AND ag.group_id = ANY($3::bigint[])
        )
    )
ORDER BY a.display_order, a.id
`

type ListVisibleAreasParams struct {
	IsStaff  bool
	IsMember bool
	GroupIds []int64
}

func (q *Queries) ListVisibleAreas(ctx context.Context, arg ListVisibleAreasParams) ([]Area, error) {
	rows, err := q.db.Query(ctx, listVisibleAreas, arg.IsStaff, arg.IsMember, arg.GroupIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Area{}
	for rows.Next() {
		var i Area
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.DisplayOrder,
			&i.Visibility,
			&i.PostingMode,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAreaForAdministration = `-- name: LockAreaForAdministration :one
SELECT
    a.id,
    a.slug,
    a.name,
    a.description,
    a.display_order,
    a.visibility,
    a.posting_mode,
    a.created_by,
    a.updated_by,
    a.created_at,
    a.updated_at,
    COALESCE(
        ARRAY(
            SELECT ag.group_id
            FROM public.area_groups AS ag
            WHERE ag.area_id = a.id
            ORDER BY ag.group_id
        ),
        ARRAY[]::bigint[]
    )::bigint[] AS group_ids
FROM public.areas AS a
WHERE a.id = $1
FOR UPDATE OF a
`

type LockAreaForAdministrationRow struct {
	ID           int64
	Slug         string
	Name         string
	Description  string
	DisplayOrder int32
	Visibility   string
	PostingMode  string
	CreatedBy    int64
	UpdatedBy    int64
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	GroupIds     []int64
}

func (q *Queries) LockAreaForAdministration(ctx context.Context, areaID int64) (LockAreaForAdministrationRow, error) {
	row := q.db.QueryRow(ctx, lockAreaForAdministration, areaID)
	var i LockAreaForAdministrationRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.DisplayOrder,
		&i.Visibility,
		&i.PostingMode,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupIds,
	)
	return i, err
}

const updateAreaForAdministration = `-- name: UpdateAreaForAdministration :one
UPDATE public.areas
SET name = $1,
    description = $2,
    display_order = $3,
    visibility = $4,
    posting_mode = $5,
    updated_by = $6,
    updated_at = GREATEST($7::timestamptz, updated_at)
WHERE id = $8
RETURNING id, slug, name, description, display_order, visibility, posting_mode, created_by, updated_by, created_at, updated_at
`

type UpdateAreaForAdministrationParams struct {
	Name         string
	Description  string
	DisplayOrder int32
	Visibility   string
	PostingMode  string
	ActorUserID  int64
	AtTime       pgtype.Timestamptz
	AreaID       int64
}

func (q *Queries) UpdateAreaForAdministration(ctx context.Context, arg UpdateAreaForAdministrationParams) (Area, error) {
	row := q.db.QueryRow(ctx, updateAreaForAdministration,
		arg.Name,
		arg.Description,
		arg.DisplayOrder,
		arg.Visibility,
		arg.PostingMode,
		arg.ActorUserID,
		arg.AtTime,
		arg.AreaID,
	)
	var i Area
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.DisplayOrder,
		&i.Visibility,
		&i.PostingMode,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
