// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeOIDCLoginAttempt = `-- name: ConsumeOIDCLoginAttempt :one
UPDATE public.oidc_login_attempts
SET consumed_at = $1
WHERE state_hash = $2
  AND consumed_at IS NULL
  AND created_at <= $1
  AND expires_at > $1
RETURNING state_hash, nonce_ciphertext, pkce_verifier_ciphertext, purpose, session_id, return_path, created_at, expires_at, consumed_at
`

type ConsumeOIDCLoginAttemptParams struct {
	ConsumedAt pgtype.Timestamptz
	StateHash  []byte
}

func (q *Queries) ConsumeOIDCLoginAttempt(ctx context.Context, arg ConsumeOIDCLoginAttemptParams) (OidcLoginAttempt, error) {
	row := q.db.QueryRow(ctx, consumeOIDCLoginAttempt, arg.ConsumedAt, arg.StateHash)
	var i OidcLoginAttempt
	err := row.Scan(
		&i.StateHash,
		&i.NonceCiphertext,
		&i.PkceVerifierCiphertext,
		&i.Purpose,
		&i.SessionID,
		&i.ReturnPath,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT
    session.id AS session_id,
    session.user_id,
    session.issued_at,
    session.last_seen_at,
    session.validated_at,
    session.expires_at,
    forum_user.display_name,
    forum_user.email,
    forum_user.avatar_url,
    forum_user.role,
    forum_user.muted_until
FROM public.sessions AS session
JOIN public.users AS forum_user ON forum_user.id = session.user_id
WHERE session.token_hash = $1
  AND session.revoked_at IS NULL
  AND session.expires_at > $2
  AND session.last_seen_at > $3
  AND (
      forum_user.suspended_at IS NULL
      OR forum_user.suspended_at > $2
      OR forum_user.suspended_until <= $2
  )
`

type GetActiveSessionParams struct {
	TokenHash  []byte
	ObservedAt pgtype.Timestamptz
	IdleCutoff pgtype.Timestamptz
}

type GetActiveSessionRow struct {
	SessionID   int64
	UserID      int64
	IssuedAt    pgtype.Timestamptz
	LastSeenAt  pgtype.Timestamptz
	ValidatedAt pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	DisplayName string
	Email       pgtype.Text
	AvatarUrl   pgtype.Text
	Role        string
	MutedUntil  pgtype.Timestamptz
}

func (q *Queries) GetActiveSession(ctx context.Context, arg GetActiveSessionParams) (GetActiveSessionRow, error) {
	row := q.db.QueryRow(ctx, getActiveSession, arg.TokenHash, arg.ObservedAt, arg.IdleCutoff)
	var i GetActiveSessionRow
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.IssuedAt,
		&i.LastSeenAt,
		&i.ValidatedAt,
		&i.ExpiresAt,
		&i.DisplayName,
		&i.Email,
		&i.AvatarUrl,
		&i.Role,
		&i.MutedUntil,
	)
	return i, err
}

const insertOIDCLoginAttempt = `-- name: InsertOIDCLoginAttempt :exec
INSERT INTO public.oidc_login_attempts (
    state_hash,
    nonce_ciphertext,
    pkce_verifier_ciphertext,
    purpose,
    session_id,
    return_path,
    created_at,
    expires_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
`

type InsertOIDCLoginAttemptParams struct {
	StateHash              []byte
	NonceCiphertext        []byte
	PkceVerifierCiphertext []byte
	Purpose                string
	SessionID              pgtype.Int8
	ReturnPath             string
	CreatedAt              pgtype.Timestamptz
	ExpiresAt              pgtype.Timestamptz
}

func (q *Queries) InsertOIDCLoginAttempt(ctx context.Context, arg InsertOIDCLoginAttemptParams) error {
	_, err := q.db.Exec(ctx, insertOIDCLoginAttempt,
		arg.StateHash,
		arg.NonceCiphertext,
		arg.PkceVerifierCiphertext,
		arg.Purpose,
		arg.SessionID,
		arg.ReturnPath,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}
