// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: control.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const loadEditableControlSettings = `-- name: LoadEditableControlSettings :one
WITH actor AS MATERIALIZED (
    SELECT forum_user.id
    FROM public.users AS forum_user
    WHERE forum_user.id = $1
      AND forum_user.role = 'administrator'
      AND forum_user.authentik_sync_state = 'accepted'
      AND (
          forum_user.suspended_at IS NULL
          OR forum_user.suspended_at > $2::timestamptz
          OR forum_user.suspended_until <= $2::timestamptz
      )
      AND (forum_user.muted_until IS NULL OR forum_user.muted_until <= $2::timestamptz)
)
SELECT (settings.singleton IS TRUE)::boolean AS settings_present,
       COALESCE(settings.registration_mode, '')::text AS registration_mode,
       COALESCE(settings.maintenance_enabled, false)::boolean AS maintenance_enabled,
       COALESCE(settings.maintenance_message, '')::text AS maintenance_message,
       COALESCE(settings.publish_rate_limit, 0)::integer AS publish_rate_limit,
       COALESCE(settings.new_account_publish_rate_limit, 0)::integer AS new_account_publish_rate_limit,
       COALESCE(settings.publish_window_seconds, 0)::integer AS publish_window_seconds,
       COALESCE(settings.new_account_period_seconds, 0)::integer AS new_account_period_seconds,
       COALESCE(settings.session_idle_seconds, 0)::integer AS session_idle_seconds,
       COALESCE(settings.auth_revalidate_seconds, 0)::integer AS auth_revalidate_seconds,
       COALESCE(settings.administration_revision, 0)::bigint AS administration_revision
FROM actor
LEFT JOIN LATERAL (
    SELECT singleton, registration_mode, maintenance_enabled,
           maintenance_message, publish_rate_limit,
           new_account_publish_rate_limit, publish_window_seconds,
           new_account_period_seconds, session_idle_seconds,
           auth_revalidate_seconds, administration_revision
    FROM public.site_settings
    WHERE singleton
) AS settings ON true
`

type LoadEditableControlSettingsParams struct {
	ActorUserID int64
	ObservedAt  pgtype.Timestamptz
}

type LoadEditableControlSettingsRow struct {
	SettingsPresent            bool
	RegistrationMode           string
	MaintenanceEnabled         bool
	MaintenanceMessage         string
	PublishRateLimit           int32
	NewAccountPublishRateLimit int32
	PublishWindowSeconds       int32
	NewAccountPeriodSeconds    int32
	SessionIdleSeconds         int32
	AuthRevalidateSeconds      int32
	AdministrationRevision     int64
}

func (q *Queries) LoadEditableControlSettings(ctx context.Context, arg LoadEditableControlSettingsParams) (LoadEditableControlSettingsRow, error) {
	row := q.db.QueryRow(ctx, loadEditableControlSettings, arg.ActorUserID, arg.ObservedAt)
	var i LoadEditableControlSettingsRow
	err := row.Scan(
		&i.SettingsPresent,
		&i.RegistrationMode,
		&i.MaintenanceEnabled,
		&i.MaintenanceMessage,
		&i.PublishRateLimit,
		&i.NewAccountPublishRateLimit,
		&i.PublishWindowSeconds,
		&i.NewAccountPeriodSeconds,
		&i.SessionIdleSeconds,
		&i.AuthRevalidateSeconds,
		&i.AdministrationRevision,
	)
	return i, err
}

const loadRuntimeControlSettings = `-- name: LoadRuntimeControlSettings :one
SELECT registration_mode,
       maintenance_enabled,
       maintenance_message,
       publish_rate_limit,
       new_account_publish_rate_limit,
       publish_window_seconds,
       new_account_period_seconds,
       session_idle_seconds,
       auth_revalidate_seconds,
       administration_revision
FROM public.site_settings
WHERE singleton
  AND (SELECT count(*) FROM public.site_settings) = 1
`

type LoadRuntimeControlSettingsRow struct {
	RegistrationMode           string
	MaintenanceEnabled         bool
	MaintenanceMessage         string
	PublishRateLimit           int32
	NewAccountPublishRateLimit int32
	PublishWindowSeconds       int32
	NewAccountPeriodSeconds    int32
	SessionIdleSeconds         int32
	AuthRevalidateSeconds      int32
	AdministrationRevision     int64
}

func (q *Queries) LoadRuntimeControlSettings(ctx context.Context) (LoadRuntimeControlSettingsRow, error) {
	row := q.db.QueryRow(ctx, loadRuntimeControlSettings)
	var i LoadRuntimeControlSettingsRow
	err := row.Scan(
		&i.RegistrationMode,
		&i.MaintenanceEnabled,
		&i.MaintenanceMessage,
		&i.PublishRateLimit,
		&i.NewAccountPublishRateLimit,
		&i.PublishWindowSeconds,
		&i.NewAccountPeriodSeconds,
		&i.SessionIdleSeconds,
		&i.AuthRevalidateSeconds,
		&i.AdministrationRevision,
	)
	return i, err
}

const lockControlSettingsAdministrator = `-- name: LockControlSettingsAdministrator :one
SELECT forum_user.id
FROM public.users AS forum_user
WHERE forum_user.id = $1
  AND forum_user.role = 'administrator'
  AND forum_user.authentik_sync_state = 'accepted'
  AND (
      forum_user.suspended_at IS NULL
      OR forum_user.suspended_at > $2::timestamptz
      OR forum_user.suspended_until <= $2::timestamptz
  )
  AND (forum_user.muted_until IS NULL OR forum_user.muted_until <= $2::timestamptz)
FOR UPDATE OF forum_user
`

type LockControlSettingsAdministratorParams struct {
	ActorUserID int64
	ObservedAt  pgtype.Timestamptz
}

func (q *Queries) LockControlSettingsAdministrator(ctx context.Context, arg LockControlSettingsAdministratorParams) (int64, error) {
	row := q.db.QueryRow(ctx, lockControlSettingsAdministrator, arg.ActorUserID, arg.ObservedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const lockRuntimeControlSettings = `-- name: LockRuntimeControlSettings :one
SELECT registration_mode, maintenance_enabled, maintenance_message,
       publish_rate_limit, new_account_publish_rate_limit,
       publish_window_seconds, new_account_period_seconds,
       session_idle_seconds, auth_revalidate_seconds,
       administration_revision
FROM public.site_settings
WHERE singleton
FOR UPDATE
`

type LockRuntimeControlSettingsRow struct {
	RegistrationMode           string
	MaintenanceEnabled         bool
	MaintenanceMessage         string
	PublishRateLimit           int32
	NewAccountPublishRateLimit int32
	PublishWindowSeconds       int32
	NewAccountPeriodSeconds    int32
	SessionIdleSeconds         int32
	AuthRevalidateSeconds      int32
	AdministrationRevision     int64
}

func (q *Queries) LockRuntimeControlSettings(ctx context.Context) (LockRuntimeControlSettingsRow, error) {
	row := q.db.QueryRow(ctx, lockRuntimeControlSettings)
	var i LockRuntimeControlSettingsRow
	err := row.Scan(
		&i.RegistrationMode,
		&i.MaintenanceEnabled,
		&i.MaintenanceMessage,
		&i.PublishRateLimit,
		&i.NewAccountPublishRateLimit,
		&i.PublishWindowSeconds,
		&i.NewAccountPeriodSeconds,
		&i.SessionIdleSeconds,
		&i.AuthRevalidateSeconds,
		&i.AdministrationRevision,
	)
	return i, err
}

const updateControlSettingsAndAudit = `-- name: UpdateControlSettingsAndAudit :one
WITH updated AS (
    UPDATE public.site_settings AS settings
    SET registration_mode = $1,
        maintenance_enabled = $2,
        maintenance_message = $3,
        publish_rate_limit = $4,
        new_account_publish_rate_limit = $5,
        publish_window_seconds = $6,
        new_account_period_seconds = $7,
        session_idle_seconds = $8,
        auth_revalidate_seconds = $9,
        administration_revision = settings.administration_revision + 1,
        updated_at = $10::timestamptz
    WHERE settings.singleton
      AND settings.administration_revision = $11
      AND settings.administration_revision < 9223372036854775807
    RETURNING settings.administration_revision
),
audit AS (
    INSERT INTO public.moderation_actions (
        actor_kind, actor_user_id, target_type, target_site, action_type,
        reason, previous_state, resulting_state, request_id, created_at
    )
    SELECT 'forum_user', $12, 'site', true,
           'update_control_settings', $13,
           jsonb_build_object(
               'registration_mode', $14::text,
               'maintenance_enabled', $15::boolean,
               'maintenance_message_sha256', $16::text,
               'publish_rate_limit', $17::integer,
               'new_account_publish_rate_limit', $18::integer,
               'publish_window_seconds', $19::integer,
               'new_account_period_seconds', $20::integer,
               'session_idle_seconds', $21::integer,
               'auth_revalidate_seconds', $22::integer
           ),
           jsonb_build_object(
               'registration_mode', $1::text,
               'maintenance_enabled', $2::boolean,
               'maintenance_message_sha256', $23::text,
               'publish_rate_limit', $4::integer,
               'new_account_publish_rate_limit', $5::integer,
               'publish_window_seconds', $6::integer,
               'new_account_period_seconds', $7::integer,
               'session_idle_seconds', $8::integer,
               'auth_revalidate_seconds', $9::integer
           ),
           $24, $10::timestamptz
    FROM updated
    RETURNING id
)
SELECT updated.administration_revision, audit.id AS audit_id
FROM updated
JOIN audit ON true
`

type UpdateControlSettingsAndAuditParams struct {
	RegistrationMode                   string
	MaintenanceEnabled                 bool
	MaintenanceMessage                 string
	PublishRateLimit                   int32
	NewAccountPublishRateLimit         int32
	PublishWindowSeconds               int32
	NewAccountPeriodSeconds            int32
	SessionIdleSeconds                 int32
	AuthRevalidateSeconds              int32
	ObservedAt                         pgtype.Timestamptz
	ExpectedRevision                   int64
	ActorUserID                        pgtype.Int8
	Reason                             pgtype.Text
	PreviousRegistrationMode           string
	PreviousMaintenanceEnabled         bool
	PreviousMaintenanceMessageSha256   string
	PreviousPublishRateLimit           int32
	PreviousNewAccountPublishRateLimit int32
	PreviousPublishWindowSeconds       int32
	PreviousNewAccountPeriodSeconds    int32
	PreviousSessionIdleSeconds         int32
	PreviousAuthRevalidateSeconds      int32
	MaintenanceMessageSha256           string
	RequestID                          pgtype.UUID
}

type UpdateControlSettingsAndAuditRow struct {
	AdministrationRevision int64
	AuditID                int64
}

func (q *Queries) UpdateControlSettingsAndAudit(ctx context.Context, arg UpdateControlSettingsAndAuditParams) (UpdateControlSettingsAndAuditRow, error) {
	row := q.db.QueryRow(ctx, updateControlSettingsAndAudit,
		arg.RegistrationMode,
		arg.MaintenanceEnabled,
		arg.MaintenanceMessage,
		arg.PublishRateLimit,
		arg.NewAccountPublishRateLimit,
		arg.PublishWindowSeconds,
		arg.NewAccountPeriodSeconds,
		arg.SessionIdleSeconds,
		arg.AuthRevalidateSeconds,
		arg.ObservedAt,
		arg.ExpectedRevision,
		arg.ActorUserID,
		arg.Reason,
		arg.PreviousRegistrationMode,
		arg.PreviousMaintenanceEnabled,
		arg.PreviousMaintenanceMessageSha256,
		arg.PreviousPublishRateLimit,
		arg.PreviousNewAccountPublishRateLimit,
		arg.PreviousPublishWindowSeconds,
		arg.PreviousNewAccountPeriodSeconds,
		arg.PreviousSessionIdleSeconds,
		arg.PreviousAuthRevalidateSeconds,
		arg.MaintenanceMessageSha256,
		arg.RequestID,
	)
	var i UpdateControlSettingsAndAuditRow
	err := row.Scan(&i.AdministrationRevision, &i.AuditID)
	return i, err
}
