// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discovery.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDirectPost = `-- name: GetDirectPost :one
SELECT
    post.id AS post_id,
    post.created_at,
    post.updated_at,
    post.edited_at,
    post.revision,
    post.rendered_html,
    post.renderer_version,
    post.author_id,
    author.display_name AS author_name,
    topic.id AS topic_id,
    topic.title AS topic_title,
    area.id AS area_id,
    area.slug AS area_slug,
    area.name AS area_name
FROM public.posts AS post
JOIN public.users AS author ON author.id = post.author_id
JOIN public.topics AS topic ON topic.id = post.topic_id
JOIN public.areas AS area ON area.id = topic.area_id
WHERE post.id = $1::bigint
  AND post.deleted_at IS NULL
  AND post.redacted_at IS NULL
  AND topic.deleted_at IS NULL
  AND ($2::boolean OR topic.state <> 'hidden')
  AND (
    $2::boolean
    OR area.visibility = 'public'
    OR ($3::boolean AND area.visibility = 'authenticated')
    OR (
        $3::boolean AND area.visibility = 'groups'
        AND COALESCE(cardinality($4::bigint[]), 0) > 0
        AND EXISTS (SELECT 1 FROM public.area_groups AS membership
            WHERE membership.area_id = area.id AND membership.group_id = ANY($4::bigint[]))
    )
  )
`

type GetDirectPostParams struct {
	PostID   int64
	IsStaff  bool
	IsMember bool
	GroupIds []int64
}

type GetDirectPostRow struct {
	PostID          int64
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	EditedAt        pgtype.Timestamptz
	Revision        int32
	RenderedHtml    string
	RendererVersion string
	AuthorID        int64
	AuthorName      string
	TopicID         int64
	TopicTitle      string
	AreaID          int64
	AreaSlug        string
	AreaName        string
}

func (q *Queries) GetDirectPost(ctx context.Context, arg GetDirectPostParams) (GetDirectPostRow, error) {
	row := q.db.QueryRow(ctx, getDirectPost,
		arg.PostID,
		arg.IsStaff,
		arg.IsMember,
		arg.GroupIds,
	)
	var i GetDirectPostRow
	err := row.Scan(
		&i.PostID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
		&i.Revision,
		&i.RenderedHtml,
		&i.RendererVersion,
		&i.AuthorID,
		&i.AuthorName,
		&i.TopicID,
		&i.TopicTitle,
		&i.AreaID,
		&i.AreaSlug,
		&i.AreaName,
	)
	return i, err
}

const getDiscoveryDatabaseTime = `-- name: GetDiscoveryDatabaseTime :one
SELECT clock_timestamp()::timestamptz
`

func (q *Queries) GetDiscoveryDatabaseTime(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getDiscoveryDatabaseTime)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const listRecentActivityAfter = `-- name: ListRecentActivityAfter :many
SELECT
    post.id AS post_id,
    post.created_at,
    post.author_id,
    author.display_name AS author_name,
    topic.id AS topic_id,
    topic.title AS topic_title,
    area.id AS area_id,
    area.slug AS area_slug,
    area.name AS area_name
FROM public.posts AS post
JOIN public.users AS author ON author.id = post.author_id
JOIN public.topics AS topic ON topic.id = post.topic_id
JOIN public.areas AS area ON area.id = topic.area_id
WHERE post.deleted_at IS NULL
  AND post.redacted_at IS NULL
  AND post.search_projection_version = 'search-v1-pg17-simple-u15-p2'
  AND topic.deleted_at IS NULL
  AND topic.search_projection_version = 'search-v1-pg17-simple-u15-p2'
  AND ($1::boolean OR topic.state <> 'hidden')
  AND (
    $1::boolean
    OR area.visibility = 'public'
    OR ($2::boolean AND area.visibility = 'authenticated')
    OR (
        $2::boolean AND area.visibility = 'groups'
        AND COALESCE(cardinality($3::bigint[]), 0) > 0
        AND EXISTS (SELECT 1 FROM public.area_groups AS membership
            WHERE membership.area_id = area.id AND membership.group_id = ANY($3::bigint[]))
    )
  )
  AND (post.created_at, post.id) < ($4::timestamptz, $5::bigint)
ORDER BY post.created_at DESC, post.id DESC
LIMIT 26
`

type ListRecentActivityAfterParams struct {
	IsStaff         bool
	IsMember        bool
	GroupIds        []int64
	CursorCreatedAt pgtype.Timestamptz
	CursorPostID    int64
}

type ListRecentActivityAfterRow struct {
	PostID     int64
	CreatedAt  pgtype.Timestamptz
	AuthorID   int64
	AuthorName string
	TopicID    int64
	TopicTitle string
	AreaID     int64
	AreaSlug   string
	AreaName   string
}

func (q *Queries) ListRecentActivityAfter(ctx context.Context, arg ListRecentActivityAfterParams) ([]ListRecentActivityAfterRow, error) {
	rows, err := q.db.Query(ctx, listRecentActivityAfter,
		arg.IsStaff,
		arg.IsMember,
		arg.GroupIds,
		arg.CursorCreatedAt,
		arg.CursorPostID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentActivityAfterRow{}
	for rows.Next() {
		var i ListRecentActivityAfterRow
		if err := rows.Scan(
			&i.PostID,
			&i.CreatedAt,
			&i.AuthorID,
			&i.AuthorName,
			&i.TopicID,
			&i.TopicTitle,
			&i.AreaID,
			&i.AreaSlug,
			&i.AreaName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentActivityInitial = `-- name: ListRecentActivityInitial :many
SELECT
    post.id AS post_id,
    post.created_at,
    post.author_id,
    author.display_name AS author_name,
    topic.id AS topic_id,
    topic.title AS topic_title,
    area.id AS area_id,
    area.slug AS area_slug,
    area.name AS area_name
FROM public.posts AS post
JOIN public.users AS author ON author.id = post.author_id
JOIN public.topics AS topic ON topic.id = post.topic_id
JOIN public.areas AS area ON area.id = topic.area_id
WHERE post.deleted_at IS NULL
  AND post.redacted_at IS NULL
  AND post.search_projection_version = 'search-v1-pg17-simple-u15-p2'
  AND topic.deleted_at IS NULL
  AND topic.search_projection_version = 'search-v1-pg17-simple-u15-p2'
  AND ($1::boolean OR topic.state <> 'hidden')
  AND (
    $1::boolean
    OR area.visibility = 'public'
    OR ($2::boolean AND area.visibility = 'authenticated')
    OR (
        $2::boolean AND area.visibility = 'groups'
        AND COALESCE(cardinality($3::bigint[]), 0) > 0
        AND EXISTS (SELECT 1 FROM public.area_groups AS membership
            WHERE membership.area_id = area.id AND membership.group_id = ANY($3::bigint[]))
    )
  )
ORDER BY post.created_at DESC, post.id DESC
LIMIT 26
`

type ListRecentActivityInitialParams struct {
	IsStaff  bool
	IsMember bool
	GroupIds []int64
}

type ListRecentActivityInitialRow struct {
	PostID     int64
	CreatedAt  pgtype.Timestamptz
	AuthorID   int64
	AuthorName string
	TopicID    int64
	TopicTitle string
	AreaID     int64
	AreaSlug   string
	AreaName   string
}

func (q *Queries) ListRecentActivityInitial(ctx context.Context, arg ListRecentActivityInitialParams) ([]ListRecentActivityInitialRow, error) {
	rows, err := q.db.Query(ctx, listRecentActivityInitial, arg.IsStaff, arg.IsMember, arg.GroupIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentActivityInitialRow{}
	for rows.Next() {
		var i ListRecentActivityInitialRow
		if err := rows.Scan(
			&i.PostID,
			&i.CreatedAt,
			&i.AuthorID,
			&i.AuthorName,
			&i.TopicID,
			&i.TopicTitle,
			&i.AreaID,
			&i.AreaSlug,
			&i.AreaName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const parseDiscoveryQuery = `-- name: ParseDiscoveryQuery :one
SELECT
    parsed.query::text AS parsed_query,
    numnode(parsed.query)::integer AS node_count,
    querytree(parsed.query)::text AS positive_query
FROM (
    SELECT websearch_to_tsquery('pg_catalog.simple'::regconfig, $1::text) AS query
) AS parsed
`

type ParseDiscoveryQueryRow struct {
	ParsedQuery   string
	NodeCount     int32
	PositiveQuery string
}

func (q *Queries) ParseDiscoveryQuery(ctx context.Context, queryText string) (ParseDiscoveryQueryRow, error) {
	row := q.db.QueryRow(ctx, parseDiscoveryQuery, queryText)
	var i ParseDiscoveryQueryRow
	err := row.Scan(&i.ParsedQuery, &i.NodeCount, &i.PositiveQuery)
	return i, err
}

const searchDiscoveryPage = `-- name: SearchDiscoveryPage :many
WITH candidate AS MATERIALIZED (
    SELECT identity.kind_order, identity.result_kind, identity.result_id, identity.created_at, identity.search_vector
    FROM (
        SELECT
            0::smallint AS kind_order,
            'topic'::text AS result_kind,
            topic.id AS result_id,
            topic.created_at,
            topic.search_vector
        FROM public.topics AS topic
        JOIN public.areas AS area ON area.id = topic.area_id
        WHERE topic.deleted_at IS NULL
          AND topic.search_projection_version = 'search-v1-pg17-simple-u15-p2'
          AND ($2::boolean OR topic.state <> 'hidden')
          AND (
            $2::boolean
            OR area.visibility = 'public'
            OR ($3::boolean AND area.visibility = 'authenticated')
            OR (
                $3::boolean
                AND area.visibility = 'groups'
                AND COALESCE(cardinality($4::bigint[]), 0) > 0
                AND EXISTS (
                    SELECT 1 FROM public.area_groups AS membership
                    WHERE membership.area_id = area.id
                      AND membership.group_id = ANY($4::bigint[])
                )
            )
          )
          AND ($7::bigint = 0 OR topic.author_id = $7::bigint)
          AND ($8::text = '' OR area.slug = $8::text)
          AND (NOT $9::boolean OR topic.created_at >= $10::timestamptz)
          AND (
            NOT $11::boolean
            OR ($12::boolean AND topic.created_at <= $13::timestamptz)
            OR (NOT $12::boolean AND topic.created_at < $13::timestamptz)
          )
          AND (NOT $5::boolean OR topic.search_vector @@ $6::text::tsquery)
        UNION ALL
        SELECT
            1::smallint AS kind_order,
            'post'::text AS result_kind,
            post.id AS result_id,
            post.created_at,
            post.search_vector
        FROM public.posts AS post
        JOIN public.topics AS topic ON topic.id = post.topic_id
        JOIN public.areas AS area ON area.id = topic.area_id
        WHERE post.deleted_at IS NULL
          AND post.redacted_at IS NULL
          AND post.search_projection_version = 'search-v1-pg17-simple-u15-p2'
          AND topic.deleted_at IS NULL
          AND topic.search_projection_version = 'search-v1-pg17-simple-u15-p2'
          AND ($2::boolean OR topic.state <> 'hidden')
          AND (
            $2::boolean
            OR area.visibility = 'public'
            OR ($3::boolean AND area.visibility = 'authenticated')
            OR (
                $3::boolean
                AND area.visibility = 'groups'
                AND COALESCE(cardinality($4::bigint[]), 0) > 0
                AND EXISTS (
                    SELECT 1 FROM public.area_groups AS membership
                    WHERE membership.area_id = area.id
                      AND membership.group_id = ANY($4::bigint[])
                )
            )
          )
          AND ($7::bigint = 0 OR post.author_id = $7::bigint)
          AND ($8::text = '' OR area.slug = $8::text)
          AND (NOT $9::boolean OR post.created_at >= $10::timestamptz)
          AND (
            NOT $11::boolean
            OR ($12::boolean AND post.created_at <= $13::timestamptz)
            OR (NOT $12::boolean AND post.created_at < $13::timestamptz)
          )
          AND (NOT $5::boolean OR post.search_vector @@ $6::text::tsquery)
          AND NOT (
            $5::boolean
            AND post.id = topic.first_post_id
            AND topic.search_vector @@ $6::text::tsquery
            AND ($7::bigint = 0 OR topic.author_id = $7::bigint)
          )
    ) AS identity
    ORDER BY identity.created_at DESC, identity.kind_order, identity.result_id DESC
    LIMIT 51
),
rankable AS (
    SELECT kind_order, result_kind, result_id, created_at, search_vector FROM candidate
    ORDER BY created_at DESC, kind_order, result_id DESC
    LIMIT 50
),
ordered AS (
    SELECT
        rankable.kind_order, rankable.result_kind, rankable.result_id, rankable.created_at, rankable.search_vector,
        CASE WHEN $5::boolean
            THEN ts_rank_cd(rankable.search_vector, $6::text::tsquery, 32)
            ELSE NULL::real
        END AS result_rank,
        row_number() OVER (
            ORDER BY
                CASE WHEN $5::boolean
                    THEN ts_rank_cd(rankable.search_vector, $6::text::tsquery, 32)
                    ELSE NULL::real
                END DESC NULLS LAST,
                rankable.created_at DESC,
                rankable.kind_order,
                rankable.result_id DESC
        )::integer AS result_ordinal
    FROM rankable
),
expected_page AS (
    SELECT kind_order, result_kind, result_id, created_at, search_vector, result_rank, result_ordinal FROM ordered
    WHERE result_ordinal > $1::integer
      AND result_ordinal <= $1::integer + 25
)
SELECT
    expected_page.result_kind AS expected_kind,
    expected_page.result_id AS expected_id,
    expected_page.result_ordinal,
    COALESCE(expected_page.result_rank, 0::real)::real AS result_rank,
    ($1::integer = 0 AND (SELECT count(*) FROM candidate) > 25)::boolean AS has_next_page,
    ((SELECT count(*) FROM candidate) > 50)::boolean AS beyond_window,
    selected.result_kind,
    selected.result_id,
    selected.area_id,
    selected.area_slug,
    selected.area_name,
    selected.topic_id,
    selected.topic_title,
    selected.post_id,
    selected.author_id,
    selected.author_name,
    selected.created_at,
    selected.rendered_html
FROM expected_page
LEFT JOIN LATERAL (
    SELECT
        'topic'::text AS result_kind,
        topic.id AS result_id,
        area.id AS area_id,
        area.slug AS area_slug,
        area.name AS area_name,
        topic.id AS topic_id,
        topic.title AS topic_title,
        NULL::bigint AS post_id,
        topic.author_id,
        author.display_name AS author_name,
        topic.created_at,
        NULL::text AS rendered_html
    FROM public.topics AS topic
    JOIN public.areas AS area ON area.id = topic.area_id
    JOIN public.users AS author ON author.id = topic.author_id
    WHERE expected_page.result_kind = 'topic'
      AND topic.id = expected_page.result_id
      AND topic.deleted_at IS NULL
      AND topic.search_projection_version = 'search-v1-pg17-simple-u15-p2'
      AND ($2::boolean OR topic.state <> 'hidden')
      AND (
        $2::boolean OR area.visibility = 'public'
        OR ($3::boolean AND area.visibility = 'authenticated')
        OR ($3::boolean AND area.visibility = 'groups'
            AND COALESCE(cardinality($4::bigint[]), 0) > 0
            AND EXISTS (SELECT 1 FROM public.area_groups AS membership
                WHERE membership.area_id = area.id AND membership.group_id = ANY($4::bigint[])))
      )
      AND (NOT $5::boolean OR topic.search_vector @@ $6::text::tsquery)
    UNION ALL
    SELECT
        'post'::text AS result_kind,
        post.id AS result_id,
        area.id AS area_id,
        area.slug AS area_slug,
        area.name AS area_name,
        topic.id AS topic_id,
        topic.title AS topic_title,
        post.id AS post_id,
        post.author_id,
        author.display_name AS author_name,
        post.created_at,
        post.rendered_html
    FROM public.posts AS post
    JOIN public.topics AS topic ON topic.id = post.topic_id
    JOIN public.areas AS area ON area.id = topic.area_id
    JOIN public.users AS author ON author.id = post.author_id
    WHERE expected_page.result_kind = 'post'
      AND post.id = expected_page.result_id
      AND post.deleted_at IS NULL AND post.redacted_at IS NULL
      AND post.search_projection_version = 'search-v1-pg17-simple-u15-p2'
      AND topic.deleted_at IS NULL
      AND topic.search_projection_version = 'search-v1-pg17-simple-u15-p2'
      AND ($2::boolean OR topic.state <> 'hidden')
      AND (
        $2::boolean OR area.visibility = 'public'
        OR ($3::boolean AND area.visibility = 'authenticated')
        OR ($3::boolean AND area.visibility = 'groups'
            AND COALESCE(cardinality($4::bigint[]), 0) > 0
            AND EXISTS (SELECT 1 FROM public.area_groups AS membership
                WHERE membership.area_id = area.id AND membership.group_id = ANY($4::bigint[])))
      )
      AND (NOT $5::boolean OR post.search_vector @@ $6::text::tsquery)
) AS selected ON true
ORDER BY expected_page.result_ordinal
`

type SearchDiscoveryPageParams struct {
	PageOffset  int32
	IsStaff     bool
	IsMember    bool
	GroupIds    []int64
	HasQuery    bool
	ParsedQuery string
	AuthorID    int64
	AreaSlug    string
	HasFrom     bool
	FromTime    pgtype.Timestamptz
	HasTo       bool
	ToInclusive bool
	ToTime      pgtype.Timestamptz
}

type SearchDiscoveryPageRow struct {
	ExpectedKind  string
	ExpectedID    int64
	ResultOrdinal int32
	ResultRank    float32
	HasNextPage   bool
	BeyondWindow  bool
	ResultKind    string
	ResultID      int64
	AreaID        int64
	AreaSlug      string
	AreaName      string
	TopicID       int64
	TopicTitle    string
	PostID        pgtype.Int8
	AuthorID      int64
	AuthorName    string
	CreatedAt     pgtype.Timestamptz
	RenderedHtml  pgtype.Text
}

func (q *Queries) SearchDiscoveryPage(ctx context.Context, arg SearchDiscoveryPageParams) ([]SearchDiscoveryPageRow, error) {
	rows, err := q.db.Query(ctx, searchDiscoveryPage,
		arg.PageOffset,
		arg.IsStaff,
		arg.IsMember,
		arg.GroupIds,
		arg.HasQuery,
		arg.ParsedQuery,
		arg.AuthorID,
		arg.AreaSlug,
		arg.HasFrom,
		arg.FromTime,
		arg.HasTo,
		arg.ToInclusive,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchDiscoveryPageRow{}
	for rows.Next() {
		var i SearchDiscoveryPageRow
		if err := rows.Scan(
			&i.ExpectedKind,
			&i.ExpectedID,
			&i.ResultOrdinal,
			&i.ResultRank,
			&i.HasNextPage,
			&i.BeyondWindow,
			&i.ResultKind,
			&i.ResultID,
			&i.AreaID,
			&i.AreaSlug,
			&i.AreaName,
			&i.TopicID,
			&i.TopicTitle,
			&i.PostID,
			&i.AuthorID,
			&i.AuthorName,
			&i.CreatedAt,
			&i.RenderedHtml,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
