// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: editing.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEditablePost = `-- name: GetEditablePost :one
SELECT
    post.id AS post_id,
    post.topic_id,
    post.post_number,
    post.markdown_source,
    post.revision,
    (
        SELECT count(*)::bigint
        FROM public.posts AS node
        WHERE node.topic_id = post.topic_id
          AND node.thread_path <= post.thread_path
          AND (
            node.deleted_at IS NULL
            OR EXISTS (
                SELECT 1 FROM public.posts AS descendant
                WHERE descendant.topic_id = node.topic_id
                  AND descendant.deleted_at IS NULL
                  AND descendant.thread_path[1:cardinality(node.thread_path)] = node.thread_path
                  AND cardinality(descendant.thread_path) > cardinality(node.thread_path)
            )
          )
    ) AS node_ordinal
FROM public.posts AS post
JOIN public.topics AS topic ON topic.id = post.topic_id
JOIN public.areas AS area ON area.id = topic.area_id
WHERE post.id = $1
  AND post.author_id = $2
  AND post.deleted_at IS NULL
  AND topic.deleted_at IS NULL
  AND ($3::boolean OR topic.state <> 'hidden')
  AND (
    $3::boolean
    OR area.visibility IN ('public', 'authenticated')
    OR (
      area.visibility = 'groups'
      AND COALESCE(cardinality($4::bigint[]), 0) > 0
      AND EXISTS (
        SELECT 1
        FROM public.area_groups AS membership
        WHERE membership.area_id = area.id
          AND membership.group_id = ANY($4::bigint[])
      )
    )
  )
`

type GetEditablePostParams struct {
	PostID   int64
	AuthorID int64
	IsStaff  bool
	GroupIds []int64
}

type GetEditablePostRow struct {
	PostID         int64
	TopicID        int64
	PostNumber     int32
	MarkdownSource string
	Revision       int32
	NodeOrdinal    int64
}

func (q *Queries) GetEditablePost(ctx context.Context, arg GetEditablePostParams) (GetEditablePostRow, error) {
	row := q.db.QueryRow(ctx, getEditablePost,
		arg.PostID,
		arg.AuthorID,
		arg.IsStaff,
		arg.GroupIds,
	)
	var i GetEditablePostRow
	err := row.Scan(
		&i.PostID,
		&i.TopicID,
		&i.PostNumber,
		&i.MarkdownSource,
		&i.Revision,
		&i.NodeOrdinal,
	)
	return i, err
}

const lockPostForEdit = `-- name: LockPostForEdit :one
SELECT
    post.id AS post_id,
    post.author_id,
    post.revision,
    post.topic_id,
    post.post_number,
    topic.state AS topic_state,
    area.id AS area_id,
    area.visibility,
    area.posting_mode
FROM public.posts AS post
JOIN public.topics AS topic ON topic.id = post.topic_id
JOIN public.areas AS area ON area.id = topic.area_id
WHERE post.id = $1
  AND post.deleted_at IS NULL
  AND topic.deleted_at IS NULL
FOR UPDATE OF post
FOR SHARE OF topic, area
`

type LockPostForEditRow struct {
	PostID      int64
	AuthorID    int64
	Revision    int32
	TopicID     int64
	PostNumber  int32
	TopicState  string
	AreaID      int64
	Visibility  string
	PostingMode string
}

func (q *Queries) LockPostForEdit(ctx context.Context, postID int64) (LockPostForEditRow, error) {
	row := q.db.QueryRow(ctx, lockPostForEdit, postID)
	var i LockPostForEditRow
	err := row.Scan(
		&i.PostID,
		&i.AuthorID,
		&i.Revision,
		&i.TopicID,
		&i.PostNumber,
		&i.TopicState,
		&i.AreaID,
		&i.Visibility,
		&i.PostingMode,
	)
	return i, err
}

const softDeletePost = `-- name: SoftDeletePost :one
UPDATE public.posts AS post
SET deleted_at = GREATEST(
        $1::timestamptz,
        post.created_at,
        post.updated_at,
        COALESCE(post.edited_at, '-infinity'::timestamptz)
    ),
    deleted_by = $2::bigint,
    deletion_reason = 'Deleted by author'
WHERE post.id = $3
  AND post.author_id = $2::bigint
  AND post.revision = $4
  AND post.deleted_at IS NULL
RETURNING post.id AS post_id, post.topic_id, post.post_number, post.revision
`

type SoftDeletePostParams struct {
	AtTime           pgtype.Timestamptz
	AuthorID         int64
	PostID           int64
	ExpectedRevision int32
}

type SoftDeletePostRow struct {
	PostID     int64
	TopicID    int64
	PostNumber int32
	Revision   int32
}

func (q *Queries) SoftDeletePost(ctx context.Context, arg SoftDeletePostParams) (SoftDeletePostRow, error) {
	row := q.db.QueryRow(ctx, softDeletePost,
		arg.AtTime,
		arg.AuthorID,
		arg.PostID,
		arg.ExpectedRevision,
	)
	var i SoftDeletePostRow
	err := row.Scan(
		&i.PostID,
		&i.TopicID,
		&i.PostNumber,
		&i.Revision,
	)
	return i, err
}

const updatePostRevision = `-- name: UpdatePostRevision :one
WITH updated AS (
    UPDATE public.posts AS post
    SET markdown_source = $1,
        rendered_html = $2,
        renderer_version = $3,
        revision = post.revision + 1,
        updated_at = GREATEST($4::timestamptz, post.updated_at, COALESCE(post.edited_at, '-infinity'::timestamptz)),
        edited_at = GREATEST($4::timestamptz, post.updated_at, COALESCE(post.edited_at, '-infinity'::timestamptz))
    WHERE post.id = $5
      AND post.revision = $6
      AND post.deleted_at IS NULL
    RETURNING post.id AS post_id, post.topic_id, post.post_number, post.thread_path, post.revision
)
SELECT
    updated.post_id,
    updated.topic_id,
    updated.post_number,
    updated.revision,
    (
        SELECT count(*)::bigint
        FROM public.posts AS node
        WHERE node.topic_id = updated.topic_id
          AND node.thread_path <= updated.thread_path
          AND (
            node.deleted_at IS NULL
            OR EXISTS (
                SELECT 1 FROM public.posts AS descendant
                WHERE descendant.topic_id = node.topic_id
                  AND descendant.deleted_at IS NULL
                  AND descendant.thread_path[1:cardinality(node.thread_path)] = node.thread_path
                  AND cardinality(descendant.thread_path) > cardinality(node.thread_path)
            )
          )
    ) AS node_ordinal
FROM updated
`

type UpdatePostRevisionParams struct {
	MarkdownSource   string
	RenderedHtml     string
	RendererVersion  string
	AtTime           pgtype.Timestamptz
	PostID           int64
	ExpectedRevision int32
}

type UpdatePostRevisionRow struct {
	PostID      int64
	TopicID     int64
	PostNumber  int32
	Revision    int32
	NodeOrdinal int64
}

func (q *Queries) UpdatePostRevision(ctx context.Context, arg UpdatePostRevisionParams) (UpdatePostRevisionRow, error) {
	row := q.db.QueryRow(ctx, updatePostRevision,
		arg.MarkdownSource,
		arg.RenderedHtml,
		arg.RendererVersion,
		arg.AtTime,
		arg.PostID,
		arg.ExpectedRevision,
	)
	var i UpdatePostRevisionRow
	err := row.Scan(
		&i.PostID,
		&i.TopicID,
		&i.PostNumber,
		&i.Revision,
		&i.NodeOrdinal,
	)
	return i, err
}
