// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: editing.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const lockPostForEdit = `-- name: LockPostForEdit :one
SELECT
    post.id AS post_id,
    post.author_id,
    post.revision,
    post.topic_id,
    post.post_number,
    topic.state AS topic_state,
    area.id AS area_id,
    area.visibility,
    area.posting_mode
FROM public.posts AS post
JOIN public.topics AS topic ON topic.id = post.topic_id
JOIN public.areas AS area ON area.id = topic.area_id
WHERE post.id = $1
  AND post.deleted_at IS NULL
  AND topic.deleted_at IS NULL
FOR UPDATE OF post
FOR SHARE OF topic, area
`

type LockPostForEditRow struct {
	PostID      int64
	AuthorID    int64
	Revision    int32
	TopicID     int64
	PostNumber  int32
	TopicState  string
	AreaID      int64
	Visibility  string
	PostingMode string
}

func (q *Queries) LockPostForEdit(ctx context.Context, postID int64) (LockPostForEditRow, error) {
	row := q.db.QueryRow(ctx, lockPostForEdit, postID)
	var i LockPostForEditRow
	err := row.Scan(
		&i.PostID,
		&i.AuthorID,
		&i.Revision,
		&i.TopicID,
		&i.PostNumber,
		&i.TopicState,
		&i.AreaID,
		&i.Visibility,
		&i.PostingMode,
	)
	return i, err
}

const updatePostRevision = `-- name: UpdatePostRevision :one
UPDATE public.posts AS post
SET markdown_source = $1,
    rendered_html = $2,
    renderer_version = $3,
    revision = post.revision + 1,
    updated_at = GREATEST($4::timestamptz, post.updated_at, COALESCE(post.edited_at, '-infinity'::timestamptz)),
    edited_at = GREATEST($4::timestamptz, post.updated_at, COALESCE(post.edited_at, '-infinity'::timestamptz))
WHERE post.id = $5
  AND post.revision = $6
  AND post.deleted_at IS NULL
RETURNING post.id AS post_id, post.topic_id, post.post_number, post.revision
`

type UpdatePostRevisionParams struct {
	MarkdownSource   string
	RenderedHtml     string
	RendererVersion  string
	AtTime           pgtype.Timestamptz
	PostID           int64
	ExpectedRevision int32
}

type UpdatePostRevisionRow struct {
	PostID     int64
	TopicID    int64
	PostNumber int32
	Revision   int32
}

func (q *Queries) UpdatePostRevision(ctx context.Context, arg UpdatePostRevisionParams) (UpdatePostRevisionRow, error) {
	row := q.db.QueryRow(ctx, updatePostRevision,
		arg.MarkdownSource,
		arg.RenderedHtml,
		arg.RendererVersion,
		arg.AtTime,
		arg.PostID,
		arg.ExpectedRevision,
	)
	var i UpdatePostRevisionRow
	err := row.Scan(
		&i.PostID,
		&i.TopicID,
		&i.PostNumber,
		&i.Revision,
	)
	return i, err
}
