// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: foundation.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveAdministrators = `-- name: CountActiveAdministrators :one
SELECT count(*)::bigint
FROM public.users
WHERE role = 'administrator'
  AND (
      suspended_at IS NULL
      OR suspended_at > $1::timestamptz
      OR suspended_until <= $1::timestamptz
  )
`

func (q *Queries) CountActiveAdministrators(ctx context.Context, atTime pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdministrators, atTime)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countGovernanceRows = `-- name: CountGovernanceRows :one
SELECT count(*)::bigint
FROM public.governance_state
`

func (q *Queries) CountGovernanceRows(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countGovernanceRows)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getUserByExternalIdentity = `-- name: GetUserByExternalIdentity :one
SELECT u.id, u.display_name, u.email, u.avatar_url, u.bio, u.role, u.suspended_at, u.suspended_until, u.suspension_reason, u.muted_until, u.created_at, u.updated_at, u.last_login_at
FROM public.users AS u
JOIN public.external_identities AS identity ON identity.user_id = u.id
WHERE identity.issuer = $1
  AND identity.subject = $2
`

type GetUserByExternalIdentityParams struct {
	Issuer  string
	Subject string
}

func (q *Queries) GetUserByExternalIdentity(ctx context.Context, arg GetUserByExternalIdentityParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByExternalIdentity, arg.Issuer, arg.Subject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.AvatarUrl,
		&i.Bio,
		&i.Role,
		&i.SuspendedAt,
		&i.SuspendedUntil,
		&i.SuspensionReason,
		&i.MutedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const insertExternalIdentity = `-- name: InsertExternalIdentity :exec
INSERT INTO public.external_identities (user_id, issuer, subject, created_at, last_verified_at)
VALUES (
    $1, $2, $3,
    $4, $4
)
`

type InsertExternalIdentityParams struct {
	UserID     int64
	Issuer     string
	Subject    string
	VerifiedAt pgtype.Timestamptz
}

func (q *Queries) InsertExternalIdentity(ctx context.Context, arg InsertExternalIdentityParams) error {
	_, err := q.db.Exec(ctx, insertExternalIdentity,
		arg.UserID,
		arg.Issuer,
		arg.Subject,
		arg.VerifiedAt,
	)
	return err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO public.users (display_name, email, avatar_url, created_at, updated_at, last_login_at)
VALUES (
    $1, $2, $3,
    $4, $4, $4
)
RETURNING id, display_name, email, avatar_url, bio, role, suspended_at, suspended_until, suspension_reason, muted_until, created_at, updated_at, last_login_at
`

type InsertUserParams struct {
	DisplayName string
	Email       pgtype.Text
	AvatarUrl   pgtype.Text
	LoginAt     pgtype.Timestamptz
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.DisplayName,
		arg.Email,
		arg.AvatarUrl,
		arg.LoginAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.AvatarUrl,
		&i.Bio,
		&i.Role,
		&i.SuspendedAt,
		&i.SuspendedUntil,
		&i.SuspensionReason,
		&i.MutedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const lockGovernanceState = `-- name: LockGovernanceState :one
SELECT singleton
FROM public.governance_state
WHERE singleton
FOR UPDATE
`

func (q *Queries) LockGovernanceState(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, lockGovernanceState)
	var singleton bool
	err := row.Scan(&singleton)
	return singleton, err
}
