// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: foundation.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveAdministrators = `-- name: CountActiveAdministrators :one
SELECT count(*)::bigint
FROM public.users
WHERE role = 'administrator'
  AND (
      suspended_at IS NULL
      OR suspended_at > $1::timestamptz
      OR suspended_until <= $1::timestamptz
  )
`

func (q *Queries) CountActiveAdministrators(ctx context.Context, atTime pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdministrators, atTime)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countGovernanceRows = `-- name: CountGovernanceRows :one
SELECT count(*)::bigint
FROM public.governance_state
`

func (q *Queries) CountGovernanceRows(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countGovernanceRows)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getActiveSessionForRotation = `-- name: GetActiveSessionForRotation :one
SELECT
    session.user_id,
    identity.issuer,
    identity.subject,
    session.expires_at
FROM public.sessions AS session
JOIN public.users AS forum_user ON forum_user.id = session.user_id
JOIN public.external_identities AS identity ON identity.user_id = session.user_id
WHERE session.id = $1
  AND session.token_hash = $2
  AND session.revoked_at IS NULL
  AND session.issued_at <= $3
  AND session.last_seen_at <= $3
  AND session.validated_at <= $3
  AND session.expires_at > $3
  AND session.last_seen_at > $4
  AND (
      forum_user.suspended_at IS NULL
      OR forum_user.suspended_at > $3
      OR forum_user.suspended_until <= $3
  )
FOR UPDATE OF session, forum_user, identity
`

type GetActiveSessionForRotationParams struct {
	SessionID  int64
	TokenHash  []byte
	ObservedAt pgtype.Timestamptz
	IdleCutoff pgtype.Timestamptz
}

type GetActiveSessionForRotationRow struct {
	UserID    int64
	Issuer    string
	Subject   string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) GetActiveSessionForRotation(ctx context.Context, arg GetActiveSessionForRotationParams) (GetActiveSessionForRotationRow, error) {
	row := q.db.QueryRow(ctx, getActiveSessionForRotation,
		arg.SessionID,
		arg.TokenHash,
		arg.ObservedAt,
		arg.IdleCutoff,
	)
	var i GetActiveSessionForRotationRow
	err := row.Scan(
		&i.UserID,
		&i.Issuer,
		&i.Subject,
		&i.ExpiresAt,
	)
	return i, err
}

const getUserByExternalIdentity = `-- name: GetUserByExternalIdentity :one
SELECT u.id, u.display_name, u.email, u.avatar_url, u.bio, u.role, u.suspended_at, u.suspended_until, u.suspension_reason, u.muted_until, u.created_at, u.updated_at, u.last_login_at
FROM public.users AS u
JOIN public.external_identities AS identity ON identity.user_id = u.id
WHERE identity.issuer = $1
  AND identity.subject = $2
`

type GetUserByExternalIdentityParams struct {
	Issuer  string
	Subject string
}

func (q *Queries) GetUserByExternalIdentity(ctx context.Context, arg GetUserByExternalIdentityParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByExternalIdentity, arg.Issuer, arg.Subject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.AvatarUrl,
		&i.Bio,
		&i.Role,
		&i.SuspendedAt,
		&i.SuspendedUntil,
		&i.SuspensionReason,
		&i.MutedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const insertExternalIdentity = `-- name: InsertExternalIdentity :exec
INSERT INTO public.external_identities (user_id, issuer, subject, created_at, last_verified_at)
VALUES (
    $1, $2, $3,
    $4, $4
)
`

type InsertExternalIdentityParams struct {
	UserID     int64
	Issuer     string
	Subject    string
	VerifiedAt pgtype.Timestamptz
}

func (q *Queries) InsertExternalIdentity(ctx context.Context, arg InsertExternalIdentityParams) error {
	_, err := q.db.Exec(ctx, insertExternalIdentity,
		arg.UserID,
		arg.Issuer,
		arg.Subject,
		arg.VerifiedAt,
	)
	return err
}

const insertSession = `-- name: InsertSession :one
INSERT INTO public.sessions (
    token_hash,
    user_id,
    issued_at,
    last_seen_at,
    validated_at,
    expires_at,
    user_agent_hash,
    ip_prefix
)
VALUES (
    $1,
    $2,
    $3,
    $3,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, token_hash, user_id, issued_at, last_seen_at, validated_at, expires_at, revoked_at, user_agent_hash, ip_prefix
`

type InsertSessionParams struct {
	TokenHash     []byte
	UserID        int64
	IssuedAt      pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
	UserAgentHash []byte
	IpPrefix      *netip.Addr
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, insertSession,
		arg.TokenHash,
		arg.UserID,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.UserAgentHash,
		arg.IpPrefix,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.IssuedAt,
		&i.LastSeenAt,
		&i.ValidatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserAgentHash,
		&i.IpPrefix,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO public.users (display_name, email, avatar_url, created_at, updated_at, last_login_at)
VALUES (
    $1, $2, $3,
    $4, $4, $4
)
RETURNING id, display_name, email, avatar_url, bio, role, suspended_at, suspended_until, suspension_reason, muted_until, created_at, updated_at, last_login_at
`

type InsertUserParams struct {
	DisplayName string
	Email       pgtype.Text
	AvatarUrl   pgtype.Text
	LoginAt     pgtype.Timestamptz
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.DisplayName,
		arg.Email,
		arg.AvatarUrl,
		arg.LoginAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.AvatarUrl,
		&i.Bio,
		&i.Role,
		&i.SuspendedAt,
		&i.SuspendedUntil,
		&i.SuspensionReason,
		&i.MutedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const lockExternalIdentity = `-- name: LockExternalIdentity :one
WITH acquired AS MATERIALIZED (
    SELECT pg_advisory_xact_lock(
        hashtext($1::text),
        hashtext($2::text)
    ) AS ignored
)
SELECT true::boolean AS locked
FROM acquired
`

type LockExternalIdentityParams struct {
	Issuer  string
	Subject string
}

func (q *Queries) LockExternalIdentity(ctx context.Context, arg LockExternalIdentityParams) (bool, error) {
	row := q.db.QueryRow(ctx, lockExternalIdentity, arg.Issuer, arg.Subject)
	var locked bool
	err := row.Scan(&locked)
	return locked, err
}

const lockGovernanceState = `-- name: LockGovernanceState :one
SELECT singleton
FROM public.governance_state
WHERE singleton
FOR UPDATE
`

func (q *Queries) LockGovernanceState(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, lockGovernanceState)
	var singleton bool
	err := row.Scan(&singleton)
	return singleton, err
}

const updateExternalIdentityVerification = `-- name: UpdateExternalIdentityVerification :exec
UPDATE public.external_identities
SET last_verified_at = $1
WHERE user_id = $2
`

type UpdateExternalIdentityVerificationParams struct {
	VerifiedAt pgtype.Timestamptz
	UserID     int64
}

func (q *Queries) UpdateExternalIdentityVerification(ctx context.Context, arg UpdateExternalIdentityVerificationParams) error {
	_, err := q.db.Exec(ctx, updateExternalIdentityVerification, arg.VerifiedAt, arg.UserID)
	return err
}

const updateUserFromOIDC = `-- name: UpdateUserFromOIDC :one
UPDATE public.users
SET display_name = $1,
    email = $2,
    avatar_url = $3,
    updated_at = $4,
    last_login_at = $4
WHERE id = $5
RETURNING id, display_name, email, avatar_url, bio, role, suspended_at, suspended_until, suspension_reason, muted_until, created_at, updated_at, last_login_at
`

type UpdateUserFromOIDCParams struct {
	DisplayName string
	Email       pgtype.Text
	AvatarUrl   pgtype.Text
	LoginAt     pgtype.Timestamptz
	UserID      int64
}

func (q *Queries) UpdateUserFromOIDC(ctx context.Context, arg UpdateUserFromOIDCParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserFromOIDC,
		arg.DisplayName,
		arg.Email,
		arg.AvatarUrl,
		arg.LoginAt,
		arg.UserID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.AvatarUrl,
		&i.Bio,
		&i.Role,
		&i.SuspendedAt,
		&i.SuspendedUntil,
		&i.SuspensionReason,
		&i.MutedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}
