// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: moderation.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const changeTopicStateAndAudit = `-- name: ChangeTopicStateAndAudit :one
WITH changed AS (
    UPDATE public.topics AS topic
    SET state = $1,
        updated_at = GREATEST($2::timestamptz, topic.updated_at)
    WHERE topic.id = $3
      AND topic.state = $4
      AND topic.deleted_at IS NULL
    RETURNING topic.id, topic.state, topic.updated_at
),
audit AS (
    INSERT INTO public.moderation_actions (
        actor_kind,
        actor_user_id,
        target_type,
        target_topic_id,
        action_type,
        reason,
        previous_state,
        resulting_state,
        request_id,
        created_at
    )
    SELECT
        'forum_user',
        $5,
        'topic',
        changed.id,
        $6,
        $7,
        jsonb_build_object('state', $4::text),
        jsonb_build_object('state', changed.state),
        $8,
        changed.updated_at
    FROM changed
    RETURNING id, target_topic_id
)
SELECT changed.id AS topic_id, changed.state, changed.updated_at, audit.id AS audit_id
FROM changed
JOIN audit ON audit.target_topic_id = changed.id
`

type ChangeTopicStateAndAuditParams struct {
	ResultingState string
	AtTime         pgtype.Timestamptz
	TopicID        int64
	PreviousState  string
	ActorUserID    pgtype.Int8
	ActionType     string
	Reason         pgtype.Text
	RequestID      pgtype.UUID
}

type ChangeTopicStateAndAuditRow struct {
	TopicID   int64
	State     string
	UpdatedAt pgtype.Timestamptz
	AuditID   int64
}

func (q *Queries) ChangeTopicStateAndAudit(ctx context.Context, arg ChangeTopicStateAndAuditParams) (ChangeTopicStateAndAuditRow, error) {
	row := q.db.QueryRow(ctx, changeTopicStateAndAudit,
		arg.ResultingState,
		arg.AtTime,
		arg.TopicID,
		arg.PreviousState,
		arg.ActorUserID,
		arg.ActionType,
		arg.Reason,
		arg.RequestID,
	)
	var i ChangeTopicStateAndAuditRow
	err := row.Scan(
		&i.TopicID,
		&i.State,
		&i.UpdatedAt,
		&i.AuditID,
	)
	return i, err
}

const lockTopicForModeration = `-- name: LockTopicForModeration :one
SELECT topic.id, topic.state
FROM public.topics AS topic
WHERE topic.id = $1
  AND topic.deleted_at IS NULL
FOR UPDATE OF topic
`

type LockTopicForModerationRow struct {
	ID    int64
	State string
}

func (q *Queries) LockTopicForModeration(ctx context.Context, topicID int64) (LockTopicForModerationRow, error) {
	row := q.db.QueryRow(ctx, lockTopicForModeration, topicID)
	var i LockTopicForModerationRow
	err := row.Scan(&i.ID, &i.State)
	return i, err
}

const lockUserForSuspension = `-- name: LockUserForSuspension :one
SELECT
    forum_user.id,
    forum_user.role,
    forum_user.suspended_at,
    forum_user.suspended_until,
    forum_user.suspension_reason,
    forum_user.muted_until,
    forum_user.created_at,
    forum_user.updated_at
FROM public.users AS forum_user
WHERE forum_user.id = $1
FOR UPDATE OF forum_user
`

type LockUserForSuspensionRow struct {
	ID               int64
	Role             string
	SuspendedAt      pgtype.Timestamptz
	SuspendedUntil   pgtype.Timestamptz
	SuspensionReason pgtype.Text
	MutedUntil       pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) LockUserForSuspension(ctx context.Context, userID int64) (LockUserForSuspensionRow, error) {
	row := q.db.QueryRow(ctx, lockUserForSuspension, userID)
	var i LockUserForSuspensionRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.SuspendedAt,
		&i.SuspendedUntil,
		&i.SuspensionReason,
		&i.MutedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reinstateUserAndAudit = `-- name: ReinstateUserAndAudit :one
WITH changed AS (
    UPDATE public.users AS forum_user
    SET suspended_at = NULL,
        suspended_until = NULL,
        suspension_reason = NULL,
        updated_at = GREATEST($1::timestamptz, forum_user.updated_at)
    WHERE forum_user.id = $2
      AND forum_user.suspended_at <= $3::timestamptz
      AND (
          forum_user.suspended_until IS NULL
          OR forum_user.suspended_until > $3::timestamptz
      )
    RETURNING forum_user.id, forum_user.suspended_at, forum_user.suspended_until,
              forum_user.suspension_reason, forum_user.updated_at
),
audit AS (
    INSERT INTO public.moderation_actions (
        actor_kind,
        actor_user_id,
        target_type,
        target_user_id,
        action_type,
        reason,
        previous_state,
        resulting_state,
        request_id,
        created_at
    )
    SELECT
        'forum_user',
        $4,
        'user',
        changed.id,
        'reinstate_user',
        $5,
        jsonb_build_object(
            'suspended_at', $6::timestamptz,
            'suspended_until', $7::timestamptz,
            'suspension_reason', $8::text
        ),
        jsonb_build_object(
            'suspended_at', changed.suspended_at,
            'suspended_until', changed.suspended_until,
            'suspension_reason', changed.suspension_reason
        ),
        $9,
        changed.updated_at
    FROM changed
    RETURNING id, target_user_id
)
SELECT changed.id AS user_id, changed.suspended_at, changed.suspended_until,
       changed.suspension_reason, changed.updated_at, audit.id AS audit_id
FROM changed
JOIN audit ON audit.target_user_id = changed.id
`

type ReinstateUserAndAuditParams struct {
	UpdatedAt                pgtype.Timestamptz
	UserID                   int64
	ObservedAt               pgtype.Timestamptz
	ActorUserID              pgtype.Int8
	Reason                   pgtype.Text
	PreviousSuspendedAt      pgtype.Timestamptz
	PreviousSuspendedUntil   pgtype.Timestamptz
	PreviousSuspensionReason string
	RequestID                pgtype.UUID
}

type ReinstateUserAndAuditRow struct {
	UserID           int64
	SuspendedAt      pgtype.Timestamptz
	SuspendedUntil   pgtype.Timestamptz
	SuspensionReason pgtype.Text
	UpdatedAt        pgtype.Timestamptz
	AuditID          int64
}

func (q *Queries) ReinstateUserAndAudit(ctx context.Context, arg ReinstateUserAndAuditParams) (ReinstateUserAndAuditRow, error) {
	row := q.db.QueryRow(ctx, reinstateUserAndAudit,
		arg.UpdatedAt,
		arg.UserID,
		arg.ObservedAt,
		arg.ActorUserID,
		arg.Reason,
		arg.PreviousSuspendedAt,
		arg.PreviousSuspendedUntil,
		arg.PreviousSuspensionReason,
		arg.RequestID,
	)
	var i ReinstateUserAndAuditRow
	err := row.Scan(
		&i.UserID,
		&i.SuspendedAt,
		&i.SuspendedUntil,
		&i.SuspensionReason,
		&i.UpdatedAt,
		&i.AuditID,
	)
	return i, err
}

const suspendUserAndAudit = `-- name: SuspendUserAndAudit :one
WITH changed AS (
    UPDATE public.users AS forum_user
    SET suspended_at = GREATEST($1::timestamptz, forum_user.created_at),
        suspended_until = NULL,
        suspension_reason = $2,
        updated_at = GREATEST($3::timestamptz, forum_user.updated_at)
    WHERE forum_user.id = $4
      AND (
          forum_user.suspended_at IS NULL
          OR forum_user.suspended_at > $5::timestamptz
          OR forum_user.suspended_until <= $5::timestamptz
      )
    RETURNING forum_user.id, forum_user.suspended_at, forum_user.suspended_until,
              forum_user.suspension_reason, forum_user.updated_at
),
audit AS (
    INSERT INTO public.moderation_actions (
        actor_kind,
        actor_user_id,
        target_type,
        target_user_id,
        action_type,
        reason,
        previous_state,
        resulting_state,
        request_id,
        created_at
    )
    SELECT
        'forum_user',
        $6,
        'user',
        changed.id,
        'suspend_user',
        $2,
        jsonb_build_object(
            'suspended_at', $7::timestamptz,
            'suspended_until', $8::timestamptz,
            'suspension_reason', $9::text
        ),
        jsonb_build_object(
            'suspended_at', changed.suspended_at,
            'suspended_until', changed.suspended_until,
            'suspension_reason', changed.suspension_reason
        ),
        $10,
        changed.updated_at
    FROM changed
    RETURNING id, target_user_id
)
SELECT changed.id AS user_id, changed.suspended_at, changed.suspended_until,
       changed.suspension_reason, changed.updated_at, audit.id AS audit_id
FROM changed
JOIN audit ON audit.target_user_id = changed.id
`

type SuspendUserAndAuditParams struct {
	SuspendedAt              pgtype.Timestamptz
	Reason                   pgtype.Text
	UpdatedAt                pgtype.Timestamptz
	UserID                   int64
	ObservedAt               pgtype.Timestamptz
	ActorUserID              pgtype.Int8
	PreviousSuspendedAt      pgtype.Timestamptz
	PreviousSuspendedUntil   pgtype.Timestamptz
	PreviousSuspensionReason pgtype.Text
	RequestID                pgtype.UUID
}

type SuspendUserAndAuditRow struct {
	UserID           int64
	SuspendedAt      pgtype.Timestamptz
	SuspendedUntil   pgtype.Timestamptz
	SuspensionReason pgtype.Text
	UpdatedAt        pgtype.Timestamptz
	AuditID          int64
}

func (q *Queries) SuspendUserAndAudit(ctx context.Context, arg SuspendUserAndAuditParams) (SuspendUserAndAuditRow, error) {
	row := q.db.QueryRow(ctx, suspendUserAndAudit,
		arg.SuspendedAt,
		arg.Reason,
		arg.UpdatedAt,
		arg.UserID,
		arg.ObservedAt,
		arg.ActorUserID,
		arg.PreviousSuspendedAt,
		arg.PreviousSuspendedUntil,
		arg.PreviousSuspensionReason,
		arg.RequestID,
	)
	var i SuspendUserAndAuditRow
	err := row.Scan(
		&i.UserID,
		&i.SuspendedAt,
		&i.SuspendedUntil,
		&i.SuspensionReason,
		&i.UpdatedAt,
		&i.AuditID,
	)
	return i, err
}
