// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: moderation.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const changeTopicStateAndAudit = `-- name: ChangeTopicStateAndAudit :one
WITH changed AS (
    UPDATE public.topics AS topic
    SET state = $1,
        updated_at = GREATEST($2::timestamptz, topic.updated_at)
    WHERE topic.id = $3
      AND topic.state = $4
      AND topic.deleted_at IS NULL
    RETURNING topic.id, topic.state, topic.updated_at
),
audit AS (
    INSERT INTO public.moderation_actions (
        actor_kind,
        actor_user_id,
        target_type,
        target_topic_id,
        action_type,
        reason,
        previous_state,
        resulting_state,
        request_id,
        created_at
    )
    SELECT
        'forum_user',
        $5,
        'topic',
        changed.id,
        $6,
        $7,
        jsonb_build_object('state', $4::text),
        jsonb_build_object('state', changed.state),
        $8,
        changed.updated_at
    FROM changed
    RETURNING id, target_topic_id
)
SELECT changed.id AS topic_id, changed.state, changed.updated_at, audit.id AS audit_id
FROM changed
JOIN audit ON audit.target_topic_id = changed.id
`

type ChangeTopicStateAndAuditParams struct {
	ResultingState string
	AtTime         pgtype.Timestamptz
	TopicID        int64
	PreviousState  string
	ActorUserID    pgtype.Int8
	ActionType     string
	Reason         pgtype.Text
	RequestID      pgtype.UUID
}

type ChangeTopicStateAndAuditRow struct {
	TopicID   int64
	State     string
	UpdatedAt pgtype.Timestamptz
	AuditID   int64
}

func (q *Queries) ChangeTopicStateAndAudit(ctx context.Context, arg ChangeTopicStateAndAuditParams) (ChangeTopicStateAndAuditRow, error) {
	row := q.db.QueryRow(ctx, changeTopicStateAndAudit,
		arg.ResultingState,
		arg.AtTime,
		arg.TopicID,
		arg.PreviousState,
		arg.ActorUserID,
		arg.ActionType,
		arg.Reason,
		arg.RequestID,
	)
	var i ChangeTopicStateAndAuditRow
	err := row.Scan(
		&i.TopicID,
		&i.State,
		&i.UpdatedAt,
		&i.AuditID,
	)
	return i, err
}

const lockTopicForModeration = `-- name: LockTopicForModeration :one
SELECT topic.id, topic.state
FROM public.topics AS topic
WHERE topic.id = $1
  AND topic.deleted_at IS NULL
FOR UPDATE OF topic
`

type LockTopicForModerationRow struct {
	ID    int64
	State string
}

func (q *Queries) LockTopicForModeration(ctx context.Context, topicID int64) (LockTopicForModerationRow, error) {
	row := q.db.QueryRow(ctx, lockTopicForModeration, topicID)
	var i LockTopicForModerationRow
	err := row.Scan(&i.ID, &i.State)
	return i, err
}
