// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Area struct {
	ID           int64
	Slug         string
	Name         string
	Description  string
	DisplayOrder int32
	Visibility   string
	PostingMode  string
	CreatedBy    int64
	UpdatedBy    int64
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type AreaGroup struct {
	AreaID    int64
	GroupID   int64
	AddedBy   int64
	CreatedAt pgtype.Timestamptz
}

type ExternalIdentity struct {
	UserID         int64
	Issuer         string
	Subject        string
	CreatedAt      pgtype.Timestamptz
	LastVerifiedAt pgtype.Timestamptz
}

type ForumGroup struct {
	ID        int64
	Name      string
	CreatedBy int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ForumGroupMember struct {
	GroupID   int64
	UserID    int64
	GrantedBy int64
	CreatedAt pgtype.Timestamptz
}

type GovernanceState struct {
	Singleton bool
	CreatedAt pgtype.Timestamptz
}

type ModerationAction struct {
	ID                 int64
	ActorKind          string
	ActorUserID        pgtype.Int8
	OperatorIdentifier pgtype.Text
	TargetType         string
	TargetUserID       pgtype.Int8
	TargetGroupID      pgtype.Int8
	TargetAreaID       pgtype.Int8
	TargetTopicID      pgtype.Int8
	TargetPostID       pgtype.Int8
	TargetReportID     pgtype.Int8
	ActionType         string
	Reason             pgtype.Text
	PreviousState      []byte
	ResultingState     []byte
	RequestID          pgtype.UUID
	CreatedAt          pgtype.Timestamptz
}

type OidcLoginAttempt struct {
	StateHash              []byte
	NonceCiphertext        []byte
	PkceVerifierCiphertext []byte
	Purpose                string
	SessionID              pgtype.Int8
	ReturnPath             string
	CreatedAt              pgtype.Timestamptz
	ExpiresAt              pgtype.Timestamptz
	ConsumedAt             pgtype.Timestamptz
}

type Post struct {
	ID              int64
	TopicID         int64
	AuthorID        int64
	PostNumber      int32
	MarkdownSource  string
	RenderedHtml    string
	RendererVersion string
	Revision        int32
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	EditedAt        pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	DeletedBy       pgtype.Int8
	DeletionReason  pgtype.Text
}

type Report struct {
	ID         int64
	ReportedBy int64
	TopicID    pgtype.Int8
	PostID     pgtype.Int8
	UserID     pgtype.Int8
	Reason     string
	Status     string
	AssignedTo pgtype.Int8
	Resolution pgtype.Text
	ResolvedBy pgtype.Int8
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	ResolvedAt pgtype.Timestamptz
}

type Session struct {
	ID            int64
	TokenHash     []byte
	UserID        int64
	IssuedAt      pgtype.Timestamptz
	LastSeenAt    pgtype.Timestamptz
	ValidatedAt   pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
	RevokedAt     pgtype.Timestamptz
	UserAgentHash []byte
	IpPrefix      *netip.Addr
}

type Topic struct {
	ID             int64
	AreaID         int64
	AuthorID       int64
	Title          string
	Slug           pgtype.Text
	State          string
	PinnedAt       pgtype.Timestamptz
	FirstPostID    int64
	LatestPostID   int64
	ReplyCount     int32
	NextPostNumber int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	LastActivityAt pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type TopicRead struct {
	UserID             int64
	TopicID            int64
	LastReadPostNumber int32
	ReadAt             pgtype.Timestamptz
}

type User struct {
	ID               int64
	DisplayName      string
	Email            pgtype.Text
	AvatarUrl        pgtype.Text
	Bio              string
	Role             string
	SuspendedAt      pgtype.Timestamptz
	SuspendedUntil   pgtype.Timestamptz
	SuspensionReason pgtype.Text
	MutedUntil       pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	LastLoginAt      pgtype.Timestamptz
}
