// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: moderation_completion.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const changePostVisibilityAndAudit = `-- name: ChangePostVisibilityAndAudit :one
WITH changed AS (
    UPDATE public.posts AS post
    SET deleted_at = $1,
        deleted_by = $2,
        deletion_reason = $3,
        updated_at = GREATEST($4::timestamptz, post.updated_at)
    WHERE post.id = $5
      AND post.redacted_at IS NULL
      AND post.deleted_at IS NOT DISTINCT FROM $6::timestamptz
    RETURNING post.id, post.topic_id, post.deleted_at, post.deleted_by, post.updated_at
), audit AS (
    INSERT INTO public.moderation_actions (
        actor_kind, actor_user_id, target_type, target_post_id, action_type,
        reason, previous_state, resulting_state, request_id, created_at
    )
    SELECT 'forum_user', $7, 'post', changed.id,
           $8, $9,
           jsonb_build_object('deleted_at', $6::timestamptz,
                              'deleted_by', $10::bigint),
           jsonb_build_object('deleted_at', changed.deleted_at, 'deleted_by', changed.deleted_by),
           $11, changed.updated_at
    FROM changed RETURNING id, target_post_id
)
SELECT changed.id AS post_id, changed.topic_id, changed.deleted_at,
       changed.deleted_by, changed.updated_at, audit.id AS audit_id
FROM changed JOIN audit ON audit.target_post_id = changed.id
`

type ChangePostVisibilityAndAuditParams struct {
	ResultingDeletedAt pgtype.Timestamptz
	ResultingDeletedBy pgtype.Int8
	ResultingReason    pgtype.Text
	AtTime             pgtype.Timestamptz
	PostID             int64
	PreviousDeletedAt  pgtype.Timestamptz
	ActorUserID        pgtype.Int8
	ActionType         string
	AuditReason        pgtype.Text
	PreviousDeletedBy  pgtype.Int8
	RequestID          pgtype.UUID
}

type ChangePostVisibilityAndAuditRow struct {
	PostID    int64
	TopicID   int64
	DeletedAt pgtype.Timestamptz
	DeletedBy pgtype.Int8
	UpdatedAt pgtype.Timestamptz
	AuditID   int64
}

func (q *Queries) ChangePostVisibilityAndAudit(ctx context.Context, arg ChangePostVisibilityAndAuditParams) (ChangePostVisibilityAndAuditRow, error) {
	row := q.db.QueryRow(ctx, changePostVisibilityAndAudit,
		arg.ResultingDeletedAt,
		arg.ResultingDeletedBy,
		arg.ResultingReason,
		arg.AtTime,
		arg.PostID,
		arg.PreviousDeletedAt,
		arg.ActorUserID,
		arg.ActionType,
		arg.AuditReason,
		arg.PreviousDeletedBy,
		arg.RequestID,
	)
	var i ChangePostVisibilityAndAuditRow
	err := row.Scan(
		&i.PostID,
		&i.TopicID,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.UpdatedAt,
		&i.AuditID,
	)
	return i, err
}

const changeTopicPinAndAudit = `-- name: ChangeTopicPinAndAudit :one
WITH changed AS (
    UPDATE public.topics AS topic
    SET pinned_at = $1,
        updated_at = GREATEST($2::timestamptz, topic.updated_at)
    WHERE topic.id = $3
      AND topic.pinned_at IS NOT DISTINCT FROM $4::timestamptz
    RETURNING topic.id, topic.pinned_at, topic.updated_at
), audit AS (
    INSERT INTO public.moderation_actions (
        actor_kind, actor_user_id, target_type, target_topic_id, action_type,
        reason, previous_state, resulting_state, request_id, created_at
    )
    SELECT 'forum_user', $5, 'topic', changed.id,
           $6, $7,
           jsonb_build_object('pinned_at', $4::timestamptz),
           jsonb_build_object('pinned_at', changed.pinned_at),
           $8, changed.updated_at
    FROM changed RETURNING id, target_topic_id
)
SELECT changed.id AS topic_id, changed.pinned_at, changed.updated_at, audit.id AS audit_id
FROM changed JOIN audit ON audit.target_topic_id = changed.id
`

type ChangeTopicPinAndAuditParams struct {
	ResultingPinnedAt pgtype.Timestamptz
	AtTime            pgtype.Timestamptz
	TopicID           int64
	PreviousPinnedAt  pgtype.Timestamptz
	ActorUserID       pgtype.Int8
	ActionType        string
	Reason            pgtype.Text
	RequestID         pgtype.UUID
}

type ChangeTopicPinAndAuditRow struct {
	TopicID   int64
	PinnedAt  pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	AuditID   int64
}

func (q *Queries) ChangeTopicPinAndAudit(ctx context.Context, arg ChangeTopicPinAndAuditParams) (ChangeTopicPinAndAuditRow, error) {
	row := q.db.QueryRow(ctx, changeTopicPinAndAudit,
		arg.ResultingPinnedAt,
		arg.AtTime,
		arg.TopicID,
		arg.PreviousPinnedAt,
		arg.ActorUserID,
		arg.ActionType,
		arg.Reason,
		arg.RequestID,
	)
	var i ChangeTopicPinAndAuditRow
	err := row.Scan(
		&i.TopicID,
		&i.PinnedAt,
		&i.UpdatedAt,
		&i.AuditID,
	)
	return i, err
}

const getDestinationAreaBySlug = `-- name: GetDestinationAreaBySlug :one
SELECT area.id, area.slug, area.name, area.posting_mode
FROM public.areas AS area
WHERE area.slug = $1
`

type GetDestinationAreaBySlugRow struct {
	ID          int64
	Slug        string
	Name        string
	PostingMode string
}

func (q *Queries) GetDestinationAreaBySlug(ctx context.Context, areaSlug string) (GetDestinationAreaBySlugRow, error) {
	row := q.db.QueryRow(ctx, getDestinationAreaBySlug, areaSlug)
	var i GetDestinationAreaBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.PostingMode,
	)
	return i, err
}

const lockAreaForTopicMove = `-- name: LockAreaForTopicMove :one
SELECT area.id, area.slug, area.name, area.posting_mode
FROM public.areas AS area
WHERE area.id = $1
FOR UPDATE OF area
`

type LockAreaForTopicMoveRow struct {
	ID          int64
	Slug        string
	Name        string
	PostingMode string
}

func (q *Queries) LockAreaForTopicMove(ctx context.Context, areaID int64) (LockAreaForTopicMoveRow, error) {
	row := q.db.QueryRow(ctx, lockAreaForTopicMove, areaID)
	var i LockAreaForTopicMoveRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.PostingMode,
	)
	return i, err
}

const lockPostForModeration = `-- name: LockPostForModeration :one
SELECT post.id, post.topic_id, post.author_id, post.revision, post.deleted_at,
       post.deleted_by, post.deletion_reason, post.redacted_at, post.redacted_by,
       post.redaction_reason, post.created_at, post.updated_at,
       (
           SELECT count(*)
           FROM public.posts AS ranked_post
           WHERE ranked_post.topic_id = post.topic_id
             AND ranked_post.thread_path <= post.thread_path
       )::bigint AS node_ordinal
FROM public.posts AS post
JOIN public.topics AS topic ON topic.id = post.topic_id
WHERE post.id = $1 AND topic.deleted_at IS NULL
FOR UPDATE OF post
`

type LockPostForModerationRow struct {
	ID              int64
	TopicID         int64
	AuthorID        int64
	Revision        int32
	DeletedAt       pgtype.Timestamptz
	DeletedBy       pgtype.Int8
	DeletionReason  pgtype.Text
	RedactedAt      pgtype.Timestamptz
	RedactedBy      pgtype.Int8
	RedactionReason pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	NodeOrdinal     int64
}

func (q *Queries) LockPostForModeration(ctx context.Context, postID int64) (LockPostForModerationRow, error) {
	row := q.db.QueryRow(ctx, lockPostForModeration, postID)
	var i LockPostForModerationRow
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.AuthorID,
		&i.Revision,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeletionReason,
		&i.RedactedAt,
		&i.RedactedBy,
		&i.RedactionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NodeOrdinal,
	)
	return i, err
}

const lockTopicForExtendedModeration = `-- name: LockTopicForExtendedModeration :one
SELECT topic.id, topic.area_id, topic.state, topic.pinned_at, topic.created_at, topic.updated_at
FROM public.topics AS topic
WHERE topic.id = $1 AND topic.deleted_at IS NULL
FOR UPDATE OF topic
`

type LockTopicForExtendedModerationRow struct {
	ID        int64
	AreaID    int64
	State     string
	PinnedAt  pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) LockTopicForExtendedModeration(ctx context.Context, topicID int64) (LockTopicForExtendedModerationRow, error) {
	row := q.db.QueryRow(ctx, lockTopicForExtendedModeration, topicID)
	var i LockTopicForExtendedModerationRow
	err := row.Scan(
		&i.ID,
		&i.AreaID,
		&i.State,
		&i.PinnedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const moveTopicAndAudit = `-- name: MoveTopicAndAudit :one
WITH changed AS (
    UPDATE public.topics AS topic
    SET area_id = $1,
        slug = NULL,
        updated_at = GREATEST($2::timestamptz, topic.updated_at)
    WHERE topic.id = $3 AND topic.area_id = $4
    RETURNING topic.id, topic.area_id, topic.updated_at
), audit AS (
    INSERT INTO public.moderation_actions (
        actor_kind, actor_user_id, target_type, target_topic_id, action_type,
        reason, previous_state, resulting_state, request_id, created_at
    )
    SELECT 'forum_user', $5, 'topic', changed.id, 'move_topic',
           $6, jsonb_build_object('area_id', $4::bigint),
           jsonb_build_object('area_id', changed.area_id), $7, changed.updated_at
    FROM changed RETURNING id, target_topic_id
)
SELECT changed.id AS topic_id, changed.area_id, changed.updated_at, audit.id AS audit_id
FROM changed JOIN audit ON audit.target_topic_id = changed.id
`

type MoveTopicAndAuditParams struct {
	ResultingAreaID int64
	AtTime          pgtype.Timestamptz
	TopicID         int64
	PreviousAreaID  int64
	ActorUserID     pgtype.Int8
	Reason          pgtype.Text
	RequestID       pgtype.UUID
}

type MoveTopicAndAuditRow struct {
	TopicID   int64
	AreaID    int64
	UpdatedAt pgtype.Timestamptz
	AuditID   int64
}

func (q *Queries) MoveTopicAndAudit(ctx context.Context, arg MoveTopicAndAuditParams) (MoveTopicAndAuditRow, error) {
	row := q.db.QueryRow(ctx, moveTopicAndAudit,
		arg.ResultingAreaID,
		arg.AtTime,
		arg.TopicID,
		arg.PreviousAreaID,
		arg.ActorUserID,
		arg.Reason,
		arg.RequestID,
	)
	var i MoveTopicAndAuditRow
	err := row.Scan(
		&i.TopicID,
		&i.AreaID,
		&i.UpdatedAt,
		&i.AuditID,
	)
	return i, err
}

const muteUserAndAudit = `-- name: MuteUserAndAudit :one
WITH changed AS (
    UPDATE public.users AS target
    SET muted_until = $1,
        updated_at = GREATEST($2::timestamptz, target.updated_at)
    WHERE target.id = $3
      AND (target.muted_until IS NULL OR target.muted_until <= $4::timestamptz)
    RETURNING target.id, target.muted_until, target.updated_at
), audit AS (
    INSERT INTO public.moderation_actions (
        actor_kind, actor_user_id, target_type, target_user_id, action_type,
        reason, previous_state, resulting_state, request_id, created_at
    )
    SELECT 'forum_user', $5, 'user', changed.id, 'mute_user',
           $6, jsonb_build_object('muted_until', $7::timestamptz),
           jsonb_build_object('muted_until', changed.muted_until),
           $8, changed.updated_at
    FROM changed RETURNING id, target_user_id
)
SELECT changed.id AS user_id, changed.muted_until, changed.updated_at, audit.id AS audit_id
FROM changed JOIN audit ON audit.target_user_id = changed.id
`

type MuteUserAndAuditParams struct {
	MutedUntil         pgtype.Timestamptz
	AtTime             pgtype.Timestamptz
	UserID             int64
	ObservedAt         pgtype.Timestamptz
	ActorUserID        pgtype.Int8
	Reason             pgtype.Text
	PreviousMutedUntil pgtype.Timestamptz
	RequestID          pgtype.UUID
}

type MuteUserAndAuditRow struct {
	UserID     int64
	MutedUntil pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	AuditID    int64
}

func (q *Queries) MuteUserAndAudit(ctx context.Context, arg MuteUserAndAuditParams) (MuteUserAndAuditRow, error) {
	row := q.db.QueryRow(ctx, muteUserAndAudit,
		arg.MutedUntil,
		arg.AtTime,
		arg.UserID,
		arg.ObservedAt,
		arg.ActorUserID,
		arg.Reason,
		arg.PreviousMutedUntil,
		arg.RequestID,
	)
	var i MuteUserAndAuditRow
	err := row.Scan(
		&i.UserID,
		&i.MutedUntil,
		&i.UpdatedAt,
		&i.AuditID,
	)
	return i, err
}

const redactPostAndAudit = `-- name: RedactPostAndAudit :one
WITH changed AS (
    UPDATE public.posts AS post
    SET markdown_source = '[Content removed by moderation]',
        rendered_html = '<p>Content removed by moderation.</p>',
        renderer_version = 'moderation-redaction-v1',
        search_vector = to_tsvector('pg_catalog.simple'::regconfig, ''),
        search_projection_version = 'search-v1-pg17-simple-u15-p2',
        revision = post.revision + 1,
        edited_at = GREATEST($1::timestamptz, post.updated_at),
        deleted_at = GREATEST($1::timestamptz, post.updated_at),
        deleted_by = $2, deletion_reason = $3,
        redacted_at = GREATEST($1::timestamptz, post.updated_at),
        redacted_by = $2, redaction_reason = $3,
        updated_at = GREATEST($1::timestamptz, post.updated_at)
    WHERE post.id = $4 AND post.deleted_at IS NULL AND post.redacted_at IS NULL
    RETURNING post.id, post.topic_id, post.revision, post.redacted_at, post.redacted_by, post.updated_at
), audit AS (
    INSERT INTO public.moderation_actions (
        actor_kind, actor_user_id, target_type, target_post_id, action_type,
        reason, previous_state, resulting_state, request_id, created_at
    )
    SELECT 'forum_user', $2, 'post', changed.id, 'redact_post',
           $3, jsonb_build_object('revision', $5::integer, 'redacted', false),
           jsonb_build_object('revision', changed.revision, 'redacted', true),
           $6, changed.updated_at
    FROM changed RETURNING id, target_post_id
)
SELECT changed.id AS post_id, changed.topic_id, changed.revision, changed.redacted_at,
       changed.redacted_by, changed.updated_at, audit.id AS audit_id
FROM changed JOIN audit ON audit.target_post_id = changed.id
`

type RedactPostAndAuditParams struct {
	AtTime           pgtype.Timestamptz
	ActorUserID      pgtype.Int8
	Reason           pgtype.Text
	PostID           int64
	PreviousRevision int32
	RequestID        pgtype.UUID
}

type RedactPostAndAuditRow struct {
	PostID     int64
	TopicID    int64
	Revision   int32
	RedactedAt pgtype.Timestamptz
	RedactedBy pgtype.Int8
	UpdatedAt  pgtype.Timestamptz
	AuditID    int64
}

func (q *Queries) RedactPostAndAudit(ctx context.Context, arg RedactPostAndAuditParams) (RedactPostAndAuditRow, error) {
	row := q.db.QueryRow(ctx, redactPostAndAudit,
		arg.AtTime,
		arg.ActorUserID,
		arg.Reason,
		arg.PostID,
		arg.PreviousRevision,
		arg.RequestID,
	)
	var i RedactPostAndAuditRow
	err := row.Scan(
		&i.PostID,
		&i.TopicID,
		&i.Revision,
		&i.RedactedAt,
		&i.RedactedBy,
		&i.UpdatedAt,
		&i.AuditID,
	)
	return i, err
}

const warnUserAndAudit = `-- name: WarnUserAndAudit :one
WITH warned AS (
    INSERT INTO public.user_warnings (user_id, warned_by, reason, created_at)
    VALUES ($1, $2, $3, $4)
    RETURNING id, user_id, warned_by, created_at
), audit AS (
    INSERT INTO public.moderation_actions (
        actor_kind, actor_user_id, target_type, target_user_id, action_type,
        reason, previous_state, resulting_state, request_id, created_at
    )
    SELECT 'forum_user', warned.warned_by, 'user', warned.user_id, 'warn_user',
           $3, '{}'::jsonb, jsonb_build_object('warning_id', warned.id),
           $5, warned.created_at
    FROM warned RETURNING id, target_user_id
)
SELECT warned.id AS warning_id, warned.user_id, warned.created_at, audit.id AS audit_id
FROM warned JOIN audit ON audit.target_user_id = warned.user_id
`

type WarnUserAndAuditParams struct {
	UserID      int64
	ActorUserID int64
	Reason      string
	AtTime      pgtype.Timestamptz
	RequestID   pgtype.UUID
}

type WarnUserAndAuditRow struct {
	WarningID int64
	UserID    int64
	CreatedAt pgtype.Timestamptz
	AuditID   int64
}

func (q *Queries) WarnUserAndAudit(ctx context.Context, arg WarnUserAndAuditParams) (WarnUserAndAuditRow, error) {
	row := q.db.QueryRow(ctx, warnUserAndAudit,
		arg.UserID,
		arg.ActorUserID,
		arg.Reason,
		arg.AtTime,
		arg.RequestID,
	)
	var i WarnUserAndAuditRow
	err := row.Scan(
		&i.WarningID,
		&i.UserID,
		&i.CreatedAt,
		&i.AuditID,
	)
	return i, err
}
