// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: publishing.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const configurePublicationTransaction = `-- name: ConfigurePublicationTransaction :exec
SELECT
    set_config('statement_timeout', '2000ms', true),
    set_config('lock_timeout', '250ms', true)
`

func (q *Queries) ConfigurePublicationTransaction(ctx context.Context) error {
	_, err := q.db.Exec(ctx, configurePublicationTransaction)
	return err
}

const createReplyAndAdvanceTopic = `-- name: CreateReplyAndAdvanceTopic :one
WITH inserted_post AS (
    INSERT INTO public.posts (
        topic_id, author_id, post_number, markdown_source, rendered_html,
        renderer_version, revision, parent_post_id, created_at, updated_at,
        search_vector, search_projection_version
    )
    SELECT
        topic.id,
        $1,
        topic.next_post_number,
        $2,
        $3,
        $4,
        1,
        $5,
        GREATEST($6::timestamptz, topic.last_activity_at),
        GREATEST($6::timestamptz, topic.last_activity_at),
        to_tsvector('pg_catalog.simple'::regconfig, $7::text),
        $8
    FROM public.topics AS topic
    WHERE topic.id = $9
    RETURNING id, topic_id, post_number, thread_path, created_at AS post_created_at
),
advanced_topic AS (
    UPDATE public.topics AS topic
    SET latest_post_id = inserted_post.id,
        reply_count = inserted_post.post_number - 1,
        next_post_number = inserted_post.post_number + 1,
        updated_at = inserted_post.post_created_at,
        last_activity_at = inserted_post.post_created_at
    FROM inserted_post
    WHERE topic.id = inserted_post.topic_id
    RETURNING topic.id AS topic_id, inserted_post.id AS post_id, inserted_post.post_number, inserted_post.thread_path
)
SELECT
    advanced_topic.topic_id,
    advanced_topic.post_id,
    advanced_topic.post_number,
    (1::bigint + (
        SELECT count(*)::bigint
        FROM public.posts AS node
        WHERE node.topic_id = advanced_topic.topic_id
          AND node.thread_path <= advanced_topic.thread_path
          AND (
            node.deleted_at IS NULL
            OR EXISTS (
                SELECT 1
                FROM public.posts AS descendant
                WHERE descendant.topic_id = node.topic_id
                  AND descendant.deleted_at IS NULL
                  AND descendant.thread_path[1:cardinality(node.thread_path)] = node.thread_path
                  AND cardinality(descendant.thread_path) > cardinality(node.thread_path)
            )
          )
    ))::bigint AS node_ordinal
FROM advanced_topic
`

type CreateReplyAndAdvanceTopicParams struct {
	AuthorID                int64
	MarkdownSource          string
	RenderedHtml            string
	RendererVersion         string
	ParentPostID            pgtype.Int8
	AtTime                  pgtype.Timestamptz
	PostSearchText          string
	SearchProjectionVersion pgtype.Text
	TopicID                 int64
}

type CreateReplyAndAdvanceTopicRow struct {
	TopicID     int64
	PostID      int64
	PostNumber  int32
	NodeOrdinal int64
}

func (q *Queries) CreateReplyAndAdvanceTopic(ctx context.Context, arg CreateReplyAndAdvanceTopicParams) (CreateReplyAndAdvanceTopicRow, error) {
	row := q.db.QueryRow(ctx, createReplyAndAdvanceTopic,
		arg.AuthorID,
		arg.MarkdownSource,
		arg.RenderedHtml,
		arg.RendererVersion,
		arg.ParentPostID,
		arg.AtTime,
		arg.PostSearchText,
		arg.SearchProjectionVersion,
		arg.TopicID,
	)
	var i CreateReplyAndAdvanceTopicRow
	err := row.Scan(
		&i.TopicID,
		&i.PostID,
		&i.PostNumber,
		&i.NodeOrdinal,
	)
	return i, err
}

const createTopicAndFirstPost = `-- name: CreateTopicAndFirstPost :one
WITH identifiers AS (
    SELECT
        nextval(pg_get_serial_sequence('public.topics', 'id'))::bigint AS topic_id,
        nextval(pg_get_serial_sequence('public.posts', 'id'))::bigint AS post_id
),
inserted_topic AS (
    INSERT INTO public.topics (
        id, area_id, author_id, title, state, first_post_id, latest_post_id,
        reply_count, next_post_number, created_at, updated_at, last_activity_at,
        search_vector, search_projection_version
    )
    SELECT
        identifiers.topic_id,
        $1,
        $2,
        $3,
        'open',
        identifiers.post_id,
        identifiers.post_id,
        0,
        2,
        $4,
        $4,
        $4,
        to_tsvector('pg_catalog.simple'::regconfig, $5::text),
        $6
    FROM identifiers
    RETURNING id
),
inserted_post AS (
    INSERT INTO public.posts (
        id, topic_id, author_id, post_number, markdown_source, rendered_html,
        renderer_version, revision, parent_post_id, thread_path, created_at, updated_at,
        search_vector, search_projection_version
    )
    SELECT
        identifiers.post_id,
        inserted_topic.id,
        $2,
        1,
        $7,
        $8,
        $9,
        1,
        NULL,
        ARRAY[1]::integer[],
        $4,
        $4,
        to_tsvector('pg_catalog.simple'::regconfig, $10::text),
        $6
    FROM identifiers
    JOIN inserted_topic ON inserted_topic.id = identifiers.topic_id
    RETURNING id, topic_id, post_number
)
SELECT topic_id, id AS post_id, post_number, 1::bigint AS node_ordinal
FROM inserted_post
`

type CreateTopicAndFirstPostParams struct {
	AreaID                  int64
	AuthorID                int64
	Title                   string
	AtTime                  pgtype.Timestamptz
	TopicSearchText         string
	SearchProjectionVersion pgtype.Text
	MarkdownSource          string
	RenderedHtml            string
	RendererVersion         string
	PostSearchText          string
}

type CreateTopicAndFirstPostRow struct {
	TopicID     int64
	PostID      int64
	PostNumber  int32
	NodeOrdinal int64
}

func (q *Queries) CreateTopicAndFirstPost(ctx context.Context, arg CreateTopicAndFirstPostParams) (CreateTopicAndFirstPostRow, error) {
	row := q.db.QueryRow(ctx, createTopicAndFirstPost,
		arg.AreaID,
		arg.AuthorID,
		arg.Title,
		arg.AtTime,
		arg.TopicSearchText,
		arg.SearchProjectionVersion,
		arg.MarkdownSource,
		arg.RenderedHtml,
		arg.RendererVersion,
		arg.PostSearchText,
	)
	var i CreateTopicAndFirstPostRow
	err := row.Scan(
		&i.TopicID,
		&i.PostID,
		&i.PostNumber,
		&i.NodeOrdinal,
	)
	return i, err
}

const listLockedPublicationActorGroupIDs = `-- name: ListLockedPublicationActorGroupIDs :many
SELECT membership.group_id
FROM public.forum_group_members AS membership
WHERE membership.user_id = $1
ORDER BY membership.group_id
`

func (q *Queries) ListLockedPublicationActorGroupIDs(ctx context.Context, actorUserID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listLockedPublicationActorGroupIDs, actorUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var group_id int64
		if err := rows.Scan(&group_id); err != nil {
			return nil, err
		}
		items = append(items, group_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAreaForTopicCreation = `-- name: LockAreaForTopicCreation :one
SELECT
    area.id,
    area.visibility,
    area.posting_mode
FROM public.areas AS area
WHERE area.slug = $1
FOR SHARE OF area
`

type LockAreaForTopicCreationRow struct {
	ID          int64
	Visibility  string
	PostingMode string
}

func (q *Queries) LockAreaForTopicCreation(ctx context.Context, areaSlug string) (LockAreaForTopicCreationRow, error) {
	row := q.db.QueryRow(ctx, lockAreaForTopicCreation, areaSlug)
	var i LockAreaForTopicCreationRow
	err := row.Scan(&i.ID, &i.Visibility, &i.PostingMode)
	return i, err
}

const lockAreaGroupIDs = `-- name: LockAreaGroupIDs :many
SELECT mapping.group_id
FROM public.area_groups AS mapping
WHERE mapping.area_id = $1
ORDER BY mapping.group_id
FOR SHARE OF mapping
`

func (q *Queries) LockAreaGroupIDs(ctx context.Context, areaID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, lockAreaGroupIDs, areaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var group_id int64
		if err := rows.Scan(&group_id); err != nil {
			return nil, err
		}
		items = append(items, group_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPublicationActor = `-- name: LockPublicationActor :one
SELECT
    forum_user.id,
    forum_user.role,
    forum_user.suspended_at,
    forum_user.suspended_until,
    forum_user.muted_until,
    forum_user.created_at,
    forum_user.publication_window_started_at,
    forum_user.publication_count,
    clock_timestamp()::timestamp with time zone AS observed_at
FROM public.users AS forum_user
WHERE forum_user.id = $1
FOR UPDATE OF forum_user
`

type LockPublicationActorRow struct {
	ID                         int64
	Role                       string
	SuspendedAt                pgtype.Timestamptz
	SuspendedUntil             pgtype.Timestamptz
	MutedUntil                 pgtype.Timestamptz
	CreatedAt                  pgtype.Timestamptz
	PublicationWindowStartedAt pgtype.Timestamptz
	PublicationCount           int32
	ObservedAt                 pgtype.Timestamptz
}

func (q *Queries) LockPublicationActor(ctx context.Context, actorUserID int64) (LockPublicationActorRow, error) {
	row := q.db.QueryRow(ctx, lockPublicationActor, actorUserID)
	var i LockPublicationActorRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.SuspendedAt,
		&i.SuspendedUntil,
		&i.MutedUntil,
		&i.CreatedAt,
		&i.PublicationWindowStartedAt,
		&i.PublicationCount,
		&i.ObservedAt,
	)
	return i, err
}

const lockTopicForReply = `-- name: LockTopicForReply :one
SELECT
    topic.id AS topic_id,
    topic.state AS topic_state,
    area.id AS area_id,
    area.visibility,
    area.posting_mode,
    parent.id AS parent_post_id,
    cardinality(parent.thread_path)::integer AS parent_depth
FROM public.topics AS topic
JOIN public.areas AS area ON area.id = topic.area_id
JOIN public.posts AS parent
  ON parent.topic_id = topic.id
 AND parent.id = $1
 AND parent.deleted_at IS NULL
WHERE topic.id = $2
  AND topic.deleted_at IS NULL
FOR UPDATE OF topic
FOR SHARE OF area, parent
`

type LockTopicForReplyParams struct {
	ParentPostID int64
	TopicID      int64
}

type LockTopicForReplyRow struct {
	TopicID      int64
	TopicState   string
	AreaID       int64
	Visibility   string
	PostingMode  string
	ParentPostID int64
	ParentDepth  int32
}

func (q *Queries) LockTopicForReply(ctx context.Context, arg LockTopicForReplyParams) (LockTopicForReplyRow, error) {
	row := q.db.QueryRow(ctx, lockTopicForReply, arg.ParentPostID, arg.TopicID)
	var i LockTopicForReplyRow
	err := row.Scan(
		&i.TopicID,
		&i.TopicState,
		&i.AreaID,
		&i.Visibility,
		&i.PostingMode,
		&i.ParentPostID,
		&i.ParentDepth,
	)
	return i, err
}

const publicationDatabaseTime = `-- name: PublicationDatabaseTime :one
SELECT clock_timestamp()::timestamp with time zone AS database_now
`

func (q *Queries) PublicationDatabaseTime(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, publicationDatabaseTime)
	var database_now pgtype.Timestamptz
	err := row.Scan(&database_now)
	return database_now, err
}

const replacePublicationWindow = `-- name: ReplacePublicationWindow :one
UPDATE public.users AS forum_user
SET publication_window_started_at = $1,
    publication_count = $2
WHERE forum_user.id = $3
RETURNING forum_user.publication_window_started_at, forum_user.publication_count
`

type ReplacePublicationWindowParams struct {
	WindowStartedAt  pgtype.Timestamptz
	PublicationCount int32
	ActorUserID      int64
}

type ReplacePublicationWindowRow struct {
	PublicationWindowStartedAt pgtype.Timestamptz
	PublicationCount           int32
}

func (q *Queries) ReplacePublicationWindow(ctx context.Context, arg ReplacePublicationWindowParams) (ReplacePublicationWindowRow, error) {
	row := q.db.QueryRow(ctx, replacePublicationWindow, arg.WindowStartedAt, arg.PublicationCount, arg.ActorUserID)
	var i ReplacePublicationWindowRow
	err := row.Scan(&i.PublicationWindowStartedAt, &i.PublicationCount)
	return i, err
}
