// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registration.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const beginPendingRegistrationDecision = `-- name: BeginPendingRegistrationDecision :one
WITH changed AS (
    UPDATE public.pending_registrations AS registration
    SET status = $1,
        administration_revision = registration.administration_revision + 1,
        transition_request_id = $2,
        reconciliation_class = NULL
    WHERE registration.id = $3
      AND registration.status = 'pending'
      AND registration.administration_revision = $4
      AND registration.administration_revision < 9223372036854775807
    RETURNING registration.id, registration.status,
              registration.administration_revision
), audit AS (
    INSERT INTO public.moderation_actions (
        actor_kind, actor_user_id, target_type, target_site, action_type,
        reason, previous_state, resulting_state, request_id, created_at
    )
    SELECT 'forum_user', $5, 'site', true,
           $6, $7,
           pg_catalog.jsonb_build_object(
               'registration_ref', $8::text,
               'status', 'pending'::text,
               'administration_revision', $4::bigint
           ),
           pg_catalog.jsonb_build_object(
               'registration_ref', $8::text,
               'status', changed.status,
               'administration_revision', changed.administration_revision
           ),
           $2, $9::timestamptz
    FROM changed
    RETURNING id
)
SELECT changed.status, changed.administration_revision, audit.id AS audit_id
FROM changed
JOIN audit ON true
`

type BeginPendingRegistrationDecisionParams struct {
	RequiredStatus   string
	RequestID        pgtype.UUID
	RegistrationID   int64
	ExpectedRevision int64
	ActorUserID      pgtype.Int8
	ActionType       string
	Reason           pgtype.Text
	RegistrationRef  string
	ObservedAt       pgtype.Timestamptz
}

type BeginPendingRegistrationDecisionRow struct {
	Status                 string
	AdministrationRevision int64
	AuditID                int64
}

func (q *Queries) BeginPendingRegistrationDecision(ctx context.Context, arg BeginPendingRegistrationDecisionParams) (BeginPendingRegistrationDecisionRow, error) {
	row := q.db.QueryRow(ctx, beginPendingRegistrationDecision,
		arg.RequiredStatus,
		arg.RequestID,
		arg.RegistrationID,
		arg.ExpectedRevision,
		arg.ActorUserID,
		arg.ActionType,
		arg.Reason,
		arg.RegistrationRef,
		arg.ObservedAt,
	)
	var i BeginPendingRegistrationDecisionRow
	err := row.Scan(&i.Status, &i.AdministrationRevision, &i.AuditID)
	return i, err
}

const completePendingRegistrationDecision = `-- name: CompletePendingRegistrationDecision :one
WITH changed AS (
    UPDATE public.pending_registrations AS registration
    SET status = $1,
        administration_revision = registration.administration_revision + 1,
        decided_at = $2,
        deciding_administrator_id = $3,
        reconciliation_class = NULL
    WHERE registration.id = $4
      AND registration.status = $5
      AND registration.transition_request_id = $6
      AND registration.administration_revision = $7
      AND registration.administration_revision < 9223372036854775807
    RETURNING registration.id, registration.status,
              registration.administration_revision
), audit AS (
    INSERT INTO public.moderation_actions (
        actor_kind, actor_user_id, target_type, target_site, action_type,
        reason, previous_state, resulting_state, request_id, created_at
    )
    SELECT 'forum_user', $3, 'site', true,
           $8, $9,
           pg_catalog.jsonb_build_object(
               'registration_ref', $10::text,
               'status', $5::text,
               'administration_revision', $7::bigint
           ),
           pg_catalog.jsonb_build_object(
               'registration_ref', $10::text,
               'status', changed.status,
               'administration_revision', changed.administration_revision,
               'result', 'confirmed'::text
           ),
           $6, $2::timestamptz
    FROM changed
    RETURNING id
)
SELECT changed.status, changed.administration_revision, audit.id AS audit_id
FROM changed
JOIN audit ON true
`

type CompletePendingRegistrationDecisionParams struct {
	ResultingStatus  string
	ObservedAt       pgtype.Timestamptz
	ActorUserID      pgtype.Int8
	RegistrationID   int64
	RequiredStatus   string
	RequestID        pgtype.UUID
	ExpectedRevision int64
	ActionType       string
	Reason           pgtype.Text
	RegistrationRef  string
}

type CompletePendingRegistrationDecisionRow struct {
	Status                 string
	AdministrationRevision int64
	AuditID                int64
}

func (q *Queries) CompletePendingRegistrationDecision(ctx context.Context, arg CompletePendingRegistrationDecisionParams) (CompletePendingRegistrationDecisionRow, error) {
	row := q.db.QueryRow(ctx, completePendingRegistrationDecision,
		arg.ResultingStatus,
		arg.ObservedAt,
		arg.ActorUserID,
		arg.RegistrationID,
		arg.RequiredStatus,
		arg.RequestID,
		arg.ExpectedRevision,
		arg.ActionType,
		arg.Reason,
		arg.RegistrationRef,
	)
	var i CompletePendingRegistrationDecisionRow
	err := row.Scan(&i.Status, &i.AdministrationRevision, &i.AuditID)
	return i, err
}

const insertOrLoadPendingRegistrationAdoption = `-- name: InsertOrLoadPendingRegistrationAdoption :one
WITH inserted AS (
    INSERT INTO public.pending_registrations (
        authentik_user_id, authentik_subject, display_name, verified_email,
        status, administration_revision, intake_at
    ) VALUES (
        $1, $2,
        $3, $4,
        'pending', 1, $5
    )
    ON CONFLICT DO NOTHING
    RETURNING id, administration_revision, true AS inserted
), existing AS (
    SELECT pending.id, pending.administration_revision, false AS inserted
    FROM public.pending_registrations AS pending
    WHERE pending.authentik_user_id = $1
      AND pending.authentik_subject = $2
      AND pending.status = 'pending'
)
SELECT id, administration_revision, inserted FROM inserted
UNION ALL
SELECT id, administration_revision, inserted FROM existing
LIMIT 1
`

type InsertOrLoadPendingRegistrationAdoptionParams struct {
	AuthentikUserID  int64
	AuthentikSubject pgtype.UUID
	DisplayName      string
	VerifiedEmail    string
	IntakeAt         pgtype.Timestamptz
}

type InsertOrLoadPendingRegistrationAdoptionRow struct {
	ID                     int64
	AdministrationRevision int64
	Inserted               bool
}

func (q *Queries) InsertOrLoadPendingRegistrationAdoption(ctx context.Context, arg InsertOrLoadPendingRegistrationAdoptionParams) (InsertOrLoadPendingRegistrationAdoptionRow, error) {
	row := q.db.QueryRow(ctx, insertOrLoadPendingRegistrationAdoption,
		arg.AuthentikUserID,
		arg.AuthentikSubject,
		arg.DisplayName,
		arg.VerifiedEmail,
		arg.IntakeAt,
	)
	var i InsertOrLoadPendingRegistrationAdoptionRow
	err := row.Scan(&i.ID, &i.AdministrationRevision, &i.Inserted)
	return i, err
}

const listPendingRegistrationsForAdministration = `-- name: ListPendingRegistrationsForAdministration :many
WITH actor AS MATERIALIZED (
    SELECT forum_user.id
    FROM public.users AS forum_user
    WHERE forum_user.id = $1
      AND forum_user.role = 'administrator'
      AND forum_user.authentik_sync_state = 'accepted'
      AND (
          forum_user.suspended_at IS NULL
          OR forum_user.suspended_at > $2::timestamptz
          OR forum_user.suspended_until <= $2::timestamptz
      )
      AND (forum_user.muted_until IS NULL OR forum_user.muted_until <= $2::timestamptz)
), candidate AS MATERIALIZED (
    SELECT registration.id, registration.display_name,
           registration.verified_email, registration.status,
           registration.administration_revision, registration.intake_at,
           registration.reconciliation_class
    FROM actor
    JOIN LATERAL (
        SELECT pending.id, pending.display_name, pending.verified_email,
               pending.status, pending.administration_revision,
               pending.intake_at, pending.reconciliation_class
        FROM public.pending_registrations AS pending
        WHERE pending.status IN ('pending', 'approval_required', 'rejection_required')
          AND pending.id > $3
        ORDER BY pending.id
        LIMIT $4
    ) AS registration ON true
)
SELECT (candidate.id IS NOT NULL)::boolean AS registration_present,
       COALESCE(candidate.id, 0)::bigint AS id,
       COALESCE(candidate.display_name, '')::text AS display_name,
       COALESCE(candidate.verified_email, '')::text AS verified_email,
       COALESCE(candidate.status, '')::text AS status,
       COALESCE(candidate.administration_revision, 0)::bigint AS administration_revision,
       candidate.intake_at,
       candidate.reconciliation_class
FROM actor
LEFT JOIN candidate ON true
ORDER BY candidate.id NULLS LAST
`

type ListPendingRegistrationsForAdministrationParams struct {
	ActorUserID         int64
	ObservedAt          pgtype.Timestamptz
	AfterRegistrationID int64
	PageLimit           int32
}

type ListPendingRegistrationsForAdministrationRow struct {
	RegistrationPresent    bool
	ID                     int64
	DisplayName            string
	VerifiedEmail          string
	Status                 string
	AdministrationRevision int64
	IntakeAt               pgtype.Timestamptz
	ReconciliationClass    pgtype.Text
}

func (q *Queries) ListPendingRegistrationsForAdministration(ctx context.Context, arg ListPendingRegistrationsForAdministrationParams) ([]ListPendingRegistrationsForAdministrationRow, error) {
	rows, err := q.db.Query(ctx, listPendingRegistrationsForAdministration,
		arg.ActorUserID,
		arg.ObservedAt,
		arg.AfterRegistrationID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingRegistrationsForAdministrationRow{}
	for rows.Next() {
		var i ListPendingRegistrationsForAdministrationRow
		if err := rows.Scan(
			&i.RegistrationPresent,
			&i.ID,
			&i.DisplayName,
			&i.VerifiedEmail,
			&i.Status,
			&i.AdministrationRevision,
			&i.IntakeAt,
			&i.ReconciliationClass,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPendingRegistration = `-- name: LockPendingRegistration :one
SELECT id, authentik_user_id, authentik_subject, status,
       administration_revision, transition_request_id,
       reconciliation_class
FROM public.pending_registrations
WHERE id = $1
FOR UPDATE
`

type LockPendingRegistrationRow struct {
	ID                     int64
	AuthentikUserID        int64
	AuthentikSubject       pgtype.UUID
	Status                 string
	AdministrationRevision int64
	TransitionRequestID    pgtype.UUID
	ReconciliationClass    pgtype.Text
}

func (q *Queries) LockPendingRegistration(ctx context.Context, registrationID int64) (LockPendingRegistrationRow, error) {
	row := q.db.QueryRow(ctx, lockPendingRegistration, registrationID)
	var i LockPendingRegistrationRow
	err := row.Scan(
		&i.ID,
		&i.AuthentikUserID,
		&i.AuthentikSubject,
		&i.Status,
		&i.AdministrationRevision,
		&i.TransitionRequestID,
		&i.ReconciliationClass,
	)
	return i, err
}

const lockRegistrationAdministrator = `-- name: LockRegistrationAdministrator :one
SELECT forum_user.id
FROM public.users AS forum_user
WHERE forum_user.id = $1
  AND forum_user.role = 'administrator'
  AND forum_user.authentik_sync_state = 'accepted'
  AND (
      forum_user.suspended_at IS NULL
      OR forum_user.suspended_at > $2::timestamptz
      OR forum_user.suspended_until <= $2::timestamptz
  )
  AND (forum_user.muted_until IS NULL OR forum_user.muted_until <= $2::timestamptz)
FOR UPDATE OF forum_user
`

type LockRegistrationAdministratorParams struct {
	ActorUserID int64
	ObservedAt  pgtype.Timestamptz
}

func (q *Queries) LockRegistrationAdministrator(ctx context.Context, arg LockRegistrationAdministratorParams) (int64, error) {
	row := q.db.QueryRow(ctx, lockRegistrationAdministrator, arg.ActorUserID, arg.ObservedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const matchPendingRegistrationCoordinates = `-- name: MatchPendingRegistrationCoordinates :many
WITH actor AS MATERIALIZED (
    SELECT forum_user.id
    FROM public.users AS forum_user
    WHERE forum_user.id = $1
      AND forum_user.role = 'administrator'
      AND forum_user.authentik_sync_state = 'accepted'
      AND (
          forum_user.suspended_at IS NULL
          OR forum_user.suspended_at > $2::timestamptz
          OR forum_user.suspended_until <= $2::timestamptz
      )
      AND (forum_user.muted_until IS NULL OR forum_user.muted_until <= $2::timestamptz)
), candidate AS MATERIALIZED (
    SELECT pending.id, pending.authentik_user_id,
           pending.authentik_subject::text AS authentik_subject
    FROM actor
    CROSS JOIN public.pending_registrations AS pending
    WHERE pending.authentik_user_id = ANY($3::bigint[])
       OR pending.authentik_subject::text = ANY($4::text[])
    ORDER BY pending.id
    LIMIT 103
)
SELECT EXISTS (SELECT 1 FROM actor)::boolean AS actor_present,
       (candidate.id IS NOT NULL)::boolean AS registration_present,
       COALESCE(candidate.id, 0)::bigint AS id,
       COALESCE(candidate.authentik_user_id, 0)::bigint AS authentik_user_id,
       COALESCE(candidate.authentik_subject, '')::text AS authentik_subject
FROM (SELECT 1) AS seed
LEFT JOIN candidate ON true
ORDER BY candidate.id NULLS LAST
`

type MatchPendingRegistrationCoordinatesParams struct {
	ActorUserID       int64
	ObservedAt        pgtype.Timestamptz
	AuthentikUserIds  []int64
	AuthentikSubjects []string
}

type MatchPendingRegistrationCoordinatesRow struct {
	ActorPresent        bool
	RegistrationPresent bool
	ID                  int64
	AuthentikUserID     int64
	AuthentikSubject    string
}

func (q *Queries) MatchPendingRegistrationCoordinates(ctx context.Context, arg MatchPendingRegistrationCoordinatesParams) ([]MatchPendingRegistrationCoordinatesRow, error) {
	rows, err := q.db.Query(ctx, matchPendingRegistrationCoordinates,
		arg.ActorUserID,
		arg.ObservedAt,
		arg.AuthentikUserIds,
		arg.AuthentikSubjects,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MatchPendingRegistrationCoordinatesRow{}
	for rows.Next() {
		var i MatchPendingRegistrationCoordinatesRow
		if err := rows.Scan(
			&i.ActorPresent,
			&i.RegistrationPresent,
			&i.ID,
			&i.AuthentikUserID,
			&i.AuthentikSubject,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordPendingRegistrationAdoption = `-- name: RecordPendingRegistrationAdoption :one
INSERT INTO public.moderation_actions (
    actor_kind, actor_user_id, target_type, target_site, action_type,
    reason, previous_state, resulting_state, request_id, created_at
) VALUES (
    'forum_user', $1, 'site', true,
    'adopt_pending_registration', $2,
    pg_catalog.jsonb_build_object(
        'registration_ref', $3::text,
        'status', 'remote_pending_orphan'::text
    ),
    pg_catalog.jsonb_build_object(
        'registration_ref', $3::text,
        'status', 'pending'::text,
        'administration_revision', $4::bigint
    ),
    $5, $6::timestamptz
)
RETURNING id
`

type RecordPendingRegistrationAdoptionParams struct {
	ActorUserID            pgtype.Int8
	Reason                 pgtype.Text
	RegistrationRef        string
	AdministrationRevision int64
	RequestID              pgtype.UUID
	ObservedAt             pgtype.Timestamptz
}

func (q *Queries) RecordPendingRegistrationAdoption(ctx context.Context, arg RecordPendingRegistrationAdoptionParams) (int64, error) {
	row := q.db.QueryRow(ctx, recordPendingRegistrationAdoption,
		arg.ActorUserID,
		arg.Reason,
		arg.RegistrationRef,
		arg.AdministrationRevision,
		arg.RequestID,
		arg.ObservedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const recordPendingRegistrationDecisionFailure = `-- name: RecordPendingRegistrationDecisionFailure :one
WITH changed AS (
    UPDATE public.pending_registrations AS registration
    SET reconciliation_class = $1,
        administration_revision = registration.administration_revision + 1
    WHERE registration.id = $2
      AND registration.status = $3
      AND registration.transition_request_id = $4
      AND registration.administration_revision = $5
      AND registration.administration_revision < 9223372036854775807
    RETURNING registration.status, registration.administration_revision
), audit AS (
    INSERT INTO public.moderation_actions (
        actor_kind, actor_user_id, target_type, target_site, action_type,
        reason, previous_state, resulting_state, request_id, created_at
    )
    SELECT 'forum_user', $6, 'site', true,
           'record_registration_transition_result', $7,
           pg_catalog.jsonb_build_object(
               'registration_ref', $8::text,
               'status', $3::text,
               'administration_revision', $5::bigint
           ),
           pg_catalog.jsonb_build_object(
               'registration_ref', $8::text,
               'status', changed.status,
               'administration_revision', changed.administration_revision,
               'result', $1::text
           ),
           $4, $9::timestamptz
    FROM changed
    RETURNING id
)
SELECT changed.status, changed.administration_revision, audit.id AS audit_id
FROM changed
JOIN audit ON true
`

type RecordPendingRegistrationDecisionFailureParams struct {
	FailureClass     pgtype.Text
	RegistrationID   int64
	RequiredStatus   string
	RequestID        pgtype.UUID
	ExpectedRevision int64
	ActorUserID      pgtype.Int8
	Reason           pgtype.Text
	RegistrationRef  string
	ObservedAt       pgtype.Timestamptz
}

type RecordPendingRegistrationDecisionFailureRow struct {
	Status                 string
	AdministrationRevision int64
	AuditID                int64
}

func (q *Queries) RecordPendingRegistrationDecisionFailure(ctx context.Context, arg RecordPendingRegistrationDecisionFailureParams) (RecordPendingRegistrationDecisionFailureRow, error) {
	row := q.db.QueryRow(ctx, recordPendingRegistrationDecisionFailure,
		arg.FailureClass,
		arg.RegistrationID,
		arg.RequiredStatus,
		arg.RequestID,
		arg.ExpectedRevision,
		arg.ActorUserID,
		arg.Reason,
		arg.RegistrationRef,
		arg.ObservedAt,
	)
	var i RecordPendingRegistrationDecisionFailureRow
	err := row.Scan(&i.Status, &i.AdministrationRevision, &i.AuditID)
	return i, err
}

const upsertPendingRegistrationIntake = `-- name: UpsertPendingRegistrationIntake :one
WITH admitted AS (
    INSERT INTO public.pending_registrations (
        authentik_user_id, authentik_subject, display_name, verified_email,
        status, administration_revision, intake_at
    )
    VALUES (
        $2, $1,
        $3, $4,
        'pending', 1, $5
    )
    ON CONFLICT (authentik_subject) DO UPDATE
    SET display_name = EXCLUDED.display_name,
        verified_email = EXCLUDED.verified_email
    WHERE pending_registrations.authentik_user_id = EXCLUDED.authentik_user_id
      AND pending_registrations.status = 'pending'
    RETURNING true AS accepted
)
SELECT COALESCE(
    (SELECT accepted FROM admitted),
    EXISTS (
        SELECT 1
        FROM public.pending_registrations
        WHERE pending_registrations.authentik_subject = $1
          AND pending_registrations.authentik_user_id = $2
    )
)::boolean AS accepted
`

type UpsertPendingRegistrationIntakeParams struct {
	AuthentikSubject pgtype.UUID
	AuthentikUserID  int64
	DisplayName      string
	VerifiedEmail    string
	IntakeAt         pgtype.Timestamptz
}

func (q *Queries) UpsertPendingRegistrationIntake(ctx context.Context, arg UpsertPendingRegistrationIntakeParams) (bool, error) {
	row := q.db.QueryRow(ctx, upsertPendingRegistrationIntake,
		arg.AuthentikSubject,
		arg.AuthentikUserID,
		arg.DisplayName,
		arg.VerifiedEmail,
		arg.IntakeAt,
	)
	var accepted bool
	err := row.Scan(&accepted)
	return accepted, err
}
