// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registration.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const beginPendingRegistrationDecision = `-- name: BeginPendingRegistrationDecision :one
WITH changed AS (
    UPDATE public.pending_registrations AS registration
    SET status = $1,
        administration_revision = registration.administration_revision + 1,
        transition_request_id = $2,
        reconciliation_class = NULL
    WHERE registration.id = $3
      AND registration.status = 'pending'
      AND registration.administration_revision = $4
      AND registration.administration_revision < 9223372036854775807
    RETURNING registration.id, registration.status,
              registration.administration_revision
), audit AS (
    INSERT INTO public.moderation_actions (
        actor_kind, actor_user_id, target_type, target_site, action_type,
        reason, previous_state, resulting_state, request_id, created_at
    )
    SELECT 'forum_user', $5, 'site', true,
           $6, $7,
           pg_catalog.jsonb_build_object(
               'registration_ref', $8::text,
               'status', 'pending'::text,
               'administration_revision', $4::bigint
           ),
           pg_catalog.jsonb_build_object(
               'registration_ref', $8::text,
               'status', changed.status,
               'administration_revision', changed.administration_revision
           ),
           $2, $9::timestamptz
    FROM changed
    RETURNING id
)
SELECT changed.status, changed.administration_revision, audit.id AS audit_id
FROM changed
JOIN audit ON true
`

type BeginPendingRegistrationDecisionParams struct {
	RequiredStatus   string
	RequestID        pgtype.UUID
	RegistrationID   int64
	ExpectedRevision int64
	ActorUserID      pgtype.Int8
	ActionType       string
	Reason           pgtype.Text
	RegistrationRef  string
	ObservedAt       pgtype.Timestamptz
}

type BeginPendingRegistrationDecisionRow struct {
	Status                 string
	AdministrationRevision int64
	AuditID                int64
}

func (q *Queries) BeginPendingRegistrationDecision(ctx context.Context, arg BeginPendingRegistrationDecisionParams) (BeginPendingRegistrationDecisionRow, error) {
	row := q.db.QueryRow(ctx, beginPendingRegistrationDecision,
		arg.RequiredStatus,
		arg.RequestID,
		arg.RegistrationID,
		arg.ExpectedRevision,
		arg.ActorUserID,
		arg.ActionType,
		arg.Reason,
		arg.RegistrationRef,
		arg.ObservedAt,
	)
	var i BeginPendingRegistrationDecisionRow
	err := row.Scan(&i.Status, &i.AdministrationRevision, &i.AuditID)
	return i, err
}

const completePendingRegistrationDecision = `-- name: CompletePendingRegistrationDecision :one
WITH changed AS (
    UPDATE public.pending_registrations AS registration
    SET status = $1,
        administration_revision = registration.administration_revision + 1,
        decided_at = $2,
        deciding_administrator_id = $3,
        reconciliation_class = NULL
    WHERE registration.id = $4
      AND registration.status = $5
      AND registration.transition_request_id = $6
      AND registration.administration_revision = $7
      AND registration.administration_revision < 9223372036854775807
    RETURNING registration.id, registration.status,
              registration.administration_revision
), audit AS (
    INSERT INTO public.moderation_actions (
        actor_kind, actor_user_id, target_type, target_site, action_type,
        reason, previous_state, resulting_state, request_id, created_at
    )
    SELECT 'forum_user', $3, 'site', true,
           $8, $9,
           pg_catalog.jsonb_build_object(
               'registration_ref', $10::text,
               'status', $5::text,
               'administration_revision', $7::bigint
           ),
           pg_catalog.jsonb_build_object(
               'registration_ref', $10::text,
               'status', changed.status,
               'administration_revision', changed.administration_revision,
               'result', 'confirmed'::text
           ),
           $6, $2::timestamptz
    FROM changed
    RETURNING id
)
SELECT changed.status, changed.administration_revision, audit.id AS audit_id
FROM changed
JOIN audit ON true
`

type CompletePendingRegistrationDecisionParams struct {
	ResultingStatus  string
	ObservedAt       pgtype.Timestamptz
	ActorUserID      pgtype.Int8
	RegistrationID   int64
	RequiredStatus   string
	RequestID        pgtype.UUID
	ExpectedRevision int64
	ActionType       string
	Reason           pgtype.Text
	RegistrationRef  string
}

type CompletePendingRegistrationDecisionRow struct {
	Status                 string
	AdministrationRevision int64
	AuditID                int64
}

func (q *Queries) CompletePendingRegistrationDecision(ctx context.Context, arg CompletePendingRegistrationDecisionParams) (CompletePendingRegistrationDecisionRow, error) {
	row := q.db.QueryRow(ctx, completePendingRegistrationDecision,
		arg.ResultingStatus,
		arg.ObservedAt,
		arg.ActorUserID,
		arg.RegistrationID,
		arg.RequiredStatus,
		arg.RequestID,
		arg.ExpectedRevision,
		arg.ActionType,
		arg.Reason,
		arg.RegistrationRef,
	)
	var i CompletePendingRegistrationDecisionRow
	err := row.Scan(&i.Status, &i.AdministrationRevision, &i.AuditID)
	return i, err
}

const lockPendingRegistration = `-- name: LockPendingRegistration :one
SELECT id, authentik_user_id, authentik_subject, status,
       administration_revision, transition_request_id,
       reconciliation_class
FROM public.pending_registrations
WHERE id = $1
FOR UPDATE
`

type LockPendingRegistrationRow struct {
	ID                     int64
	AuthentikUserID        int64
	AuthentikSubject       pgtype.UUID
	Status                 string
	AdministrationRevision int64
	TransitionRequestID    pgtype.UUID
	ReconciliationClass    pgtype.Text
}

func (q *Queries) LockPendingRegistration(ctx context.Context, registrationID int64) (LockPendingRegistrationRow, error) {
	row := q.db.QueryRow(ctx, lockPendingRegistration, registrationID)
	var i LockPendingRegistrationRow
	err := row.Scan(
		&i.ID,
		&i.AuthentikUserID,
		&i.AuthentikSubject,
		&i.Status,
		&i.AdministrationRevision,
		&i.TransitionRequestID,
		&i.ReconciliationClass,
	)
	return i, err
}

const lockRegistrationAdministrator = `-- name: LockRegistrationAdministrator :one
SELECT forum_user.id
FROM public.users AS forum_user
WHERE forum_user.id = $1
  AND forum_user.role = 'administrator'
  AND forum_user.authentik_sync_state = 'accepted'
  AND (
      forum_user.suspended_at IS NULL
      OR forum_user.suspended_at > $2::timestamptz
      OR forum_user.suspended_until <= $2::timestamptz
  )
  AND (forum_user.muted_until IS NULL OR forum_user.muted_until <= $2::timestamptz)
FOR UPDATE OF forum_user
`

type LockRegistrationAdministratorParams struct {
	ActorUserID int64
	ObservedAt  pgtype.Timestamptz
}

func (q *Queries) LockRegistrationAdministrator(ctx context.Context, arg LockRegistrationAdministratorParams) (int64, error) {
	row := q.db.QueryRow(ctx, lockRegistrationAdministrator, arg.ActorUserID, arg.ObservedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const recordPendingRegistrationDecisionFailure = `-- name: RecordPendingRegistrationDecisionFailure :one
WITH changed AS (
    UPDATE public.pending_registrations AS registration
    SET reconciliation_class = $1,
        administration_revision = registration.administration_revision + 1
    WHERE registration.id = $2
      AND registration.status = $3
      AND registration.transition_request_id = $4
      AND registration.administration_revision = $5
      AND registration.administration_revision < 9223372036854775807
    RETURNING registration.status, registration.administration_revision
), audit AS (
    INSERT INTO public.moderation_actions (
        actor_kind, actor_user_id, target_type, target_site, action_type,
        reason, previous_state, resulting_state, request_id, created_at
    )
    SELECT 'forum_user', $6, 'site', true,
           'record_registration_transition_result', $7,
           pg_catalog.jsonb_build_object(
               'registration_ref', $8::text,
               'status', $3::text,
               'administration_revision', $5::bigint
           ),
           pg_catalog.jsonb_build_object(
               'registration_ref', $8::text,
               'status', changed.status,
               'administration_revision', changed.administration_revision,
               'result', $1::text
           ),
           $4, $9::timestamptz
    FROM changed
    RETURNING id
)
SELECT changed.status, changed.administration_revision, audit.id AS audit_id
FROM changed
JOIN audit ON true
`

type RecordPendingRegistrationDecisionFailureParams struct {
	FailureClass     pgtype.Text
	RegistrationID   int64
	RequiredStatus   string
	RequestID        pgtype.UUID
	ExpectedRevision int64
	ActorUserID      pgtype.Int8
	Reason           pgtype.Text
	RegistrationRef  string
	ObservedAt       pgtype.Timestamptz
}

type RecordPendingRegistrationDecisionFailureRow struct {
	Status                 string
	AdministrationRevision int64
	AuditID                int64
}

func (q *Queries) RecordPendingRegistrationDecisionFailure(ctx context.Context, arg RecordPendingRegistrationDecisionFailureParams) (RecordPendingRegistrationDecisionFailureRow, error) {
	row := q.db.QueryRow(ctx, recordPendingRegistrationDecisionFailure,
		arg.FailureClass,
		arg.RegistrationID,
		arg.RequiredStatus,
		arg.RequestID,
		arg.ExpectedRevision,
		arg.ActorUserID,
		arg.Reason,
		arg.RegistrationRef,
		arg.ObservedAt,
	)
	var i RecordPendingRegistrationDecisionFailureRow
	err := row.Scan(&i.Status, &i.AdministrationRevision, &i.AuditID)
	return i, err
}
