// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addReportNoteAndAudit = `-- name: AddReportNoteAndAudit :one
WITH inserted AS (
    INSERT INTO public.report_notes (report_id, author_id, body, created_at)
    SELECT report.id, $1, $2, $3
    FROM public.reports AS report
    WHERE report.id = $4
      AND report.status = 'in_review'
      AND report.assigned_to IS NOT NULL
    RETURNING report_notes.id, report_notes.report_id,
              report_notes.author_id, report_notes.created_at
), audit AS (
    INSERT INTO public.moderation_actions (
        actor_kind, actor_user_id, target_type, target_report_id, action_type,
        reason, previous_state, resulting_state, request_id, created_at
    )
    SELECT 'forum_user', inserted.author_id, 'report', inserted.report_id, 'note_report',
           $2, '{}'::jsonb, jsonb_build_object('note_id', inserted.id),
           $5, inserted.created_at
    FROM inserted
    RETURNING id, target_report_id
)
SELECT inserted.id AS note_id, inserted.report_id, inserted.author_id,
       inserted.created_at, audit.id AS audit_id
FROM inserted JOIN audit ON audit.target_report_id = inserted.report_id
`

type AddReportNoteAndAuditParams struct {
	ActorUserID int64
	Body        string
	AtTime      pgtype.Timestamptz
	ReportID    int64
	RequestID   pgtype.UUID
}

type AddReportNoteAndAuditRow struct {
	NoteID    int64
	ReportID  int64
	AuthorID  int64
	CreatedAt pgtype.Timestamptz
	AuditID   int64
}

func (q *Queries) AddReportNoteAndAudit(ctx context.Context, arg AddReportNoteAndAuditParams) (AddReportNoteAndAuditRow, error) {
	row := q.db.QueryRow(ctx, addReportNoteAndAudit,
		arg.ActorUserID,
		arg.Body,
		arg.AtTime,
		arg.ReportID,
		arg.RequestID,
	)
	var i AddReportNoteAndAuditRow
	err := row.Scan(
		&i.NoteID,
		&i.ReportID,
		&i.AuthorID,
		&i.CreatedAt,
		&i.AuditID,
	)
	return i, err
}

const claimReportAndAudit = `-- name: ClaimReportAndAudit :one
WITH changed AS (
    UPDATE public.reports AS report
    SET status = 'in_review', assigned_to = $1,
        updated_at = GREATEST($2::timestamptz, report.updated_at)
    WHERE report.id = $3 AND report.status = 'open' AND report.assigned_to IS NULL
    RETURNING report.id, report.status, report.assigned_to, report.updated_at
), audit AS (
    INSERT INTO public.moderation_actions (
        actor_kind, actor_user_id, target_type, target_report_id, action_type,
        previous_state, resulting_state, request_id, created_at
    )
    SELECT 'forum_user', $1, 'report', changed.id, 'assign_report',
           jsonb_build_object('status', 'open', 'assigned_to', NULL),
           jsonb_build_object('status', changed.status, 'assigned_to', changed.assigned_to),
           $4, changed.updated_at
    FROM changed
    RETURNING id, target_report_id
)
SELECT changed.id AS report_id, changed.status, changed.assigned_to,
       changed.updated_at, audit.id AS audit_id
FROM changed JOIN audit ON audit.target_report_id = changed.id
`

type ClaimReportAndAuditParams struct {
	ActorUserID pgtype.Int8
	AtTime      pgtype.Timestamptz
	ReportID    int64
	RequestID   pgtype.UUID
}

type ClaimReportAndAuditRow struct {
	ReportID   int64
	Status     string
	AssignedTo pgtype.Int8
	UpdatedAt  pgtype.Timestamptz
	AuditID    int64
}

func (q *Queries) ClaimReportAndAudit(ctx context.Context, arg ClaimReportAndAuditParams) (ClaimReportAndAuditRow, error) {
	row := q.db.QueryRow(ctx, claimReportAndAudit,
		arg.ActorUserID,
		arg.AtTime,
		arg.ReportID,
		arg.RequestID,
	)
	var i ClaimReportAndAuditRow
	err := row.Scan(
		&i.ReportID,
		&i.Status,
		&i.AssignedTo,
		&i.UpdatedAt,
		&i.AuditID,
	)
	return i, err
}

const countActiveReportsByReporter = `-- name: CountActiveReportsByReporter :one
SELECT count(*)::integer
FROM public.reports
WHERE reported_by = $1
  AND status IN ('open', 'in_review')
`

func (q *Queries) CountActiveReportsByReporter(ctx context.Context, reportedBy int64) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveReportsByReporter, reportedBy)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createPostReport = `-- name: CreatePostReport :one
INSERT INTO public.reports (reported_by, post_id, reason, created_at, updated_at)
SELECT $1, post.id, $2, $3, $3
FROM public.posts AS post
JOIN public.topics AS topic ON topic.id = post.topic_id
JOIN public.areas AS area ON area.id = topic.area_id
WHERE post.id = $4
  AND post.deleted_at IS NULL
  AND topic.deleted_at IS NULL
  AND ($5::boolean OR topic.state <> 'hidden')
  AND (
      $5::boolean
      OR area.visibility = 'public'
      OR ($6::boolean AND area.visibility = 'authenticated')
      OR (
          $6::boolean
          AND area.visibility = 'groups'
          AND EXISTS (
              SELECT 1 FROM public.area_groups AS membership
              WHERE membership.area_id = area.id
                AND membership.group_id = ANY($7::bigint[])
          )
      )
  )
RETURNING id, reported_by, topic_id, post_id, user_id, status, created_at
`

type CreatePostReportParams struct {
	ReportedBy int64
	Reason     string
	AtTime     pgtype.Timestamptz
	PostID     int64
	IsStaff    bool
	IsMember   bool
	GroupIds   []int64
}

type CreatePostReportRow struct {
	ID         int64
	ReportedBy int64
	TopicID    pgtype.Int8
	PostID     pgtype.Int8
	UserID     pgtype.Int8
	Status     string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) CreatePostReport(ctx context.Context, arg CreatePostReportParams) (CreatePostReportRow, error) {
	row := q.db.QueryRow(ctx, createPostReport,
		arg.ReportedBy,
		arg.Reason,
		arg.AtTime,
		arg.PostID,
		arg.IsStaff,
		arg.IsMember,
		arg.GroupIds,
	)
	var i CreatePostReportRow
	err := row.Scan(
		&i.ID,
		&i.ReportedBy,
		&i.TopicID,
		&i.PostID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createTopicReport = `-- name: CreateTopicReport :one
INSERT INTO public.reports (reported_by, topic_id, reason, created_at, updated_at)
SELECT $1, topic.id, $2, $3, $3
FROM public.topics AS topic
JOIN public.areas AS area ON area.id = topic.area_id
WHERE topic.id = $4
  AND topic.deleted_at IS NULL
  AND ($5::boolean OR topic.state <> 'hidden')
  AND (
      $5::boolean
      OR area.visibility = 'public'
      OR ($6::boolean AND area.visibility = 'authenticated')
      OR (
          $6::boolean
          AND area.visibility = 'groups'
          AND EXISTS (
              SELECT 1 FROM public.area_groups AS membership
              WHERE membership.area_id = area.id
                AND membership.group_id = ANY($7::bigint[])
          )
      )
  )
RETURNING id, reported_by, topic_id, post_id, user_id, status, created_at
`

type CreateTopicReportParams struct {
	ReportedBy int64
	Reason     string
	AtTime     pgtype.Timestamptz
	TopicID    int64
	IsStaff    bool
	IsMember   bool
	GroupIds   []int64
}

type CreateTopicReportRow struct {
	ID         int64
	ReportedBy int64
	TopicID    pgtype.Int8
	PostID     pgtype.Int8
	UserID     pgtype.Int8
	Status     string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateTopicReport(ctx context.Context, arg CreateTopicReportParams) (CreateTopicReportRow, error) {
	row := q.db.QueryRow(ctx, createTopicReport,
		arg.ReportedBy,
		arg.Reason,
		arg.AtTime,
		arg.TopicID,
		arg.IsStaff,
		arg.IsMember,
		arg.GroupIds,
	)
	var i CreateTopicReportRow
	err := row.Scan(
		&i.ID,
		&i.ReportedBy,
		&i.TopicID,
		&i.PostID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createUserReport = `-- name: CreateUserReport :one
INSERT INTO public.reports (reported_by, user_id, reason, created_at, updated_at)
SELECT $1, target.id, $2, $3, $3
FROM public.users AS target
WHERE target.id = $4
  AND target.id <> $1
  AND EXISTS (
      SELECT 1
      FROM public.posts AS post
      JOIN public.topics AS topic ON topic.id = post.topic_id
      JOIN public.areas AS area ON area.id = topic.area_id
      WHERE post.author_id = target.id
        AND post.deleted_at IS NULL
        AND topic.deleted_at IS NULL
        AND ($5::boolean OR topic.state <> 'hidden')
        AND (
            $5::boolean
            OR area.visibility = 'public'
            OR ($6::boolean AND area.visibility = 'authenticated')
            OR (
                $6::boolean
                AND area.visibility = 'groups'
                AND EXISTS (
                    SELECT 1 FROM public.area_groups AS membership
                    WHERE membership.area_id = area.id
                      AND membership.group_id = ANY($7::bigint[])
                )
            )
        )
  )
RETURNING id, reported_by, topic_id, post_id, user_id, status, created_at
`

type CreateUserReportParams struct {
	ReportedBy int64
	Reason     string
	AtTime     pgtype.Timestamptz
	UserID     int64
	IsStaff    bool
	IsMember   bool
	GroupIds   []int64
}

type CreateUserReportRow struct {
	ID         int64
	ReportedBy int64
	TopicID    pgtype.Int8
	PostID     pgtype.Int8
	UserID     pgtype.Int8
	Status     string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateUserReport(ctx context.Context, arg CreateUserReportParams) (CreateUserReportRow, error) {
	row := q.db.QueryRow(ctx, createUserReport,
		arg.ReportedBy,
		arg.Reason,
		arg.AtTime,
		arg.UserID,
		arg.IsStaff,
		arg.IsMember,
		arg.GroupIds,
	)
	var i CreateUserReportRow
	err := row.Scan(
		&i.ID,
		&i.ReportedBy,
		&i.TopicID,
		&i.PostID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const finishReportAndAudit = `-- name: FinishReportAndAudit :one
WITH changed AS (
    UPDATE public.reports AS report
    SET status = $1, resolution = $2,
        resolved_by = $3,
        resolved_at = GREATEST($4::timestamptz, report.updated_at),
        updated_at = GREATEST($4::timestamptz, report.updated_at)
    WHERE report.id = $5
      AND report.status = 'in_review'
      AND report.assigned_to IS NOT NULL
    RETURNING report.id, report.status, report.assigned_to, report.resolution,
              report.resolved_by, report.resolved_at, report.updated_at
), audit AS (
    INSERT INTO public.moderation_actions (
        actor_kind, actor_user_id, target_type, target_report_id, action_type,
        reason, previous_state, resulting_state, request_id, created_at
    )
    SELECT 'forum_user', $3, 'report', changed.id,
           $6, changed.resolution,
           jsonb_build_object('status', 'in_review', 'assigned_to', changed.assigned_to),
           jsonb_build_object('status', changed.status, 'assigned_to', changed.assigned_to,
                              'resolved_by', changed.resolved_by),
           $7, changed.updated_at
    FROM changed
    RETURNING id, target_report_id
)
SELECT changed.id AS report_id, changed.status, changed.assigned_to,
       changed.resolved_by, changed.resolved_at, changed.updated_at, audit.id AS audit_id
FROM changed JOIN audit ON audit.target_report_id = changed.id
`

type FinishReportAndAuditParams struct {
	ResultingStatus string
	Resolution      pgtype.Text
	ActorUserID     pgtype.Int8
	AtTime          pgtype.Timestamptz
	ReportID        int64
	ActionType      string
	RequestID       pgtype.UUID
}

type FinishReportAndAuditRow struct {
	ReportID   int64
	Status     string
	AssignedTo pgtype.Int8
	ResolvedBy pgtype.Int8
	ResolvedAt pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	AuditID    int64
}

func (q *Queries) FinishReportAndAudit(ctx context.Context, arg FinishReportAndAuditParams) (FinishReportAndAuditRow, error) {
	row := q.db.QueryRow(ctx, finishReportAndAudit,
		arg.ResultingStatus,
		arg.Resolution,
		arg.ActorUserID,
		arg.AtTime,
		arg.ReportID,
		arg.ActionType,
		arg.RequestID,
	)
	var i FinishReportAndAuditRow
	err := row.Scan(
		&i.ReportID,
		&i.Status,
		&i.AssignedTo,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.UpdatedAt,
		&i.AuditID,
	)
	return i, err
}

const getReportForModeration = `-- name: GetReportForModeration :one
SELECT
    report.id,
    report.reported_by,
    reporter.display_name AS reporter_display_name,
    report.reason,
    report.status,
    report.assigned_to,
    assignee.display_name AS assignee_display_name,
    report.resolution,
    report.resolved_by,
    resolver.display_name AS resolver_display_name,
    report.created_at,
    report.updated_at,
    report.resolved_at,
    CASE WHEN report.topic_id IS NOT NULL THEN 'topic'
         WHEN report.post_id IS NOT NULL THEN 'post'
         ELSE 'user' END::text AS target_type,
    COALESCE(report.topic_id, report.post_id, report.user_id)::bigint AS target_id,
    CASE WHEN report.user_id IS NULL THEN COALESCE(report.topic_id, post.topic_id)
         ELSE 0::bigint END AS target_topic_id,
    CASE WHEN report.post_id IS NULL THEN 0::bigint
         ELSE (
             SELECT 1 + (count(*) - 1) / 25
             FROM public.posts AS ranked_post
             WHERE ranked_post.topic_id = post.topic_id
               AND ranked_post.thread_path <= post.thread_path
         ) END::bigint AS target_page,
    COALESCE(topic.title, post_topic.title, target_user.display_name)::text AS target_label
FROM public.reports AS report
JOIN public.users AS reporter ON reporter.id = report.reported_by
LEFT JOIN public.users AS assignee ON assignee.id = report.assigned_to
LEFT JOIN public.users AS resolver ON resolver.id = report.resolved_by
LEFT JOIN public.topics AS topic ON topic.id = report.topic_id
LEFT JOIN public.posts AS post ON post.id = report.post_id
LEFT JOIN public.topics AS post_topic ON post_topic.id = post.topic_id
LEFT JOIN public.users AS target_user ON target_user.id = report.user_id
WHERE report.id = $1
  AND EXISTS (
      SELECT 1 FROM public.users AS actor
      WHERE actor.id = $2
        AND actor.role = $3
        AND actor.role IN ('moderator', 'administrator')
        AND actor.authentik_sync_state = 'accepted'
        AND (actor.suspended_at IS NULL OR actor.suspended_at > $4::timestamptz OR actor.suspended_until <= $4::timestamptz)
        AND (actor.muted_until IS NULL OR actor.muted_until <= $4::timestamptz)
  )
`

type GetReportForModerationParams struct {
	ReportID    int64
	ActorUserID int64
	ActorRole   string
	ObservedAt  pgtype.Timestamptz
}

type GetReportForModerationRow struct {
	ID                  int64
	ReportedBy          int64
	ReporterDisplayName string
	Reason              string
	Status              string
	AssignedTo          pgtype.Int8
	AssigneeDisplayName pgtype.Text
	Resolution          pgtype.Text
	ResolvedBy          pgtype.Int8
	ResolverDisplayName pgtype.Text
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	ResolvedAt          pgtype.Timestamptz
	TargetType          string
	TargetID            int64
	TargetTopicID       int64
	TargetPage          int64
	TargetLabel         string
}

func (q *Queries) GetReportForModeration(ctx context.Context, arg GetReportForModerationParams) (GetReportForModerationRow, error) {
	row := q.db.QueryRow(ctx, getReportForModeration,
		arg.ReportID,
		arg.ActorUserID,
		arg.ActorRole,
		arg.ObservedAt,
	)
	var i GetReportForModerationRow
	err := row.Scan(
		&i.ID,
		&i.ReportedBy,
		&i.ReporterDisplayName,
		&i.Reason,
		&i.Status,
		&i.AssignedTo,
		&i.AssigneeDisplayName,
		&i.Resolution,
		&i.ResolvedBy,
		&i.ResolverDisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
		&i.TargetType,
		&i.TargetID,
		&i.TargetTopicID,
		&i.TargetPage,
		&i.TargetLabel,
	)
	return i, err
}

const listActiveReportsForModeration = `-- name: ListActiveReportsForModeration :many
SELECT
    report.id,
    report.reason,
    report.status,
    report.created_at,
    reporter.display_name AS reporter_display_name,
    report.assigned_to,
    assignee.display_name AS assignee_display_name,
    CASE WHEN report.topic_id IS NOT NULL THEN 'topic'
         WHEN report.post_id IS NOT NULL THEN 'post'
         ELSE 'user' END::text AS target_type,
    COALESCE(report.topic_id, report.post_id, report.user_id)::bigint AS target_id,
    COALESCE(topic.title, post_topic.title, target_user.display_name)::text AS target_label,
    count(*) OVER ()::bigint AS total_active
FROM public.reports AS report
JOIN public.users AS reporter ON reporter.id = report.reported_by
LEFT JOIN public.users AS assignee ON assignee.id = report.assigned_to
LEFT JOIN public.topics AS topic ON topic.id = report.topic_id
LEFT JOIN public.posts AS post ON post.id = report.post_id
LEFT JOIN public.topics AS post_topic ON post_topic.id = post.topic_id
LEFT JOIN public.users AS target_user ON target_user.id = report.user_id
WHERE report.status IN ('open', 'in_review')
  AND EXISTS (
      SELECT 1 FROM public.users AS actor
      WHERE actor.id = $1
        AND actor.role = $2
        AND actor.role IN ('moderator', 'administrator')
        AND actor.authentik_sync_state = 'accepted'
        AND (actor.suspended_at IS NULL OR actor.suspended_at > $3::timestamptz OR actor.suspended_until <= $3::timestamptz)
        AND (actor.muted_until IS NULL OR actor.muted_until <= $3::timestamptz)
  )
ORDER BY CASE report.status WHEN 'open' THEN 0 ELSE 1 END,
         report.created_at,
         report.id
LIMIT $5::integer
OFFSET $4::integer
`

type ListActiveReportsForModerationParams struct {
	ActorUserID int64
	ActorRole   string
	ObservedAt  pgtype.Timestamptz
	PageOffset  int32
	PageLimit   int32
}

type ListActiveReportsForModerationRow struct {
	ID                  int64
	Reason              string
	Status              string
	CreatedAt           pgtype.Timestamptz
	ReporterDisplayName string
	AssignedTo          pgtype.Int8
	AssigneeDisplayName pgtype.Text
	TargetType          string
	TargetID            int64
	TargetLabel         string
	TotalActive         int64
}

func (q *Queries) ListActiveReportsForModeration(ctx context.Context, arg ListActiveReportsForModerationParams) ([]ListActiveReportsForModerationRow, error) {
	rows, err := q.db.Query(ctx, listActiveReportsForModeration,
		arg.ActorUserID,
		arg.ActorRole,
		arg.ObservedAt,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveReportsForModerationRow{}
	for rows.Next() {
		var i ListActiveReportsForModerationRow
		if err := rows.Scan(
			&i.ID,
			&i.Reason,
			&i.Status,
			&i.CreatedAt,
			&i.ReporterDisplayName,
			&i.AssignedTo,
			&i.AssigneeDisplayName,
			&i.TargetType,
			&i.TargetID,
			&i.TargetLabel,
			&i.TotalActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportNotes = `-- name: ListReportNotes :many
SELECT report.id AS authorized_report_id,
       note.id,
       note.author_id,
       author.display_name AS author_display_name,
       note.body,
       note.created_at
FROM public.reports AS report
JOIN public.users AS actor
  ON actor.id = $1
 AND actor.role = $2
 AND actor.role IN ('moderator', 'administrator')
 AND actor.authentik_sync_state = 'accepted'
 AND (actor.suspended_at IS NULL OR actor.suspended_at > $3::timestamptz OR actor.suspended_until <= $3::timestamptz)
 AND (actor.muted_until IS NULL OR actor.muted_until <= $3::timestamptz)
LEFT JOIN public.report_notes AS note ON note.report_id = report.id
LEFT JOIN public.users AS author ON author.id = note.author_id
WHERE report.id = $4
ORDER BY note.created_at, note.id
`

type ListReportNotesParams struct {
	ActorUserID int64
	ActorRole   string
	ObservedAt  pgtype.Timestamptz
	ReportID    int64
}

type ListReportNotesRow struct {
	AuthorizedReportID int64
	ID                 pgtype.Int8
	AuthorID           pgtype.Int8
	AuthorDisplayName  pgtype.Text
	Body               pgtype.Text
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) ListReportNotes(ctx context.Context, arg ListReportNotesParams) ([]ListReportNotesRow, error) {
	rows, err := q.db.Query(ctx, listReportNotes,
		arg.ActorUserID,
		arg.ActorRole,
		arg.ObservedAt,
		arg.ReportID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReportNotesRow{}
	for rows.Next() {
		var i ListReportNotesRow
		if err := rows.Scan(
			&i.AuthorizedReportID,
			&i.ID,
			&i.AuthorID,
			&i.AuthorDisplayName,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockReportForModeration = `-- name: LockReportForModeration :one
SELECT id, status, assigned_to, created_at, updated_at
FROM public.reports
WHERE id = $1
FOR UPDATE
`

type LockReportForModerationRow struct {
	ID         int64
	Status     string
	AssignedTo pgtype.Int8
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) LockReportForModeration(ctx context.Context, reportID int64) (LockReportForModerationRow, error) {
	row := q.db.QueryRow(ctx, lockReportForModeration, reportID)
	var i LockReportForModerationRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AssignedTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
