// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: site.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const configureAdministrationTransaction = `-- name: ConfigureAdministrationTransaction :one
SELECT
    set_config('statement_timeout', '2000ms', true),
    set_config('lock_timeout', '250ms', true)
`

type ConfigureAdministrationTransactionRow struct {
	SetConfig   string
	SetConfig_2 string
}

func (q *Queries) ConfigureAdministrationTransaction(ctx context.Context) (ConfigureAdministrationTransactionRow, error) {
	row := q.db.QueryRow(ctx, configureAdministrationTransaction)
	var i ConfigureAdministrationTransactionRow
	err := row.Scan(&i.SetConfig, &i.SetConfig_2)
	return i, err
}

const loadEditableSiteSettings = `-- name: LoadEditableSiteSettings :one
WITH actor AS MATERIALIZED (
    SELECT forum_user.id
    FROM public.users AS forum_user
    WHERE forum_user.id = $1
      AND forum_user.role = 'administrator'
      AND (
          forum_user.suspended_at IS NULL
          OR forum_user.suspended_at > $2::timestamptz
          OR forum_user.suspended_until <= $2::timestamptz
      )
      AND (forum_user.muted_until IS NULL OR forum_user.muted_until <= $2::timestamptz)
)
SELECT (settings.singleton IS TRUE)::boolean AS settings_present,
       COALESCE(settings.site_name, '')::text AS site_name,
       COALESCE(settings.site_description, '')::text AS site_description,
       COALESCE(settings.brand_theme, '')::text AS brand_theme,
       COALESCE(settings.rules_markdown, '')::text AS rules_markdown,
       COALESCE(settings.rules_html, '')::text AS rules_html,
       COALESCE(settings.rules_renderer_version, '')::text AS rules_renderer_version,
       COALESCE(settings.administration_revision, 0)::bigint AS administration_revision
FROM actor
LEFT JOIN LATERAL (
    SELECT singleton, site_name, site_description, brand_theme,
           rules_markdown, rules_html, rules_renderer_version,
           administration_revision
    FROM public.site_settings
    WHERE singleton
) AS settings ON true
`

type LoadEditableSiteSettingsParams struct {
	ActorUserID int64
	ObservedAt  pgtype.Timestamptz
}

type LoadEditableSiteSettingsRow struct {
	SettingsPresent        bool
	SiteName               string
	SiteDescription        string
	BrandTheme             string
	RulesMarkdown          string
	RulesHtml              string
	RulesRendererVersion   string
	AdministrationRevision int64
}

func (q *Queries) LoadEditableSiteSettings(ctx context.Context, arg LoadEditableSiteSettingsParams) (LoadEditableSiteSettingsRow, error) {
	row := q.db.QueryRow(ctx, loadEditableSiteSettings, arg.ActorUserID, arg.ObservedAt)
	var i LoadEditableSiteSettingsRow
	err := row.Scan(
		&i.SettingsPresent,
		&i.SiteName,
		&i.SiteDescription,
		&i.BrandTheme,
		&i.RulesMarkdown,
		&i.RulesHtml,
		&i.RulesRendererVersion,
		&i.AdministrationRevision,
	)
	return i, err
}

const loadPublicRules = `-- name: LoadPublicRules :one
SELECT site_name, site_description, brand_theme,
       rules_markdown, rules_html, rules_renderer_version
FROM public.site_settings
WHERE singleton
`

type LoadPublicRulesRow struct {
	SiteName             string
	SiteDescription      string
	BrandTheme           string
	RulesMarkdown        string
	RulesHtml            string
	RulesRendererVersion string
}

func (q *Queries) LoadPublicRules(ctx context.Context) (LoadPublicRulesRow, error) {
	row := q.db.QueryRow(ctx, loadPublicRules)
	var i LoadPublicRulesRow
	err := row.Scan(
		&i.SiteName,
		&i.SiteDescription,
		&i.BrandTheme,
		&i.RulesMarkdown,
		&i.RulesHtml,
		&i.RulesRendererVersion,
	)
	return i, err
}

const loadSiteShellPresentation = `-- name: LoadSiteShellPresentation :one
SELECT site_name, site_description, brand_theme
FROM public.site_settings
WHERE singleton
`

type LoadSiteShellPresentationRow struct {
	SiteName        string
	SiteDescription string
	BrandTheme      string
}

func (q *Queries) LoadSiteShellPresentation(ctx context.Context) (LoadSiteShellPresentationRow, error) {
	row := q.db.QueryRow(ctx, loadSiteShellPresentation)
	var i LoadSiteShellPresentationRow
	err := row.Scan(&i.SiteName, &i.SiteDescription, &i.BrandTheme)
	return i, err
}

const lockSiteSettings = `-- name: LockSiteSettings :one
SELECT site_name, site_description, brand_theme,
       rules_markdown, rules_html, rules_renderer_version,
       administration_revision, updated_at
FROM public.site_settings
WHERE singleton
FOR UPDATE
`

type LockSiteSettingsRow struct {
	SiteName               string
	SiteDescription        string
	BrandTheme             string
	RulesMarkdown          string
	RulesHtml              string
	RulesRendererVersion   string
	AdministrationRevision int64
	UpdatedAt              pgtype.Timestamptz
}

func (q *Queries) LockSiteSettings(ctx context.Context) (LockSiteSettingsRow, error) {
	row := q.db.QueryRow(ctx, lockSiteSettings)
	var i LockSiteSettingsRow
	err := row.Scan(
		&i.SiteName,
		&i.SiteDescription,
		&i.BrandTheme,
		&i.RulesMarkdown,
		&i.RulesHtml,
		&i.RulesRendererVersion,
		&i.AdministrationRevision,
		&i.UpdatedAt,
	)
	return i, err
}

const lockSiteSettingsAdministrator = `-- name: LockSiteSettingsAdministrator :one
SELECT forum_user.id
FROM public.users AS forum_user
WHERE forum_user.id = $1
  AND forum_user.role = 'administrator'
  AND (
      forum_user.suspended_at IS NULL
      OR forum_user.suspended_at > $2::timestamptz
      OR forum_user.suspended_until <= $2::timestamptz
  )
  AND (forum_user.muted_until IS NULL OR forum_user.muted_until <= $2::timestamptz)
FOR UPDATE OF forum_user
`

type LockSiteSettingsAdministratorParams struct {
	ActorUserID int64
	ObservedAt  pgtype.Timestamptz
}

func (q *Queries) LockSiteSettingsAdministrator(ctx context.Context, arg LockSiteSettingsAdministratorParams) (int64, error) {
	row := q.db.QueryRow(ctx, lockSiteSettingsAdministrator, arg.ActorUserID, arg.ObservedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateSiteSettingsAndAudit = `-- name: UpdateSiteSettingsAndAudit :one
WITH updated AS (
    UPDATE public.site_settings AS settings
    SET site_name = $1,
        site_description = $2,
        brand_theme = $3,
        rules_markdown = $4,
        rules_html = $5,
        rules_renderer_version = $6,
        administration_revision = settings.administration_revision + 1,
        updated_at = $7::timestamptz
    WHERE settings.singleton
      AND settings.administration_revision = $8
      AND settings.administration_revision < 9223372036854775807
    RETURNING settings.administration_revision
),
audit AS (
    INSERT INTO public.moderation_actions (
        actor_kind,
        actor_user_id,
        target_type,
        target_site,
        action_type,
        reason,
        previous_state,
        resulting_state,
        request_id,
        created_at
    )
    SELECT
        'forum_user',
        $9,
        'site',
        true,
        'update_site_settings',
        $10,
        jsonb_build_object(
            'site_name', $11::text,
            'site_description', $12::text,
            'brand_theme', $13::text,
            'rules_renderer_version', $14::text,
            'rules_markdown_sha256', $15::text,
            'rules_html_sha256', $16::text
        ),
        jsonb_build_object(
            'site_name', $1::text,
            'site_description', $2::text,
            'brand_theme', $3::text,
            'rules_renderer_version', $6::text,
            'rules_markdown_sha256', $17::text,
            'rules_html_sha256', $18::text
        ),
        $19,
        $7::timestamptz
    FROM updated
    RETURNING id
)
SELECT updated.administration_revision, audit.id AS audit_id
FROM updated
JOIN audit ON true
`

type UpdateSiteSettingsAndAuditParams struct {
	SiteName                     string
	SiteDescription              string
	BrandTheme                   string
	RulesMarkdown                string
	RulesHtml                    string
	RulesRendererVersion         string
	ObservedAt                   pgtype.Timestamptz
	ExpectedRevision             int64
	ActorUserID                  pgtype.Int8
	Reason                       pgtype.Text
	PreviousSiteName             string
	PreviousSiteDescription      string
	PreviousBrandTheme           string
	PreviousRulesRendererVersion string
	PreviousRulesMarkdownSha256  string
	PreviousRulesHtmlSha256      string
	RulesMarkdownSha256          string
	RulesHtmlSha256              string
	RequestID                    pgtype.UUID
}

type UpdateSiteSettingsAndAuditRow struct {
	AdministrationRevision int64
	AuditID                int64
}

func (q *Queries) UpdateSiteSettingsAndAudit(ctx context.Context, arg UpdateSiteSettingsAndAuditParams) (UpdateSiteSettingsAndAuditRow, error) {
	row := q.db.QueryRow(ctx, updateSiteSettingsAndAudit,
		arg.SiteName,
		arg.SiteDescription,
		arg.BrandTheme,
		arg.RulesMarkdown,
		arg.RulesHtml,
		arg.RulesRendererVersion,
		arg.ObservedAt,
		arg.ExpectedRevision,
		arg.ActorUserID,
		arg.Reason,
		arg.PreviousSiteName,
		arg.PreviousSiteDescription,
		arg.PreviousBrandTheme,
		arg.PreviousRulesRendererVersion,
		arg.PreviousRulesMarkdownSha256,
		arg.PreviousRulesHtmlSha256,
		arg.RulesMarkdownSha256,
		arg.RulesHtmlSha256,
		arg.RequestID,
	)
	var i UpdateSiteSettingsAndAuditRow
	err := row.Scan(&i.AdministrationRevision, &i.AuditID)
	return i, err
}
