// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: unread.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const configureMarkTopicReadTransaction = `-- name: ConfigureMarkTopicReadTransaction :exec
SELECT
    set_config('statement_timeout', '2000ms', true),
    set_config('lock_timeout', '250ms', true)
`

func (q *Queries) ConfigureMarkTopicReadTransaction(ctx context.Context) error {
	_, err := q.db.Exec(ctx, configureMarkTopicReadTransaction)
	return err
}

const configureUnreadReadTransaction = `-- name: ConfigureUnreadReadTransaction :exec
SELECT
    set_config('statement_timeout', '5000ms', true),
    set_config('lock_timeout', '250ms', true),
    set_config('work_mem', '4MB', true),
    set_config('max_parallel_workers_per_gather', '0', true),
    set_config('jit', 'off', true)
`

func (q *Queries) ConfigureUnreadReadTransaction(ctx context.Context) error {
	_, err := q.db.Exec(ctx, configureUnreadReadTransaction)
	return err
}

const getAuthorizedTopicReadState = `-- name: GetAuthorizedTopicReadState :one
WITH authorized_topic AS MATERIALIZED (
    SELECT
        topic.id AS topic_id,
        topic.next_post_number
    FROM public.topics AS topic
    JOIN public.areas AS area ON area.id = topic.area_id
    WHERE topic.id = $2
      AND topic.deleted_at IS NULL
      AND ($3::boolean OR topic.state <> 'hidden')
      AND (
        $3::boolean
        OR area.visibility IN ('public', 'authenticated')
        OR (
            area.visibility = 'groups'
            AND COALESCE(cardinality($4::bigint[]), 0) > 0
            AND EXISTS (
                SELECT 1
                FROM public.area_groups AS membership
                WHERE membership.area_id = area.id
                  AND membership.group_id = ANY($4::bigint[])
            )
        )
      )
)
SELECT
    topic.topic_id,
    topic.next_post_number,
    head.read_head,
    marker.last_read_post_number,
    marker.read_at,
    CASE
        WHEN head.read_head = 0 THEN 'read'
        WHEN marker.user_id IS NULL THEN 'new'
        WHEN marker.last_read_post_number < head.read_head THEN 'unread'
        ELSE 'read'
    END::text AS read_state
FROM authorized_topic AS topic
LEFT JOIN LATERAL (
    SELECT COALESCE(max(post.post_number), 0)::integer AS read_head
    FROM public.posts AS post
    WHERE post.topic_id = topic.topic_id
      AND post.deleted_at IS NULL
      AND post.redacted_at IS NULL
      AND post.author_id <> $1::bigint
) AS head ON true
LEFT JOIN public.topic_reads AS marker
  ON marker.topic_id = topic.topic_id
 AND marker.user_id = $1::bigint
`

type GetAuthorizedTopicReadStateParams struct {
	ActorUserID int64
	TopicID     int64
	IsStaff     bool
	GroupIds    []int64
}

type GetAuthorizedTopicReadStateRow struct {
	TopicID            int64
	NextPostNumber     int32
	ReadHead           int32
	LastReadPostNumber pgtype.Int4
	ReadAt             pgtype.Timestamptz
	ReadState          string
}

func (q *Queries) GetAuthorizedTopicReadState(ctx context.Context, arg GetAuthorizedTopicReadStateParams) (GetAuthorizedTopicReadStateRow, error) {
	row := q.db.QueryRow(ctx, getAuthorizedTopicReadState,
		arg.ActorUserID,
		arg.TopicID,
		arg.IsStaff,
		arg.GroupIds,
	)
	var i GetAuthorizedTopicReadStateRow
	err := row.Scan(
		&i.TopicID,
		&i.NextPostNumber,
		&i.ReadHead,
		&i.LastReadPostNumber,
		&i.ReadAt,
		&i.ReadState,
	)
	return i, err
}

const getFirstUnreadTarget = `-- name: GetFirstUnreadTarget :one
WITH authorized_topic AS MATERIALIZED (
    SELECT
        topic.id AS topic_id,
        topic.next_post_number
    FROM public.topics AS topic
    JOIN public.areas AS area ON area.id = topic.area_id
    WHERE topic.id = $1
      AND topic.deleted_at IS NULL
      AND ($2::boolean OR topic.state <> 'hidden')
      AND (
        $2::boolean
        OR area.visibility IN ('public', 'authenticated')
        OR (
            area.visibility = 'groups'
            AND COALESCE(cardinality($3::bigint[]), 0) > 0
            AND EXISTS (
                SELECT 1
                FROM public.area_groups AS membership
                WHERE membership.area_id = area.id
                  AND membership.group_id = ANY($3::bigint[])
            )
        )
      )
),
topic_state AS MATERIALIZED (
    SELECT
        topic.topic_id,
        topic.next_post_number,
        marker.last_read_post_number,
        marker.read_at,
        head.read_head
    FROM authorized_topic AS topic
    LEFT JOIN public.topic_reads AS marker
      ON marker.topic_id = topic.topic_id
     AND marker.user_id = $4::bigint
    LEFT JOIN LATERAL (
        SELECT COALESCE(max(post.post_number), 0)::integer AS read_head
        FROM public.posts AS post
        WHERE post.topic_id = topic.topic_id
          AND post.deleted_at IS NULL
          AND post.redacted_at IS NULL
          AND post.author_id <> $4::bigint
    ) AS head ON true
),
target AS MATERIALIZED (
    SELECT
        post.id AS post_id,
        post.post_number
    FROM topic_state AS state
    JOIN LATERAL (
        SELECT candidate.id, candidate.post_number
        FROM public.posts AS candidate
        WHERE candidate.topic_id = state.topic_id
          AND candidate.deleted_at IS NULL
          AND candidate.redacted_at IS NULL
          AND candidate.author_id <> $4::bigint
          AND candidate.post_number > COALESCE(state.last_read_post_number, 0)
        ORDER BY candidate.post_number
        LIMIT 1
    ) AS post ON true
),
bounded_thread AS MATERIALIZED (
    SELECT
        post.id AS post_id,
        post.thread_path
    FROM target
    JOIN authorized_topic AS topic ON true
    JOIN public.posts AS post ON post.topic_id = topic.topic_id
    WHERE $2::boolean
       OR post.deleted_at IS NULL
       OR EXISTS (
            SELECT 1
            FROM public.posts AS descendant
            WHERE descendant.topic_id = post.topic_id
              AND descendant.deleted_at IS NULL
              AND descendant.id <> post.id
              AND descendant.thread_path[1:cardinality(post.thread_path)] = post.thread_path
       )
    ORDER BY post.thread_path
    LIMIT 250001
),
numbered_thread AS MATERIALIZED (
    SELECT
        node.post_id,
        row_number() OVER (ORDER BY node.thread_path)::bigint AS node_ordinal
    FROM bounded_thread AS node
)
SELECT
    state.topic_id,
    state.next_post_number,
    state.last_read_post_number,
    state.read_at,
    state.read_head,
    target.post_id AS target_post_id,
    target.post_number AS target_post_number,
    node.node_ordinal AS target_node_ordinal
FROM topic_state AS state
LEFT JOIN target ON true
LEFT JOIN numbered_thread AS node ON node.post_id = target.post_id
`

type GetFirstUnreadTargetParams struct {
	TopicID     int64
	IsStaff     bool
	GroupIds    []int64
	ActorUserID int64
}

type GetFirstUnreadTargetRow struct {
	TopicID            int64
	NextPostNumber     int32
	LastReadPostNumber pgtype.Int4
	ReadAt             pgtype.Timestamptz
	ReadHead           int32
	TargetPostID       pgtype.Int8
	TargetPostNumber   pgtype.Int4
	TargetNodeOrdinal  pgtype.Int8
}

func (q *Queries) GetFirstUnreadTarget(ctx context.Context, arg GetFirstUnreadTargetParams) (GetFirstUnreadTargetRow, error) {
	row := q.db.QueryRow(ctx, getFirstUnreadTarget,
		arg.TopicID,
		arg.IsStaff,
		arg.GroupIds,
		arg.ActorUserID,
	)
	var i GetFirstUnreadTargetRow
	err := row.Scan(
		&i.TopicID,
		&i.NextPostNumber,
		&i.LastReadPostNumber,
		&i.ReadAt,
		&i.ReadHead,
		&i.TargetPostID,
		&i.TargetPostNumber,
		&i.TargetNodeOrdinal,
	)
	return i, err
}

const getTopicReadMarker = `-- name: GetTopicReadMarker :one
SELECT
    marker.last_read_post_number,
    marker.read_at
FROM public.topic_reads AS marker
WHERE marker.user_id = $1
  AND marker.topic_id = $2
`

type GetTopicReadMarkerParams struct {
	ActorUserID int64
	TopicID     int64
}

type GetTopicReadMarkerRow struct {
	LastReadPostNumber int32
	ReadAt             pgtype.Timestamptz
}

func (q *Queries) GetTopicReadMarker(ctx context.Context, arg GetTopicReadMarkerParams) (GetTopicReadMarkerRow, error) {
	row := q.db.QueryRow(ctx, getTopicReadMarker, arg.ActorUserID, arg.TopicID)
	var i GetTopicReadMarkerRow
	err := row.Scan(&i.LastReadPostNumber, &i.ReadAt)
	return i, err
}

const markTopicReadBoundary = `-- name: MarkTopicReadBoundary :one
WITH authorized_topic AS MATERIALIZED (
    SELECT
        topic.id AS topic_id,
        topic.next_post_number
    FROM public.topics AS topic
    JOIN public.areas AS area ON area.id = topic.area_id
    WHERE topic.id = $1
      AND topic.deleted_at IS NULL
      AND ($2::boolean OR topic.state <> 'hidden')
      AND (
        $2::boolean
        OR area.visibility IN ('public', 'authenticated')
        OR (
            area.visibility = 'groups'
            AND COALESCE(cardinality($3::bigint[]), 0) > 0
            AND EXISTS (
                SELECT 1
                FROM public.area_groups AS membership
                WHERE membership.area_id = area.id
                  AND membership.group_id = ANY($3::bigint[])
            )
        )
      )
),
boundary AS MATERIALIZED (
    SELECT
        topic.topic_id,
        topic.next_post_number,
        head.selected_post_number
    FROM authorized_topic AS topic
    LEFT JOIN LATERAL (
        SELECT COALESCE(max(post.post_number), 0)::integer AS selected_post_number
        FROM public.posts AS post
        WHERE post.topic_id = topic.topic_id
          AND post.deleted_at IS NULL
          AND post.redacted_at IS NULL
          AND post.author_id <> $4::bigint
    ) AS head ON true
),
upserted AS (
    INSERT INTO public.topic_reads (
        user_id,
        topic_id,
        last_read_post_number,
        read_at
    )
    SELECT
        $4::bigint,
        boundary.topic_id,
        boundary.selected_post_number,
        statement_timestamp()
    FROM boundary
    WHERE boundary.selected_post_number > 0
    ON CONFLICT (user_id, topic_id) DO UPDATE
    SET last_read_post_number = GREATEST(
            public.topic_reads.last_read_post_number,
            EXCLUDED.last_read_post_number
        ),
        read_at = EXCLUDED.read_at
    WHERE EXCLUDED.last_read_post_number > public.topic_reads.last_read_post_number
    RETURNING user_id
)
SELECT
    boundary.topic_id,
    boundary.next_post_number,
    boundary.selected_post_number,
    EXISTS (SELECT 1 FROM upserted)::boolean AS advanced
FROM boundary
`

type MarkTopicReadBoundaryParams struct {
	TopicID     int64
	IsStaff     bool
	GroupIds    []int64
	ActorUserID int64
}

type MarkTopicReadBoundaryRow struct {
	TopicID            int64
	NextPostNumber     int32
	SelectedPostNumber int32
	Advanced           bool
}

func (q *Queries) MarkTopicReadBoundary(ctx context.Context, arg MarkTopicReadBoundaryParams) (MarkTopicReadBoundaryRow, error) {
	row := q.db.QueryRow(ctx, markTopicReadBoundary,
		arg.TopicID,
		arg.IsStaff,
		arg.GroupIds,
		arg.ActorUserID,
	)
	var i MarkTopicReadBoundaryRow
	err := row.Scan(
		&i.TopicID,
		&i.NextPostNumber,
		&i.SelectedPostNumber,
		&i.Advanced,
	)
	return i, err
}
