// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: unread.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const configureMarkTopicReadTransaction = `-- name: ConfigureMarkTopicReadTransaction :exec
SELECT
    set_config('statement_timeout', '2000ms', true),
    set_config('lock_timeout', '250ms', true)
`

func (q *Queries) ConfigureMarkTopicReadTransaction(ctx context.Context) error {
	_, err := q.db.Exec(ctx, configureMarkTopicReadTransaction)
	return err
}

const getTopicReadMarker = `-- name: GetTopicReadMarker :one
SELECT
    marker.last_read_post_number,
    marker.read_at
FROM public.topic_reads AS marker
WHERE marker.user_id = $1
  AND marker.topic_id = $2
`

type GetTopicReadMarkerParams struct {
	ActorUserID int64
	TopicID     int64
}

type GetTopicReadMarkerRow struct {
	LastReadPostNumber int32
	ReadAt             pgtype.Timestamptz
}

func (q *Queries) GetTopicReadMarker(ctx context.Context, arg GetTopicReadMarkerParams) (GetTopicReadMarkerRow, error) {
	row := q.db.QueryRow(ctx, getTopicReadMarker, arg.ActorUserID, arg.TopicID)
	var i GetTopicReadMarkerRow
	err := row.Scan(&i.LastReadPostNumber, &i.ReadAt)
	return i, err
}

const markTopicReadBoundary = `-- name: MarkTopicReadBoundary :one
WITH authorized_topic AS MATERIALIZED (
    SELECT
        topic.id AS topic_id,
        topic.next_post_number
    FROM public.topics AS topic
    JOIN public.areas AS area ON area.id = topic.area_id
    WHERE topic.id = $1
      AND topic.deleted_at IS NULL
      AND ($2::boolean OR topic.state <> 'hidden')
      AND (
        $2::boolean
        OR area.visibility IN ('public', 'authenticated')
        OR (
            area.visibility = 'groups'
            AND COALESCE(cardinality($3::bigint[]), 0) > 0
            AND EXISTS (
                SELECT 1
                FROM public.area_groups AS membership
                WHERE membership.area_id = area.id
                  AND membership.group_id = ANY($3::bigint[])
            )
        )
      )
),
boundary AS MATERIALIZED (
    SELECT
        topic.topic_id,
        topic.next_post_number,
        head.selected_post_number
    FROM authorized_topic AS topic
    LEFT JOIN LATERAL (
        SELECT COALESCE(max(post.post_number), 0)::integer AS selected_post_number
        FROM public.posts AS post
        WHERE post.topic_id = topic.topic_id
          AND post.deleted_at IS NULL
          AND post.redacted_at IS NULL
          AND post.author_id <> $4::bigint
    ) AS head ON true
),
upserted AS (
    INSERT INTO public.topic_reads (
        user_id,
        topic_id,
        last_read_post_number,
        read_at
    )
    SELECT
        $4::bigint,
        boundary.topic_id,
        boundary.selected_post_number,
        statement_timestamp()
    FROM boundary
    WHERE boundary.selected_post_number > 0
    ON CONFLICT (user_id, topic_id) DO UPDATE
    SET last_read_post_number = GREATEST(
            public.topic_reads.last_read_post_number,
            EXCLUDED.last_read_post_number
        ),
        read_at = EXCLUDED.read_at
    WHERE EXCLUDED.last_read_post_number > public.topic_reads.last_read_post_number
    RETURNING user_id
)
SELECT
    boundary.topic_id,
    boundary.next_post_number,
    boundary.selected_post_number,
    EXISTS (SELECT 1 FROM upserted)::boolean AS advanced
FROM boundary
`

type MarkTopicReadBoundaryParams struct {
	TopicID     int64
	IsStaff     bool
	GroupIds    []int64
	ActorUserID int64
}

type MarkTopicReadBoundaryRow struct {
	TopicID            int64
	NextPostNumber     int32
	SelectedPostNumber int32
	Advanced           bool
}

func (q *Queries) MarkTopicReadBoundary(ctx context.Context, arg MarkTopicReadBoundaryParams) (MarkTopicReadBoundaryRow, error) {
	row := q.db.QueryRow(ctx, markTopicReadBoundary,
		arg.TopicID,
		arg.IsStaff,
		arg.GroupIds,
		arg.ActorUserID,
	)
	var i MarkTopicReadBoundaryRow
	err := row.Scan(
		&i.TopicID,
		&i.NextPostNumber,
		&i.SelectedPostNumber,
		&i.Advanced,
	)
	return i, err
}
